actonlang/acton

- compiler/stack.yaml
> Switch to lts-17.14

- test/.gitignore
- test/Makefile
- test/for-break.act
- test/if-return.act
This adds two more test cases that are currently failing. Also revamped
the Makefile a bit to avoid repeating definition of test case and enable
parallel tests.
> Add more test cases

- compiler/ActonCompiler.hs
The order in which arguments are provided matters. gcc/ld will look for
things to link based on the compiled source files, thus the sources
should come before the linking args. Putting the libs to link first
becomes like a NOP since we have no unresolved references at that time.
I'm not sure why, guessing it has to do with different implementations
of gcc/ld, but this was working on OS X already before but trying to use
actonc under Linux would result in a lot of "undefined reference to X",
which are now all fixed.
Since we need -lkqueue on Linux, but there is no such library on OS X,
we use preprocessing to make compilation of actonc conditional based on
the host OS.
Note how this is not the only thing that needs fixing for everything to work correctly on Linux.
> Fix gcc linking

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Add feature request icon

- .github/ISSUE_TEMPLATE/feature_request.md
Soon going to need CI for the issues templates themselves. Meeeta ;)
> Fix issue template

- README.md
This shows the status of our CI tests.
> Add a test badge

- examples/helloworld.act
I'm now referencing this example in the top README.md but forgot to
include the actual source file ;)
Closes #62
> Add examples/helloworld.act

- compiler/ActonCompiler.hs
Rather than include a mostly useless header we just print the code which
makes it easier to pipe the result into a file. The CC command is also
moved to a separate option called --ccmd. I've found multiple times that
I just wanted the cc command and nothing else, which is now possible!
The downside is perhaps that previously one could do `actonc --hgen
--cgen`, get all the output and it would still be clear what parts were
what. If that functionality is important we could reimplement printing
of headers through the --verbose option or similar. Maybe we could
detect the output type, if it is a terminal or if we are piped to a file
and do output accordingly.
> Make --hgen/--cgen output clean code

- Makefile
Forgot to update path to actonc here :/ which resulted in artifacts
missing their version number etc.
> Fix version detection

- test/regression/105-type-inference-order.act
- test/regression/Makefile
This is a regression test for #105.
> Add test for type inference order dependency

- builtin/dict_impl.c
- builtin/exceptions.c
- builtin/exceptions.h
- builtin/float.c
- builtin/int.c
- builtin/list_impl.c
- builtin/range.c
- builtin/set_impl.c
- builtin/slice.c
- builtin/str.c
- builtin/tuple.c
- modules/random.c
- numpy/ndarray.c
- numpy/primitive.c
- numpy/protocol_impls.c
- test/regression/Makefile
... so as to match the compiler's naming schema.
> Renamed primitive RAISE to $RAISE,

- CHANGELOG.md
- compiler/Acton/Deactorizer.hs
- test/regression/109-passing-method-argument.act
> Fix passing actor method as argument

- compiler/Acton/Subst.hs
- compiler/Acton/Types.hs
- test/regression/103-dict-of-int.act
- test/regression/Makefile
> 103 dict inference fix

- builtin/int.c
- test/regression/Makefile
> Fixed typo in __ge__ for int.

- CHANGELOG.md
- docs/triage.md
Nothing too advanced, just like to have this written down so it is
easier for all of us to have a consistent view on how we prioritize
bugs.
> Add document explaining bug triaging & prio

- builtin/minienv.c
- builtin/minienv.h
- compiler/Acton/Types.hs
- rts/rts.c
- test/regression/109-passing-method-argument.act
- test/regression/Makefile
New attempt. The branch fixes issue #143, but also reveals an independent rts error when the fixed code runs test 105. Pushing with that test disabled for now. The rts error will be fixed in another branch.
> 143 generalization fix

- builtin/int.c
- test/regression/Makefile
> Fix divmod return value

- builtin/builtin_functions.c
- builtin/dict_impl.c
- builtin/int.c
- builtin/serialization_tests/multi_serialization_test.c
- builtin/str.c
- builtin/tests/tuple_test.c
- compiler/Acton/CodeGen.hs
- numpy/numpytests/str_test.c
> Replaced NEW(tuple) by NEWTUPLE.

- compiler/Acton/Env.hs
- compiler/Acton/Names.hs
- compiler/Acton/QuickType.hs
- compiler/Acton/Solver.hs
- compiler/Acton/Types.hs
- test/regression/Makefile
Fixes #174  and #176 (although test 176 is temporarily disabled due to bug 170)
> 174 checker fixes

- builtin/minienv.c
- compiler/Acton/CodeGen.hs
- compiler/Acton/Deactorizer.hs
- compiler/Acton/Prim.hs
- compiler/ActonCompiler.hs
- rts/rts.c
- rts/rts.h
- test/regression/Makefile
...  in terms of synchronous messaging. Resolves #170 and the non-termination of certain tests (now enabled).
> Reworked actor creation and initialization

- rts/rts.c
Instead of just connecting to a single database server, we can now
connect to multiple servers! The port used is specified with
--rts-ddb-port but can be specified per server by supplying the port
colon separated, like --rts-ddb-host localhost:1234 for port 1234.
This doesn't support IPv6 addresses today, like [::1]:1234, but the
database backend only listens to AF_INET anyway, so we can fix that a
little later.
Fixes #192.
> Support multiple database servers

- Makefile
- builtin/minienv.c
- compiler/ActonCompiler.hs
> Fix --version flag to not require otherwise mandatory FILE arg

- backend/Makefile
Not sure how things have worked so well when this has been incorrect. Oh
well.
> Fix build dependency declaration for backend

- Makefile
- compiler/ActonCompiler.hs
- compiler/Makefile
- test/Makefile
- test/regression/Makefile
> Move actonc to bin/actonc

- .github/workflows/tagged-release.yml
- .github/workflows/test.yml
- README.md
> Install uuid-dev & zlib1g-dev on Debian

- .github/workflows/tagged-release.yml
- .github/workflows/test.yml
> Clean up CI config cruft

- .github/workflows/tagged-release.yml
- .github/workflows/test.yml
All this info is contained in other output. It's just garbage more or
less.
> Remove superfluous messages

- .github/workflows/tagged-release.yml
- .github/workflows/test.yml
> Test on MacOS 11 / Big Sur

- .github/workflows/tagged-release.yml
I updated the artifact name in the test workflow but forgot to update it
in the tagged-release workflow. How many times is this repetition of CI
config going to bite me? :(
> Fix artifact name in release workflow

- Makefile
We now properly clean up all .o files in the make clean target.
clean-stdlib was removed and is now functionally part of clean-rts, i.e.
we only have three large components:
- compiler
- backend
- rts
The name "rts" is arguably misleading, since it also includes builtins
and stdlib, but what should it be called? "stuff"? ;)
Fixes #256.
> Revamp Makefile to fix clean targets

- compiler/Acton/CPS.hs
- test/regression/Makefile
> Cont env fix

- .github/workflows/test.yml
This enables parallel build of Acton.
> Do parallel build of Acton

- .github/workflows/test.yml
- debian/changelog.in
> Build on and for debian:bullseye

- .github/workflows/test.yml
Just cosmetic changes. Restructured some job steps but doing the same
thing.
> Remove TODO & fix up GH Action config

- compiler/Acton/CPS.hs
- test/regression/Makefile
> Added two more missing CPS cases.

- stdlib/src/numpy.h
> Add #pragma once to numpy.h

- compiler/ActonCompiler.hs
Blargh, argument priority is funny.
> Fix actonc --dev

- rts/rts.c
This reduces the number of places where we call new_work(), which wakes
up another worker thread. The basic idea is simple, as soon as we send a
message or do something that leads to new work, we call new_work() to
wake up another worker thread which can start processing that work,
potentially in parallel.
It turns out we woke up new workers in too many places. In particular
from the flush_outgoing function. When a continuation executes, outgoing
messages to other actors are collected in an outgoing queue and at the
end of the continuation, when we commit the result, we flush that
outgoing queue. We would then also call new_work() so that other actors
could start picking things up from the readyQ. It takes a little while
for the other thread to wake up. Since we are just done processing …
> Reduce worker threads wake ups

- test/Makefile
- test/test_async.act
Simple test to check if async functionality is working or not.
We are not running the test since it is currently failing.
@nordlander please have a look if you agree that this test actually tests async, like should these method calls be async or not?
Part of #361
> Add async test

- test/regression/Makefile
Also added support for tests where we explicitly expect a segfault and
not just any run time error.
> Add test of async method returning None

- .github/workflows/test.yml
Stack pulls these in anyway so no need to install via apt.
> Do not install alex & happy using apt

- .github/workflows/test.yml
I should have tested this before adding. Was thinking "what could
possibly go wrong". Well, it's not working and while I test and fix it
I'd rather back out the change.
> Disable tweeting from on release

- builtin/env.c
Fix compilation warnings on env.c on Ubuntu
> Fix to compile on ubuntu

- CHANGELOG.md
- test/Makefile
Yay, finally getting that sweet replication factor of 3, which means we
are doing quorum reads and writes!
Fixes #409, or uh, well, it's really #427 that did, but now we test it!
> Run DB App test using 3 DB nodes

- rts/rts.c
Fix a bunch of printfs to not print the log prefix and align some output.
> Fix RTS verbose / debug printfs

- builtin/env.c
We have to look for EPOLLRDHUP in addition to EPOLLHUP!
Fixes #441.
> Fix epoll disconnect detection

- compiler/Acton/CodeGen.hs
Added proper codegen of C casts on attributes selected from a class identifier. Fixes #486
> Fix codegen cast on class attrs

- utils/actonmon
Rather than hard code the query we let the user specify which command to
run towards the mon interface.
Also some cleanup.
> Generalize actonmon mon queries

- rts/rts.c
- test/test_db.py
We don't know that we received a second SIGINT or SIGTERM, it could be
that we first got a SIGINT and then a SIGTERM... so rephrasing the
message to reflect reality.
> Improve SIG* messages

- utils/gen_env.py
We want a newline on the last line...
> Fix generated end of file newline

- test/Makefile
- test/rts/ddb_test_server.act
- test/test_db.py
What a blunder... we tested, but we sort of ignored the return value,
duh....
> Correctly handle return values from DB tests

- builtin/env.c
- builtin/env.h
- examples/client.act
- examples/server.act
- stdlib/src/__builtin__.act
- test/rts/ddb_test_server.act
> Rename on_receipt to on_receive

- stdlib/src/__builtin__.act
> Rename to on_connect

- test/Makefile
- test/rts/ddb_test_client.act
Also fix the error callback to take conn arg.
> Enable rts client test

- rts/rts.c
It is apparently more robust etc, so we prefer to use sigaction rather
than signal. We already use sigaction in the DB.
Fixes #576.
> Use sigaction instead of signal

- compiler/Acton/Solver.hs
- compiler/Acton/TypeM.hs
- compiler/Acton/Types.hs
This is the same changes as in #605, which I backed out of the main branch by rewriting history. I did that since it also contained a merge commit of the main branch making our history very hard to read.
> Add str methods

- builtin/env.c
The RTS should generally be quiet.
> Do not print on new connection

- compiler/ActonCompiler.hs
When the compilation goes well, there's no need to be so verbose. If an
error occurs, we print both stdout & stderr from the process.
Fixes #613.
> Suppress make output

- compiler/ActonCompiler.hs
Some refactoring to simplify actonc.
> Actonc cleanup

- backend/actondb.c
My bad, sorry @aagapi for worrying about segfaults in actondb.
Fixes #627.
> Check mon fds are set before using

- CHANGELOG.md
- compiler/ActonCompiler.hs
- compiler/package.yaml.in
`actonc new foobar` will create a new project called 'foobar' with the
Acton project layout.
> Add actonc new project command

- .github/workflows/test.yml
It's not officially listed on GitHub but I just saw the issue
https://github.com/github/roadmap/issues/240 was closed a few days ago,
so let's try this out!
> Test on macos 12!

- builtin/__builtin__.h
- builtin/hash.c
- builtin/hash.h
- builtin/str.c
- builtin/str.h
- builtin/ty/src/__builtin__.act
- compiler/Acton/CodeGen.hs
- compiler/Acton/Normalizer.hs
- compiler/Acton/Parser.hs
- compiler/Acton/Printer.hs
- compiler/ActonCompiler.hs
- test/regression/Makefile
New attempt after fixing bug in str.c
> Add type bytes

- compiler/test.hs
Tasty doesn't seem to have a built-in way of printing some output of
tests but only when the test has failed. Likely because unit tests etc
normally doesn't run a program under the hood etc, they are much smaller
and have more deterministic failures.
Anyway, I've fixed it the pragmatic way here by passing around more
information. If we see a failure and we don't expect it, then we just
print stuff to stdout. The output of the test script will be somewhat
garbled, but this is essentially impossible to avoid since we are also
running the tests threaded.
Through the process, I've restructured quite a bit of the code and it's
now much easier to build up the test cases, simply calling the testFiles
function with a name for the test group, a directory and a list of
expected failures.
> Print debug output on test failures

- docs/acton-by-example/src/SUMMARY.md
- docs/acton-by-example/src/projects.md
- docs/acton-by-example/src/projects/directory_structure.md
There's now a new chapter in Acton by Example explaining the basics of
Acton projects and how they are used.
> Add section on Projects to AbE

- .github/workflows/test.yml
Might contain hints for fixing the decoding errors..?
> Show env in CI

- .github/workflows/test.yml
Switches the test-linux to a matrix and building across both Debian and
Ubuntu now!
> Add CI test to run on some Ubuntu versions

- compiler/Acton/Normalizer.hs
- compiler/Acton/Syntax.hs
- test/regression_auto/not_implemented.act
> Allowed docstrings in NotImplemented functions.

- compiler/Acton/Env.hs
- compiler/Acton/Solver.hs
- test/regression_auto/signature_with_typeargs.act
> Fix solver signature with typeargs

- compiler/Acton/Types.hs
- compiler/ActonCompiler.hs
Implements enhancements in issue #718
> 718 root main as default

- compiler/Acton/CodeGen.hs
> Added missing unalias when forming constructor names.

- builtin/class_hierarchy.c
> implemented __bool__, __str__ and __repr__ for classes object and value

- compiler/ActonCompiler.hs
There are various arguments to the compiler, like --kinds or --norm that
produces debug output from the different compilation passes inside of
the compiler. These are side effects from the compilation which means
they are subject to the up-to-date check, that is, if a file is deemed
up to date, then it will not be compiled and if it is not compiled,
there won't be any side effects run either. From a user perspective,
this is quite surprising as --deact will produce no output if it's
already been compiled. Now applying any of these flags will force
recompilation of the module and thus to produce the output.
It could be argued that the dump commands should be used to view this
information, but it's not the same, since it can only show the content
of a .ty file and simply doesn't have …
> Force recompilation for --sigs & --[ch]gen

- examples/print_time.act
- stdlib/src/_time.act
- stdlib/src/_time.h
- stdlib/src/time.act
- stdlib/src/time.ext.c
- test/regression_auto/125-async-actor-method-call__rf.act
- test/stdlib/test_time.act
- test/stdlib_auto/test_acton_rts_sleep.act
- test/stdlib_auto/test_time.act
> Join back the time and _time modules

- compiler/ActonCompiler.hs
Our logging functions include the path to the source code. It uses the
__FILE__ macro to achieve this and it is defined by which filename is
fed into cc. If we invoke cc with absolute filenames, we get absolute
filenames in __FILE__ and thus in our log messages, like so:
10:48:53.701706 DEBUG /home/kll/terastream/acton/stdlib/src/process.ext.c:   79: RTS  3: Pipe init stdin handle 0x7f2860001318
Somewhat shorter relative paths are much more elegant. We still have a
small challenge in that we compile both the system as well as some acton
project so we want to be able to differentiate between these. Thus, the
solution is to use relative paths that start at the parent directory of
the current project. Our stdlib is also organized as a project, so it
will now look like:
15:25:32.623690 DEBUG …
> Compile with relative paths for pretty log paths

- compiler/Acton/QuickType.hs
- compiler/Acton/Subst.hs
- compiler/Acton/Types.hs
in the absence of explicit signatures.
> Fixed inference of generic class methods

- Makefile
- compiler/ActonCompiler.hs
- compiler/package.yaml.in
> Add project level lock for actonc build

- Makefile
Our make targets for stdlib now include all source files in stdlib/src
and stdlib/c_src so that changing any files there will lead to make
rerunning those targets.
Also removed some older todo comments since those are now done!
Fixes #697.
> Improve dependency declaration for stdlib

- docs/wrapping_c_libraries.md
> Rewrite C lib guide for new style

- .github/workflows/test.yml
- debian/control
> Test on Ubuntu 20.04

- Makefile
Amazeballs how long this has been working without us noticing...
Fixes #781
> Fix variable definition order

- rts/rts.c
There's an implied newline....
> Remove newlines from log statements

- stdlib/src/process.act
- stdlib/src/process.ext.c
- test/stdlib_auto/test_process_pid.act
> Add process pid, stop, signal etc

- stdlib/src/process.act
- stdlib/src/process.ext.c
- test/stdlib_auto/test_process.act
- test/stdlib_auto/test_process_pid.act
- test/stdlib_auto/test_process_write.act
> Add process write(), done_writing() etc

- stdlib/src/process.act
- stdlib/src/process.ext.c
- test/stdlib_auto/test_process.act
- test/stdlib_auto/test_process_env.act
- test/stdlib_auto/test_process_pid.act
- test/stdlib_auto/test_process_wdir.act
It's now possible to set the working directory and the environment when
starting a process!
Part of #795
> Add wdir & env to Process

- stdlib/src/process.act
- stdlib/src/process.ext.c
> Rename wdir -> workdir

- stdlib/src/process.ext.c
Instead of a fixed size array we now malloc both the args and env lists.
Part of #795.
> Do malloced env & args

- rts/io.c
- rts/io.h
- stdlib/src/process.ext.c
We need this from all sorts of IO modules so moving to io.c!
> Make alloc_buffer common

- README.md
The 'main' actor is used as root actor if it exists!
> No need for --root argument anymore

- compiler/ActonCompiler.hs
> Include module name in error message

- compiler/ActonCompiler.hs
By always copying the .h file from src/%.h to out/types/%.h, any custom make targets would always think the source was fresher than the output .o file and thus run. We now avoid this by first comparing the source .h file with the target one.
On a AMD 9550 it takes 750ms to build numpy.o, and in total for all stdlib modules somewhere north of a second, which doesn't sound like much but is 10x more than with this fix. On slower machines it is even more noticeable.
I don't think there are any adverse performance consequences from this. Our header files shouldn't typically be that large, so this shouldn't be much of an issue. Anyway, it is still cheaper to compare two files than recompiling a large module.
> Make custom make more idempotent

- Makefile
- compiler/ActonCompiler.hs
- stdlib/Makefile
We've switched away from this approach overall, this just completes it for the last module, numpy!
Fixes #772.
> Stop partially linking numpy

- test/test_db.py
> Silence some non-integer warning

- CHANGELOG.md
- bin/runacton
a la shell style scripting, whop whop
Fixes #238.
> Add ability to directly run .act files

- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
> Test brew linkage and fix linking errors

- CHANGELOG.md
- backend/actondb.c
We can't go pointing off into the unknown, only forward the start_ptr if we know there is a next entry!
> Fix seed arg parsing

- CHANGELOG.md
- test/stdlib_auto/test_json.act
> Use inlined nested dicts

- CHANGELOG.md
- stdlib/src/process.act
- stdlib/src/process.ext.c
- test/rts_db/test_db_app.act
- test/rts_db/test_db_app.ext.c
- test/rts_db/test_tcp_client.act
- test/rts_db/test_tcp_client.ext.c
- test/rts_db/test_tcp_server.act
- test/rts_db/test_tcp_server.ext.c
> Improve rts db tests

- backend/client_api.c
This changes return code from -2 to -3 but I think that's what we mean!?
Part of #939
> Prefer symbol

- docs/acton-by-example/src/SUMMARY.md
- docs/acton-by-example/src/actors.md
- docs/acton-by-example/src/actors/async_method_call.md
- docs/acton-by-example/src/actors/attributes.md
- docs/acton-by-example/src/actors/concurrency.md
- docs/acton-by-example/src/actors/lifetime.md
- docs/acton-by-example/src/actors/root.md
- docs/acton-by-example/src/actors/sync_method_call.md
- docs/acton-by-example/src/control_flow/for.md
- docs/acton-by-example/src/control_flow/if_else.md
- docs/acton-by-example/src/control_flow/while.md
- docs/acton-by-example/src/hello.md
- docs/acton-by-example/src/hello/args.md
- docs/acton-by-example/src/hello/shebang.md
- docs/acton-by-example/src/primitives/dicts.md
- docs/acton-by-example/src/primitives/lists.md
- docs/acton-by-example/src/primitives/scalars.md
- docs/acton-by-example/src/primitives/sets.md
- docs/acton-by-example/src/primitives/tuples.md
- docs/acton-by-example/src/projects.md
- docs/acton-by-example/src/types.md
> Doc fix for --root & runacton

- backend/actondb.c
Fixes gossiping view to RTSs if they connect when there is a single seed DB server up (issue https://github.com/actonlang/acton/issues/951)
Remove some un-needed vector clock copies
> Also notify new gossip view to clients by agreement round leader

- stdlib/src/net.ext.c
- stdlib/src/process.ext.c
> Fix stdlib casts

- stdlib/src/net.ext.c
> long * -> long

- .github/workflows/test.yml
- Makefile
- compiler/ActonCompiler.hs
- examples/mathtest.act
- stdlib/Makefile
- stdlib/src/net.ext.c
- stdlib/src/numpy.h
> Bundle and use zig

- Makefile
- stdlib/src/xml.act
- stdlib/src/xml.ext.c
- test/stdlib_auto/test_xml.act
> Add xml module

- test/perf-benchgames/pidigits4.act
> Add pidigits benchmark game

- compiler/ActonCompiler.hs
> Add timing info for building executable

- compiler/Acton/Solver.hs
Significantly improves performance of issue #1025, but more can be done!
> Split solver input into disjoint constraint sets before simplification.

- Makefile
> Use zig v0.10.0!

- compiler/Acton/CPS.hs
> Added missing type conversion. (Shortest diff ever?)

- compiler/Acton/Transform.hs
- compiler/Acton/Types.hs
> Added lost constraints inferred on target exprs.

- builtin/ty/src/__builtin__.act
- compiler/Acton/Transform.hs
- compiler/Acton/Types.hs
- test/core_lang_auto/proc_callbacks.act
- test/regression_auto/indexed_extension.act
- test/regression_auto/indexed_target.act
> 1049 mut builtin

- compiler/Acton/Converter.hs
> Mended incomprehensible erasure of method decorators.

- builtin/env.c
- builtin/env.h
- compiler/Acton/Builtin.hs
- stdlib/src/file.ext.c
- stdlib/src/json.ext.c
- stdlib/src/net.ext.c
- stdlib/src/process.ext.c
> Replaced '__self__' by 'self'.

- Makefile
- backend/failure_detector/db_queries.c
> Do -Werror for all, enabling it on MacOS

- rts/rts.c
Use a debugger to print backtrace in case we hit SIGILL or SIGSEGV. This uses gdb on systems where it is available.
> Print backtrace on SIGILL & SIGSEGV

- Makefile
> Set -target in CFLAGS_DB

- stdlib/src/time.ext.c
> Fix time.monotonic

- backend/actondb.c
- backend/client_api.c
Explicitly handle EBADF select return status in client and server comm loops, assert on EINVAL and ENOMEM
> Socket reads

- Makefile
Also fix cleanup of libgc under clean-deps-rm
> Use slightly newer libgc which simplifies build

- compiler/Acton/Solver.hs
Fixed bug that gave the number of alternative solutions too little weight during constraint sorting.
> Better constraint sorting in the solver

- .github/workflows/test.yml
This should be possible now that actonc is statically compiled.
> Test run on Ubuntu 18.04

- test/builtins_auto/dict.act
- test/builtins_auto/max.act
- test/builtins_auto/min.act
> Fix dict eq test & add min/max tests

- compiler/Acton/Syntax.hs
- compiler/Acton/Types.hs
and stopped the same pattern in protocols.
> Added NotImplemented as a class body option

- compiler/Acton/QuickType.hs
> Fixed bug computing commonEnv of a single branch.

- builtin/ty/src/__builtin__.act
- test/core_lang_auto/instantiate_conrete_class.act
> Made value.__init__ abstract!

- compiler/ActonCompiler.hs
When create new projects using `actonc new foo`, we now check if git is available and if so, initialize the repo. Also write a .gitignore file.
> git init new projects

- builtin/__builtin__.c
- builtin/__builtin__.h
- builtin/str.c
- builtin/str.h
- builtin/ty/src/__builtin__.act
- test/builtins_auto/builtin_functions_test.act
This fixes builtin functions hex, bin and ascii, and changes __repr__ for str to behave better.
> fixed bugs in some string functions

- .github/workflows/test.yml
v0.2.0 was removed, updating to v0.2.1
> Upgrade action

- docs/acton-by-example/src/primitives/sets.md
> AbE: set discard

- compiler/Acton/CPS.hs
- compiler/Acton/Normalizer.hs
- compiler/Acton/Parser.hs
- compiler/Acton/QuickType.hs
- compiler/Acton/Types.hs
> Exceptions

- compiler/Acton/Types.hs
Final solution will have to await the (re)introduction of polymorphism for assigned variables.
> Temporary fix to avoid witnesses that escape their generalized scope.

- stdlib/c_src/numpy/protocol_impls.c
or else the GC patchy script fails :P
> Fix the little things

- compiler/ActonCompiler.hs
When the --root argument is not provided binTasks contains all modules we know about, like all project source files, which means we invoke the buildExecutable target for all files and if they don't contain a 'main' actor, the file is skipped.
We now filter the binTasks, or rather preBinTasks to binTasks a little earlier. This will simplify other changes to our build system later on when we now have a cleaner definition of binTasks.
> Filter binTasks

- compiler/Acton/Env.hs
... when compiling __builtin__.
> Fix global qualification of class and protocol names

- builtin/ty/src/__builtin__.act
- compiler/Acton/CodeGen.hs
And made their constructors unconditional. Changed Msg accordingly.
> Fixed codegen for classes with NotImplemented bodies

- stdlib/src/xml.ext.c
- test/stdlib_auto/test_xml.act
- Fix xml parsing of default namespace declarations
- Added tests for default and prefix-mapped namespace declarations
> Fix xml parsing of default namespace

- Makefile
- base/stdlib/numpy/init.c
- base/stdlib/numpy/ndarray.c
This is worse but it's nice getting rid of libbsd since it's so hard to build right.
> switch Numpy from arc4random to rand & ditch libbsd and libmd

- docs/acton-by-example/src/SUMMARY.md
- docs/acton-by-example/src/actors/async_method_call.md
Also avoid use of sleep since we never want to expose this to users. Replace it with computation of primes.
> Explain async actor method calls

- compiler/test.hs
- test/compiler/subdash/.gitignore
- test/compiler/subdash/src/cookie-bookie.act
- test/compiler/subdash/src/foo-bar/a-b.act
- test/compiler/subdash/src/hello.act
Tests sub-modules and dashes in filenames.
> Add subdash project test

- Makefile
- base/builtin/env.c
- base/rts/io.c
- base/rts/io.h
- base/rts/rts.c
- base/src/acton/rts.ext.c
- base/src/file.ext.c
- base/src/net.ext.c
- base/src/process.ext.c
- base/src/time.ext.c
- test/stdlib_auto/test_net_dns.act
> Use on_error rather than exception in net.DNS

- base/src/net.ext.c
Also remove all frees, not sure how this snuck in there...
> Include DNS query hostname in on_errors

- compiler/Acton/CodeGen.hs
- test/core_lang_auto/multibranch_assign.act
> Restored lost env info guiding joined assignments in multiple branches.

- compiler/ActonCompiler.hs
Using alternative output, like --sigs for printing signatures or --cgen, we now suppress various log output by effectively assuming the same as --quiet.
A bug meant that we would hit an error when running for a single .act file and there is no actor called main. This is now fixed, so we still perform the final compilation even when there is no main actor. The full compilation can thus be tested.
If alternative output is enabled, like --cgen or similar, we exit early and avoid the final compilation.
> Improve support for alternative output from actonc

- docs/acton-by-example/src/SUMMARY.md
- docs/acton-by-example/src/types.md
- docs/acton-by-example/src/types/explicit.md
Document actonc --sigs. Restructure things around types a bit.
> AbE: document --sigs

- CHANGELOG.md
- base/src/__builtin__.act
- docs/acton-by-example/README.md
- docs/acton-by-example/src/SUMMARY.md
- docs/acton-by-example/src/security.md
- docs/acton-by-example/src/security/capabilities.md
> AbE: explain capability based security

- CHANGELOG.md
- compiler/Acton/CommandLineParser.hs
- compiler/ActonCompiler.hs
> Support actonc build --cpedantic

- Makefile
- base/build.zig
- compiler/ActonCompiler.hs
Set the env var CPEDANTIC and base will be compiled with --cpedantic
Part of #805.
> Support using --cpedantic for base

- CHANGELOG.md
- base/builtin/list.c
- test/builtins_auto/list.act
lst->data is NULL for a 0 length list, which we can't copy, so got to check!
And for reversed() we have to actually return the reversed copy of the list, not the original! ;)
Add some tests for it...
Fixes #1455
> Fix list reversal

- base/rts/rts.c
- base/src/http.act
- builder/build.zig
- test/stdlib/test_http.act
Adds a rather basic http & https module. There are many things to improve here, but it basically works. We can adjust and fix over time. Having a http module in stdlib is a big and important step!
There are some tests but nothing is run automatically, primarily because I do not want to introduce a dependency on having Internet connectivity. We should test against ourself though! And we should run unit tests..
> Add http module

- compiler/Acton/Types.hs
> Added forgotten unaliasing of class names in 'except'.

- compiler/Acton/CodeGen.hs
> Fixed incorrect environment for method table initialization.

- base/builtin/int.c
- test/core_lang_auto/exceptions.act
> Add exception test

- CHANGELOG.md
- base/src/__builtin__.act
Man, this has bugged me for so long. Now got proper indent aligned on 4 spaces. Previously a mix of 2, 3 and 4.
Update changelog too
> Properly indent __builtin__.act

- compiler/Acton/Kinds.hs
This fixes location error  in error messages more generally than indicated in title of #1478.
> fixes #1478

- CHANGELOG.md
- base/builtin/dict.c
- base/src/argparse.act
- test/stdlib_auto/test_argparse.act
> Add argparse module

- base/src/argparse.act
- base/src/testing.act
- test/stdlib_auto/test_argparse.act
Also added the help arg to add_cmd()
> argparse: print commands with their help text

- base/src/time.act
- test/stdlib_auto/test_time.act
- add/sub duration
- comparison
> Additional arithmetic and comparison for time.Instant

- docs/acton-by-example/src/primitives/sets.md
While previous text did explain the empty set stuff it had a weird angle. This is more direct and to the point.
> AbE: empty set

- test/stdlib_auto/test_testing.act
Compiler bug fixed, so now the test testing program compiles, thus using the intended code.
> Fix test_testing

- base/builtin/int.c
- test/builtins_auto/int.act
Fixed a bug in rounded in the int instance of Integral.
> Fix int rounded

- base/src/time.act
- compiler/Acton/Solver.hs
- compiler/Acton/Subst.hs
- compiler/Acton/Types.hs
Added constraint that forces the type of first parameter of instance methods to be castable to Self.
> Relate "self" to Self

- compiler/Acton/Solver.hs
- compiler/Acton/Types.hs
> 1602 fix self issues

- base/src/term.act
Now that we have default argument values we can add the n argument with a default value to 1, which controls how many steps we should move in that direction.
> Add n arg to term move functions

- base/src/http.act
- base/src/net.act
- base/src/time.act
- docs/acton-by-example/src/primitives/sets.md
- test/stdlib/test_http.act
- test/stdlib_auto/test_random.act
Now that we support default values to arguments, we can make use of it in some stdlib and in some examples / docs.
> Add default argument values in various places

- test/core_lang_auto/defaults.act
There are multiple cases that we do not properly handle when calling object methods. Need to fix. At least these tests will highlight the failures.
> Add test of object method default arg values

- base/rts/rts.c
We have supported automatically printing a backtrace using gdb if we crash with a SIGILL or SIGTERM. Now there's a new mode which launches gdb interactively so the user can play around, quite useful!
./app --rts-bt-debug
> Add interactive backtrace debug mode

- Makefile
- debian/changelog.in
> Use distribution=tip mostly

- base/src/json.act
These are pure, not mut. Not sure why I explicitly set them to mut before, did we have some bug related to that?
> Fix function effect in json module

- Makefile
- backend/build.zig
- base/build.zig
- base/src/snappy.act
- base/src/snappy.ext.c
- builder/build.zig
- compiler/ActonCompiler.hs
- test/stdlib_auto/test_snappy.act
Snappy is a fast (de)compression library and this is our stdlib module for it!
> Add snappy stdlib module

- base/src/http.act
- test/stdlib/test_http.act
Also revived the test_http to the level that it compiles and testing against dummyjson exercises the code that uses int(x, 16)
> Prefer int(x, 16) over home built hex_to_decimal

- .github/workflows/test.yml
In addition to compiling telemetrify we run its nso-replay test.
> Run a telemetrify test

- base/builtin/dict.c
Now dicts have three stages in their life cycle:
- when created with d = {}, only three words are allocated (class pointer, a size field with value 0 and a null pointer to the real dictionary).
- at the first insertion, the null pointer is replaced by a small table with place for two elements, which is searched without hashing.
- at the third insertion, a proper hash table with room for five elements is used (which is from that stage on resized as needed).
The first change ("lazy" creation) is the most important; it is not clear that the second stage is worthwhile.
> improved dictionaries

- base/src/testing.act
Almost hard to quantify at this point, but this improves the testing module exceptions by a fair bit. It's not final by any means but it's a solid improvement.
> Improve testing exceptions.. by a lot

- CHANGELOG.md
- Makefile
This version has some fixes to the incremental GC mode which we could try out!
> Upgrade GC to latest

- CHANGELOG.md
- base/src/__builtin__.act
Type inferrencing got this as a list[None] which can't possibly be correct :P
> Make KeyError key: value

- CHANGELOG.md
- base/src/time.act
The default type is value, which is immutable, so we have to specify object for this to work!
> Fix time.Stopwatch.reset

- base/rts/rts.c
- base/src/re.ext.c
> Enable LLDB in crash_handler

- .github/workflows/test.yml
- Makefile
Let's do caching per macos but keep a common cache for Linux tests. It appears to work...
> Per macos cache

- base/rts/rts.c
I figured placing wctx on the stack in the main_loop would fix our issues with the GC cleaning up the WorkerCtx, but alas, the compiler aggresively optimizes away the wctx since it's "not used much", like we just do a pthread_setspecific etc so it ends up in some temporary register and later on its not visible anymore and thus cleaned up.
I've run the test thousands of times now, there are some other intermittent hangs, but no segfault crashes. Before this patch, I would get segfaults probably on the order of 1 in 30-50, so maybe 2-3% and that seems entirely gone now.
> Place wctxs in global array to avoid GC

- .github/workflows/test.yml
Clear out caches and build output so we know we are getting freshly built stuff!
> Ensure rebuild before perf test

- compiler/Acton/Deactorizer.hs
- compiler/Acton/Kinds.hs
- compiler/Acton/Names.hs
- compiler/Acton/Syntax.hs
- compiler/Acton/Transform.hs
- compiler/Acton/Types.hs
+ correct types of defaultable parameters
+ type-correct assignment of default values
> Better scoping rules

- test/typeerrors/ex24.act
- test/typeerrors/ex24.golden
I would like to get the line numbers in the error message...
> Added typeerror ex24

- base/builtin/dict.c
- test/builtins_auto/dict1805.act
> Fix dict delete ordering issue

- base/builtin/list.c
- base/src/__builtin__.act
- test/builtins_auto/list.act
> Add list.index(val, start, stop)

- compiler/Acton/Solver.hs
(much faster solved by brute force only).
> Stopped interspersed improvement when solving effect constraints

- .github/dependabot.yml
- CHANGELOG.md
> Add dependabot.yml for updating GH Actions

- Makefile
- backend/build.zig
> Simplify actondb build

- base/src/http.act
- base/src/net.act
- base/src/net.ext.c
- test/stdlib_tests/src/test_net_tcp.act
Callback to indicate when the remote side has shutdown / initiated close of its side of the TCP/TLS connection
> Add remote_close callback to TCPConnection / TCPListenConnection / TLSConnection

- base/src/buildy.act
- cli/src/acton.act
> Fix deps JSON, update URL & path properly

- compiler/Acton/CodeGen.hs
- test/core_lang_auto/proc_init.act
> Fixed missing CONSTCONT when a cps'ed __init__ is invoked

- test/core_lang_auto/exceptions_else.act
> Add test for try/else

- cli/src/acton.act
If zig-pkg add is run with a new URL, the existing one is updated.
> Update URL in zig-pkg add

- base/src/__builtin__.act
- test/builtins_auto/test_all.act
- test/builtins_auto/test_any.act
These were commented out, presumably due to a compilation error. I do get an error when I commented them out but I have reshaped the functions somewhat, forcing the bool function and checking it's result, which seems to be working.
Also added tests.
Fixes #1936
> Re-enable any() & all()

- compiler/Acton/QuickType.hs
Fixes #1821
(opening on behalf of @sydow who's experiencing trouble logging in to GitHub)
> Fix issue returning unboxed fixed size integer

- test/stdlib_tests/src/test_testing2.act
Depending on how well specified the test functions are, the type inference might look a little different. I already fixed the compiler but never added tests for it.. until. now.
> Make sure we find test functions

- .github/workflows/test.yml
> Test Orchestron & Snappy lib

- compiler/Acton/Solver.hs
... awaiting a full overhaul of the effect system.
> Weakened the leaking seal check

- compiler/Acton/Kinds.hs
- compiler/Acton/Types.hs
- test/core_lang_auto/builtin_shadowing.act
Unalias now works correctly. Resolves #1814
> Moved away from ad hoc tcon and tvar env in Kind

- .github/workflows/test-app.yml
Zig builds fail for some reason and perhaps it's related to running in a container?
> Run test-app CI job on Ubuntu (not Debian container)

- base/src/testing.act
Maybe we should give hints about excessive filtering or something?
> If there is nothing to test, say so

- .github/workflows/test.yml
> Upload macos aarch64 tip release

- base/src/time.act
> Print correct month

- base/src/file.act
- test/stdlib_tests/src/test_file.act
These functions help us go from relative paths to absolute ones and vice versa. Ideally should not be based on slash as separator but I'm not sure what else to do, so here we are now.
> Get absolute paths from relative and vice versa

- compiler/Acton/CodeGen.hs
- compiler/Acton/Names.hs
- test/core_lang_auto/exceptions_volatile.act
> Volatile vars in try

- base/src/testing.act
- cli/src/acton.act
- compiler/Acton/Types.hs
> Add __name__ & inject module name in test discovery config

- base/src/re.act
- base/src/re.ext.c
- test/stdlib_tests/src/test_re.act
Also fix string positions + test coverage
And avoid potential infinite loop.
> Add re.split

- base/builtin/dict.c
- base/src/__builtin__.act
- test/builtins_auto/dict.act
- test/builtins_auto/dict_test2.act
> Add pop / get_def / pop_def to dict & Mapping

- .github/workflows/test-app.yml
So we can get backtraces on crashes..
> Install gdb in test-app

- base/builtin/str.c
- test/builtins_auto/string_interpolation_unicode.act
Forgot to reset iterator pointer on second iteration. Incredible how this has gone by unnoticed...
Fixes #2057
> Fix to_str_noc iteration

- base/src/net.ext.c
Ensure we mark the socket as invalid (-1) when we close it as well as guard against actin on it if it is invalid, both for TCPConnection and TCPListenConnection.
Fixes #2060
> Mark socket as invalid on close & guard

- cli/src/acton.act
I accidentally broke it while improving the reading of build config.
> Fix acton fetch

- base/src/__builtin__.ext.c
- test/builtins_auto/test_complex.act
This fixes segfaults when more than 1 complex key is added to a dict.
> Add support for complex numbers as dictionary keys

- compiler/actonc/test/project/qualified_root/.build/sys
- compiler/actonc/test/project/simple/.build/sys
These were never meant to be committed.
> Remove temp files

- compiler/actonc/Main.hs
We used to discover the root actor on having both the name "main" as well as a particular signature, i.e. it should take Env as the single argument.
The discovery is now only based on the name "main". The root actor is naturally still expected to take Env as argument, but it now becomes a type error instead if there is a misalignment. This is more explicit as otherwise the effect is just that we don't output a binary at all.
Fixes #2077
> Discover root actor based solely on name

- compiler/lib/src/Acton/Types.hs
Only allow the action-proc duality inside actors
> Ensure annotated effect equals the inferred one

- base/builtin/i16.c
- base/builtin/i32.c
- base/builtin/i64.c
- base/builtin/int.c
- base/src/qcheck.act
- base/src/random.act
- base/src/random.ext.c
- test/builtins_auto/qcheck_bitops.act
> Implement Logical for int

- compiler/actonc/Main.hs
- compiler/lib/src/Acton/CommandLineParser.hs
> Add --list-imports to show list of imports

- compiler/lib/src/Acton/Solver.hs
Include any contained TCons instead, and only proceed if the lower bounds are free from TOpt and TNone.
> Don't just ignore TOpt when computing GLBs on upper bounds

- base/src/logging.act
I think this is a better name than StdoutSink, plus we actually want to send to stderr per default - that is weird log messages should go.
> Add ConsoleSink

- base/src/uri.act
- test/stdlib_tests/src/test_uri.act
Rewrite the URI module to do much more thorough URI parsing. This might not be perfect but certainly a step up from the old one. Added a bunch of tests too.
> A proper URI parsing module

- base/src/buildy.act
- cli/src/acton.act
- compiler/actonc/test/typeerrors/ex24.golden
- compiler/lib/src/Acton/Env.hs
- compiler/lib/src/Acton/Solver.hs
- compiler/lib/src/Acton/Subst.hs
- compiler/lib/src/Acton/Types.hs
Ignoring the complications caused by mutating methods in these classes until we have proper immutable variants.
> Support covariant depth subtyping for list, dict and set

- base/builtin/int.c
- base/src/qcheck.act
- test/builtins_auto/lshift.act
> fixed bug in lshift for int (issue #2136)

- cli/src/acton.act
- cli/src/acton_cli/github.act
Avoid some segfaults.
Fixes #2141 
Fixes #2137
> Fix pkg upgrade correctness

- cli/src/acton.act
The main project is built with --dev for test cmd, let's do the same for the deps.
> Use --dev to build deps in test cmd

- base/src/process.act
- base/src/process.ext.c
- cli/src/acton.act
- test/rts_db/test_db_app.act
- test/rts_db/test_tcp_client.act
- test/rts_db/test_tcp_server.act
- test/stdlib_auto/test_process.act
- test/stdlib_auto/test_process_env.act
- test/stdlib_auto/test_process_many.act
- test/stdlib_auto/test_process_pid.act
- test/stdlib_auto/test_process_write.act
> Improve error message on list test

- compiler/lib/src/Acton/CPS.hs
where just the inner one needs preprocessing
> Fix cps transformation for nested lambdas

- base/src/fs.act
- test/stdlib_tests/src/test_fs.act
This adds a new fs module, eventually the successor to the file module.
There's a new fs.glob() function for doing glob matching.
Fixes #2172
> Add fs.glob

- base/builtin/str.c
- base/src/__builtin__.act
We can now directly convert None and optionals to a str, oh so convenient!
> Allow optionals to str(?value)

- compiler/lib/src/Acton/Parser.hs
> Use cheap cons, not expensive append

- base/builtin/dict.c
- base/builtin/list.c
> Make del idempotent

- base/rts/q.c
- base/rts/rts.c
when the waiting state is entered
> Ensure that the actor waitsfor link is atomically set

- ecolift/CLAUDE.md
- ecolift/repos/.gitignore
> Add ecosystem lift process documentation

- base/src/__builtin__.act
- base/src/buildy.act
- base/src/http.act
- base/src/logging.act
- base/src/testing.act
- base/src/time.act
- ecolift/CLAUDE.md
Convert % formatting and string concatenation to f-strings across stdlib.
> Use f-strings in stdlib

- cli/src/acton.act
- compiler/actonc/Main.hs
- compiler/lib/src/Acton/CommandLineParser.hs
`acton doc` has been a stub, this now properly calls `actonc` and exposes our new doc gen functionality.
> Add `acton doc` command

- base/src/acton/rts.ext.c
Use nanosleep on platforms that support it, i.e. Linux and Macos, then fall back to uv_sleep() which offers millisecond granularity on other platforms.
> Improve acton.rts.sleep platform coverage

- compiler/lib/src/Acton/Diagnostics.hs
- Clarify the two types of errors handled: parse errors vs compiler errors
- Explain that errorDiagnosticWithLoc handles Acton's own errors (not Megaparsec)
- Document that reachOffset is just borrowed for offset-to-line/column conversion
- Add examples of error types handled by each function
> Explain functions in Diagnostics.hs

- compiler/lib/src/Acton/Normalizer.hs
> Fixed "2320"

- compiler/actonc/test/typeerrors/ex19.golden
- compiler/actonc/test/typeerrors/ex24.golden
- compiler/actonc/test/typeerrors/ex9.golden
- compiler/lib/src/Acton/Env.hs
- compiler/lib/src/Acton/Kinds.hs
- compiler/lib/src/Acton/Printer.hs
- compiler/lib/src/Acton/Solver.hs
- compiler/lib/src/Acton/Subst.hs
- compiler/lib/src/Acton/Syntax.hs
- compiler/lib/src/Acton/TypeEnv.hs
- compiler/lib/src/Acton/TypeM.hs
- compiler/lib/src/Acton/Types.hs
- compiler/lib/src/Acton/Unify.hs
- compiler/lib/test/6-cps/cps_volatiles.input
- compiler/lib/test/6-cps/cps_volatiles.output
- compiler/tests/ProtExtElim.hs
- test/core_lang_auto/coerced_index_targets.act
- test/stdlib_tests/src/test_testing.act
- test/stdlib_tests/src/test_testing2.act
Only solve top-level constraints, begin separation of univars from tyvars
> Solver overhaul step 1

- compiler/actonc/Main.hs
- compiler/lib/src/Acton/CommandLineParser.hs
Move --sub to gopts and reorder args.
> Move sub arg to gopts

- base/src/testing.act
- cli/src/acton.act
> Add `acton test --show-log` to always display test log

- compiler/actonc/Main.hs
When determining if a module is up-to-date, also verify that the .ty file can be read successfully. If it cannot (due to corruption, torn writes, or compiler version changes), trigger recompilation instead of crashing.
This prevents CI failures and dependency traps where project B cannot build because project A has unreadable .ty files that were considered 'up-to-date' based only on timestamps.
Refactored checkUptoDate to return Maybe (imports, nameInfo) instead of Bool, combining the up-to-date check with .ty file reading to avoid double-reads and provide a cleaner API.
> Handle corrupted .ty files gracefully
