.github/workflows/test.yml, Makefile, README.md, backend/Makefile, backend/failure_detector/Makefile, compiler/ActonCompiler.hs
This enabling building the distributed backend, including installing the pre-requisites, which differ a tad between Linux and OS X.
=> Enable building the distributed backend

Makefile
This makes it easier to recompile parts of Acton when we've only
modified one part.
A proper declarative Makefile would make this redundant, but until we
have that in place, this makes it a lot easier to iterate on changes.
=> Split make targets

.github/workflows/test.yml, builtin/bool.h, builtin/minienv.c, builtin/minienv.h, builtin/serialize.h, compiler/ActonCompiler.hs
This avoids some multiple definition errors we see on Linux (Debian buster, gcc 10.2) and with it, the test suit passes.
This builds upon the fixes in #14. Using two PRs to let the work be reviewed independently.
=> Make Acton work on Linux

.github/ISSUE_TEMPLATE/blank_issue.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
There should now be four choices when creating a new issue:
- bug report
- feature request
- blank issue
- ask a question (redirecting to github discussions)
=> Add Github issue templates

CHANGELOG.md
We've had enough changes for a version, notably Linux support, so time
for a release!
There is now a changelog where we can jot down changes.
=> Release v0.4.0 & add changelog

CHANGELOG.md, compiler/ActonCompiler.hs
Change --version to print a simple version string for acton:
acton 0.3.0.20210726.13.3.29
--version --verbose will include more information, like the cc version:
acton 0.3.0.20210726.13.3.29
compiled by ghc 8.10 on linux x86_64
cc: cc (Debian 10.2.1-6) 10.2.1 20210110
We also include the cc version in the internal compiler error messages
as extra information. Also, printing of internal compiler error messages
has been lifted out into its own function.
=> Add cc version information to --version

compiler/ActonCompiler.hs
We now separate the system library from a users project library. This is
the first step to being able to install Acton system wide.
Closes #25
=> Put project output in separate library

CHANGELOG.md, builtin/__builtin__.h, builtin/int.c, test/regression/arithmetic_add.act, test/regression/arithmetic_divide.act, test/regression/arithmetic_multiply.act, test/regression/arithmetic_subtract.act, test/regression/subtract_off_by_one.act
Wrong order of operators meant simple subtraction would return wildly
incorrect results. Now righted the order! Order has been restored to the
galaxy.
Test cases have been added, pushed in a separate commit so we can see how the tests fails before the fix.
=> Fix integer subtraction

compiler/ActonCompiler.hs
We got to link with libActonProject first, since this is where our
project specific things are, which can reference things (builtins /
stdlib) in libActon. This means -lActonProject goes before -lActon!
=> Link Acton libs in right order

.github/workflows/test.yml, Makefile
This adds a new make target to produce a tar ball of Acton. We run this
in CI and upload the result as an artifact.
Part of #4.
=> Build & upload release artifacts in CI

.github/workflows/tagged-release.yml, README.md
The test workflow, when run on the main branch, produces a release which
has been known as `latest`. It is now called `tip` to avoid confusion
when talking about the "latest release" - would that be `latest` or the
latest release with a proper version number? `tip` is easier and still
distinguishes this from a nightly, which it is not.
The new release workflow is essentially a copy of the test action but with
smaller variations like the tag is not statically set to 'tip' (was
'latest') but is based on the tag that is pushed. The trigger is of
course the pushing of a tag rather than any branch.
The test action is changed to ignore tags. The pre-release-tip job is
also changed to once again (I used this in early testing) use eine/tip,
since that action? will force push the tip tag. We still …
=> Add release workflow

.github/workflows/tagged-release.yml, CHANGELOG.md
This instructs make to not include the date & time in the version string
but just the version, like v0.4.1
Closes #35.
=> Fix version number for releases

.github/workflows/test.yml, CHANGELOG.md
This should make the tip releases available with a stable URL:
- https://github.com/actonlang/acton/releases/download/tip/acton-darwin-x86_64.tar.bz2
- https://github.com/actonlang/acton/releases/download/tip/acton-linux-x86_64.tar.bz2
The old URL style that includes the version number still remains. We are
just uploading the assets twice!
Closes #64.
=> Make tip releases available via stable URL

CHANGELOG.md, Makefile
tip releases already include the date and time in the version, like so:
$ ./actonc --version FOO
acton 0.4.1.20210805.13.46.55
The filename of a tip release would not reflect that, it would just be
called like `acton-linux-x86_64-0.4.1.tar.bz2`. This changes so that the
filename will be `acton-linux-x86_64-0.4.1.20210805.13.46.55.tar.bz2`,
which should make it easier for folks that often download tip releases
to differentiate them from each other.
Closes #63.
=> Include date & time in tip release filename

CHANGELOG.md, compiler/ActonCompiler.hs, examples/count.act, rts/rts.c, test/Makefile, test/argv.act, test/count.act
It is now possible to configure the RTS to use the distributed database
backend for storing the run time state of actors. It was previously
enabled through a build time flag and the database host and port was
hard-coded. There are two run time options:
--rts-ddb-host, the hostname to connect to
--rts-ddb-port, the TCP port to connect to, default is 32000
A third option, --rts-verbose, was also added to make the RTS a bit more
chatty about it is doing, in particular in regards to the backend.
An example, examples/count_forever, is added that shows how run time state persistence and restoration works.
I have been contemplating whether I should modify argc & argv before I pass it into the Acton application. My initial thought was no, let's not. Let's simply "reserve" that arguments starting …
=> rts: Add runtime args for DDB

docs/wrapping_c_libraries.md
This is a short and simple guide to wrapping C libraries in Acton that I
wrote while implementing the time module (see #83).
This sort of depends on #82 as it assumes --hgen and --cgen will output clean code without any headers or the C compilation commands.
=> Add doc to explain C library wrapping in Acton

Makefile, compiler/ActonCompiler.hs
I think this just makes it clearer what it actually is. It is the path
to where the Acton system lives, syspath! The internal variable is
called syspath so this also aligns with that.
Closes #90.
=> Change --path to --syspath

backend/Makefile
It fails intermittently so until we've fixed that, I'm disabling the test.
Related to #86
=> Disable the queue_unit_tests

Makefile, modules/acton/rts.act, modules/acton/rts.c, modules/acton/rts.h, test/Makefile, test/rts_sleep.act
Which implies we are adding the acton.rts module too! There's a simple
test case added.
I don't know where to write documentation, like it would be nice to have
a docstring under the function but there's no function defined in Acton!
Just a function type signature, so no place to put the docstring from
which we can later generate documentation. I added a big comment for
now.
As stated in this comment, acton.rts.sleep() is sort of bad and
shouldn't normally be used, but it is deliberately implemented the way
it is and can be useful for benchmarking scenarios and similar.
Closes #91.
=> Add acton.rts.sleep() function

Makefile, modules/random.act, modules/random.c, modules/random.h, test/Makefile, test/test_random.act
This adds a random module with a single function called randint(min,
max) that returns a pseudo-random number between min and max. It's using
the basic srand() / rand() for simplicity, portability and speed (we
don't need true randomness). To make it more idiomatic Pythonic I
decided to just use time() as the initial seed, which is set up when
initializing the module.
The code avoids skew and should return good random numbers. Not
cryptographically secure in any way but still not skewed in anyway.
The Acton RTS uses threads to execute actors. rand() is not thread safe,
but I don't think that matters here. AFAIK, since rand() is a PRNG, it
actually means rand() is a deterministic function based on the initial
seed. It is not thread safe and by that, I think it is meant that it
will not act …
=> Add random module

.github/workflows/test.yml
Instead of updating the existing tip tag and release, we first remove it
and create a new one. This way, the creation date is also updated which
means it will be listed first on the release page.
Closes #85.
=> Recreate tip release

rts/rts.c
The RTS when used with the distributed database backend reads in any
previously existing state from the database. If there is no state, it
should bootstrap. A bug crept in during the introduction of DDB as a run
time arg that made the RTS always bootstrap actors, regardless of any
previously found actor state in the database. This is now fixed.
=> Fix database backed RTS bootstrap

Makefile
Linux (and likely other) systems will prevent copying a file to a
destination that is currently being run. I've run into this a bunch of
times with the actondb executable where I am running it locally for
testing and then run make in the acton repo, which copies backend/server
to dist/actondb. If actondb was running, the system would refuse this as
the system does not allow modifying a running program. By moving it in
place we work around the issue.
=> Workaround build problem when running DDB

Makefile, test/Makefile
Turns out we didn't have a test case and as a result it appears we've
missed to compile the .ty file. I had it manually compiled locally and
never noticed...
=> Add test of acton.rts.sleep()

Makefile, test/Makefile, test/test_acton_rts_sleep.act
I've gone under the assumption that tests in the test/ directory were
automatically run based on how it looked previously. Since we moved some
tests under test/regression/, this is no longer true. Only tests in the
regression folder are run automatically.
Now enabling the tests we have, which also showed how I forgot to git
add the acton.rts.sleep() test. That's what happens when you try to cook
and code at the same time ;)
=> Enable tests

test/regression/125-async-actor-method-call.act, test/regression/Makefile
When calling an actor method like we are here, it should be run async,
but we are instead seeing it is run synchronously.
=> Add regression test for async actor method call

CHANGELOG.md, Makefile
Previously the math module lived in a math/ subdirectory and
modules/math.h was just a copy of math/math.h. We recently moved simple
modules like math to live directly in modules/, and thus, modules/math.h
is now the real file. We should not remove it when cleaning!
=> Do not clean away modules/math.h

test/regression/Makefile
Most of the test output, in particular when running the negative tests
that we expect to fail compilation, produce rather verbose output and it
can be difficult to differentiate an actual error from a currently
expected error (in a negative test). Thus, we now reduce this output
clutter by piping stdout and stderr to /dev/null. There's also a small
header in front of each test that makes it easier to keep them apart.
=> Reduce output clutter from running tests

test/regression/178-after.act, test/regression/Makefile
This actually acts a little funny on main HEAD right now, showing the output from both actors but it sure hasn't been able to run the after stuff on the counter actor as it should, showing the error. Testing this on an older commit, it is working as expected.
The test might not be great as it relies on acton.rts.sleep() working and not interfering with the scheduling of the other thread... it's not as minimal as it could be, but on the other hand, it does show a problem in a not entirely unrealistic setting.
=> Add broken after regression

Makefile, compiler/ActonCompiler.hs, rts/rts.c
This enables various debug printing while the RTS is running. It is very
detailed and will most definitely have a major performance impact. Thus,
it can only be used for debugging purposes in controlled environments.
Debug output is enabled with the --rts-debug option.
To completely eliminate any overhead in normal operations the debug
prints are not just conditioned on the runtime --rts-debug flag but are
also conditioned behind a build time flag. We build the rts lib twice,
once with the flag enabled and once without. actonc chooses which one to
link with when compiling the .act file. That is, given the program
helloworld.act, to run with debug output, we first have to compile with:
$ actonc --rts-debug --root main helloworld.act
Then also run the program itself with:
$ ./helloworld …
=> Add RTS debug mode

rts/rts.c
We default to 3, which seems sensible for a distributed quorum-based
database. Read and write quorums are replication_factor/2+1.
=> Add database replication factor argument

builtin/exceptions.c, modules/time.c
This it what Python's time module raises, so let's mimic it rather than
using ValueError (I freestyled that).
=> Use runtime exception in time module

compiler/ActonCompiler.hs, test/Makefile
There are currently some warnings being produced when compiling the C
code generated by actonc. We believe this likely indicates bugs and
thus, by treating these warnings as errors we are able to detect such
situations earlier. There are situations where the warnings are
irrelevant, but we should probably explicitly disable those warnings in
that case.
=> Treat warnings as errors

.github/workflows/tagged-release.yml
I added this to the test workflow but forgot to add it for the release
workflow, so when we now actually try to build a release it fails miserably :/
=> Install libbsd-dev on Linux in release workflow

.github/workflows/test.yml
Instead of running on pesky ubuntu, we switch to Debian :)
Debian sid has a newer libkqueue-dev that we are after.
It is potentially bad to run debian sid, maybe we want to stick to like debian stable (11 / bullseye) but let's see. For now, this is probably the best way of getting a recent enough version of libkqueue-dev. Once we move to native epoll or uring, we won't need it anyway so can switch to another debian version.
We want to build .deb files on debian, so I prefer trying to align the different CI jobs on fewer distribution versions...
=> Build on debian sid

.github/workflows/tagged-release.yml
Oh gosh, what a mistake. I forgot to update the tagged release workflow
with the change to use debian for the build in the test workflow. We
really should have a single definition for this but oh well.
=> Use debian for release builds too

Makefile
Avoid putting actonc in two locations; dist/actonc and dist/bin/actonc!
We now put it in just one location and the make targets to do so are now
neater!
Fixes #248.
=> Output actonc in correct location

Makefile
I believe this completes the DAG for targets where actonc is used. It is
now possible to run make -j32 or so to build Acton in parallel.
=> Add dependency on $(ACTONC) when actonc is used

.github/workflows/test.yml
We changed it to macos-XX.YY. We just upload the one from macos-11 for
now, not sure if there is a point in uploading the one from macos-10.15
too?
=> Fix artifact name

.github/workflows/tagged-release.yml, .github/workflows/test.yml, README.md, compiler/ActonCompiler.hs
The Acton RTS was written for kqueue on MacOS. We got it running on
Linux by using a shim called libkqueue which pretends to be kqueue
towards the application but translates these calls into epoll on Linux.
We ran into some problems, which we thought were related to libkqueue
but ultimately turned out to be something else. As we did ascribe those
problems to libkqueue, we resorted to replacing it with epoll.
It turned out that libkqueue wasn't the problem, but switching to native
epoll is a good thing, so all's well!
=> Remove dependency on libkqueue

CHANGELOG.md, rts/rts.c
On very low CPU count machine, like with a single CPU, Acton would not
work at all as the first thread runs the eventloop and without a second
thread there will be no workers at all. We now force a minimum of 4
worker threads. CPU affinity is normally set on the threads but when we
do not have a 1:1 mapping between worker threads and we don't set
affinity at all and let the threads roam - up to the normal scheduler to
figure out!
Fixes #258.
=> Use a minimum of 4 worker threads

.gitignore
We don't actually ignore all these files, in particular the Makefile and
.github directory. Using ripgrep and similar to search in this project
directory will honor .gitignore and thus not include these files in the
search results. Since we want them in there, I'm changing the ignores.
=> Remove some gitignores

.github/workflows/test.yml, Makefile, compiler/Makefile, debian/changelog.in, debian/control, debian/copyright, debian/rules, debian/watch, test/test_json.act
This adds new make targets to build a .deb. We invoke this from CI and upload the resulting .deb as an artifact.
The only caveat is that the pre-release .debs do not reflect the actual version number, for example, actonc will report like 0.6.0.202010919.143412 whereas the .deb file will be just 0.6.0. This is due to the order in which this information is known. We currently generate this build date when compiling the acton compiler but the .deb build process needs to know about it up front. To make it work, we have to move when we generate this. We should take care to not rebuild unless something has actually changed, something that's not just the version number. Not sure if this is possible or not!? Anyway, that's for another issue.
Fixes #60.
=> Build debian package

compiler/Acton/Env.hs, compiler/Acton/Solver.hs
The constraint solver frequently splits constraint sets into independent groups with no common type variables.
Closing each group with respect to this invariant is straightforward, with the exception of the internal Sel
and Mut constraints. Since these constraints are solved by picking a type from the environment that contains
the required attribute, free variables in that attribute's type might end up in the solution even if those
variables weren't part of the the original constraint set. Previously the closure operation didn't include
the possibility that constraints might relate via such indirectly shared type variables, but this has now
been fixed.
(Note: only class attributes need to be considered in this extended closure operation, since protocol
attributes cannot contain free type …
=> Fixed constraint grouping to also consider free environment types variables.

README.md, debian/control
They are pulled in via Haskell stack, so no need to install via apt.
Fixes #297.
=> Remove dep/install of happy & alex

Makefile, backend/Makefile, compiler/ActonCompiler.hs
We change so that actonc uses cc rather than gcc per default.
In our own makefiles we use $(CC) which most of the time means cc but does make it possible for people to choose. It's sort of good makefile practice...
Closes #40.
=> Use cc & $(CC)

Makefile
Finally! We now align the version contained in actonc, displayed with
actonc --version and the version of the deb package!
We compute the VERSION_INFO once and then pass it into the debian build
process to tag the inside content.
Fixes #271.
=> Fix deb version

README.md, docs/building-acton-from-source.md
Clean up the main readme a bit by moving the guide for how to build
Acton from source. With binary packages provided, it is not as
relevant.
Fixes #275.
=> Move build from source guide

README.md, docs/install-acton-from-tar-ball.md
After we added support for Acton projects, the getting started guide
needed some adaptation since we got rid of the .acton file concept.
Also restructured a bit and moved the install from release tar ball to a
separate document so the readme is even more to the point.
Fixes #276.
=> Fix getting started

.github/workflows/test.yml
We used to only store the actual .deb file as an artifact but there are
more files produced as part of the .deb build target. We now store all
of them in a deb/ directory and save that directory as an artifact. This
should make it easier to restore and finally add the files to a apt repo.
=> Store all .deb related artifacts in deb dir

debian/control
We don't need the -dev libraries at run time, only as Build-Depends.
Fixes #299.
=> Depend on non-dev libraries

.github/workflows/test.yml, README.md
This automatically adds the produced .deb into our own apt repo.
We only run this job for tagged releases for now.
Fixes #272.
=> Add GitHub Action job to update apt repo

.github/workflows/test.yml
We can now automatically update the homebrew repo when new versions of
Acton become available.
Fixes #235.
=> Automatically update homebrew repo

Makefile, compiler/ActonCompiler.hs
This adds a --numeric-version to actonc and makes use of it in the main Makefile.
Closes #220.
=> Add --numeric-version

Makefile
This was just plain wrong. Also protoc-c uses relative file locations,
so if we call protoc-c with a long file path, that is going to reflect
in the output.
The output is committed to git, so we should generate something that is
fairly similar. We now do!
=> Fix protoc-c invocation

Makefile, deps/yyjson.c, deps/yyjson.h, rts/rts.c, utils/actonmon
This adds monitoring function to the run time system. It is enabled with --rts-mon /tmp/mon_socket after which the RTS will listen on the UNIX Domain Socket /tmp/mon_socket. For any incoming request, we will dump the current stats for all worker threads.
There's a new thread to deal with the monitor socket. We only accept a single connection at a time. I want the monitoring thread to be completely standalone, i.e. I do not want to mix in listening on various fds into our normal eventloop. This is simple, which is good.
The protocol is a quick hack of a line protocol. The client sends "WTS" (worker thread stats) and gets a single line reply, which is a JSON document. To encode data we use yyjson, which is now included in our code base.
There is a new utility in utils/actonmon which can …
=> Add RTS monitor

rts/rts.c
Properly zero out worker thread stats by enumerating over num_wthreads
rather than a hard coded 32 (works on my machine!). Also means we move
it till after we have found out how many worker threads we have.
=> Fix worker thread stats zeroing

rts/rts.c
Reverts actonlang/acton#363
This was just wrong. I was reading code in the wrong window and didn't verify my assumptions. Should not send patches, in particular like these, as a "quick thing before next meeting".
=> Revert "Fix worker thread stats zeroing"

rts/rts.c
We now have a configurable number of worker threads although we still
default to the number of detects CPU cores (logical cores a.k.a. threads
really). This makes it possible to just play around with what happens
with lower count or whatever.
The fixed number of max worker threads (32) was rather low. It's bumped
up to 256, now using a single define MAX_WTHREADS so it is consistent
and easy to change. There is also a check that we don't actually try to
run with a higher number.
Alternatively I guess we could malloc this structure but I dunno... this
just felt simple.
=> Add arg for worker threads & fix stats init

Makefile
I previously added this target as it was required to override the one
above it that is a generic target for all the .c files in the
failure_detector directory. When I added, I implemented an actual target
that generates these .c files from the .proto file.
However, our strategy here is not to generate these files on every
build. Rather, we generate them once and have the output checked into
git. Thus, I've turned this target into a no-op instead.
Anyone wishing to regenerate the files can do so manually and check in
the resulting files in git.
=> Skip protobuf generation

Makefile, compiler/ActonCompiler.hs
This adds some basic support for building Acton on the Apple M1 silicon.
Also found that I mostly need #382.
=> Add some MacOS Apple M1 / arm64 / aarch64 support

compiler/ActonCompiler.hs
While actonc appears to currently work correctly on macos on x86_64, it
recently failed after I added a test case to the build process. Not
quite sure what is going on but the build environment is probably
somehow more clean than after actonc has been installed. I assume that
it is currently working as some default library path leaks through.
Anyway, to fix so that actonc builds correctly in the Homebrew clean
room environment, I'm adding /usr/local/lib. I think this really is the
correct thing to do.
=> Add /usr/local/lib to lib path on macos on x86_64

.github/workflows/test.yml
We have been getting duplicate GH Actions run because we trigger both on
the push to a branch and when a pull request is created.
We must have the pull_request trigger since otherwise we wouldn't run
our Action for forks, and any normal user will fork acton to submit code.
Running on any push has been convenient, as all you need to do for GH
Actions to run is to push! It wouldn't wait for you to create a PR or
whatever. However, since a PR must be created in order to merge the
code, it's never been a question of /if/ but of /when/ certain jobs
would run.
The result has been that we get duplicate builds and it's just sort of
annoying and consumes resources.
Now changing so that we only build on pushes to the main branch and to
tags starting with 'v' plus for any branch that a PR is created …
=> Do not run CI on push to branches

compiler/ActonCompiler.hs
We don't have a deliberate strategy or approach to position independent
compilation but have relied on defaults of our compilation stack. Acton
is a special case because it includes compilation as part of its run
time, like we compile builtin.o, when building Acton and then later on
use it when running actonc. Compilation flags, such as -pie, need to
align. Since we haven't been using explicit flags, we can get a mismatch.
ISTM we are effectively doing -no-pie, so I'm now adding it. This should
avoid a problem on Linux using Homebrew.
=> Compile with -no-pie

Makefile, compiler/ActonCompiler.hs
We now have two libAction:
- libActon_dev, for the development profile
- libActon_rel, for the release profile
This is more consistent than the previous solution where we always used
libActon and override certain modules (rts.o) that were specially
compiled with libActonRTSdebug. The two new archives are complete and do
not rely on each other in any way.
Thus, actonc will now link using libActon_dev OR libActon_rel.
All o-files are now compiled as a _dev.o and _rel.o file, using
CFLAGS_DEV and CFLAGS_REL for the respective flags. Right now, those are
-g for dev mode and -O3 for release mode.
Fixes #399
=> Expand on dev / rel compiler profiles

CHANGELOG.md, Makefile, rts/rts.c
We now always set the variables DEV or REL depending on if we are in dev
or release profile. Replaced the use of RTS_DEBUG with DEV.
=> Rename & always set compiler profile variable

CHANGELOG.md
I think Changed is meant to convey user visible changes. This is
internal, so putting under Fixed.
=> Move note to Fixed

test/Makefile, test/count.act
This enables a very basic test of the RTS together with the distributed database.
Replication seems to be broken right now (#409) so we use a single DB node and resumption also appears broken (#408) so that's disabled too. We just start a simple app and tell the RTS to use the DB to save state. We don't verify that it actually does, like it could just be a giant NOOP, but we assume that we have done enough things correctly that we do attempt to use the DB and second that any failures will be catastrophic, crashing the application or similarly which we will notice and fail the entire test.
Related to #225. This is like a mini-version of that.
=> Enable CI test of simple app together with the database

.github/workflows/test.yml, backend/actondb.c, test/Makefile, test/test_db.act, test/test_db.py
test_db.py is a new script that can orchestrate the setup and testing of
an Acton application together with the distributed database. Multiple
database nodes are started and their status read (from stdout) to ensure
that they agree on their membership before proceeding to run the Acton
application, specifying arguments to use the database backend.
There's an accompanying Acton application, test_db.act, that is written
to be a small and simple test of the database. By calling actor methods
on other actors, we exercise the database, since each call becomes a
message and continuation. We also check that the timer queue works by
invoking one method with after 0:
Resumption of the application is not tested since that is currently
broken. We also do not test running the application with a …
=> Add DDB test harness

rts/rts.c
This is a temp fix to issue 409 to enable distributed DB tests before proper fix to client DB gossip.
=> Temp fix to issue 409

CHANGELOG.md, rts/rts.c
The env actor was never serialized and as a result, for a system that resumes
from the database, we don't have a env actor and any actor method call on env
will fail catastrophically (segfault).
Since the env actor is a sort of constant actor that might not be scheduled for
execution by the main_loop, we might not serialize it. Thus, to fix this, we
simply serialize it just after it has been created.
Fixes #408.
=> Serialize env actor

CHANGELOG.md, rts/rts.c
Only pin worker threads to CPU cores through process affinity when there
are just as many of both.
=> Only do CPU affinity when wthreads == num_cores

.github/workflows/test.yml, builtin/env.c, rts/rts.c, test/Makefile, test/rts/exit_0.act, test/rts/exit_1.act, test/rts/wthreads1.act
This changes how env.exit() is implemented and rather than directly
calling the C exit() function and abruptly killing everything, we now
let the RTS worker threads process any currently running continuation
until completion and then shut them down one by one until no worker
threads remain.
Fixes #454.
=> Exit App / RTS cleanly

rts/rts.c
We had some log messages that would print a partial log message on the
start of an operation and print the rest on completion. Since stdout is
line buffered, this meant we had to flush the output and if anything
printed log messages in between the output would look all messed up.
Avoid the complexity by always logging a complete line!
=> Do single line log messages

rts/rts.c, test/test_db.py
We now enforce that the user must specify enough database hosts, using
--rts-ddb-host to reach the replication factor, i.e. if
--rts-ddb-replication is 3, --rts-ddb-host must be specified at least 3
times, like ./app --rts-ddb-host localhost:32000 --rts-ddb-host
localhost:32001 --rts-ddb-host localhost:32002
The idea is that when we connect to a database node, we will communicate
with it and find out about other database nodes that we can connect to,
so that we will reach the required number for the configured replication
factor. With a replication factor of 3, we want to connect to 3 servers!
However, the dissemination of DB servers isn't implemented yet, so the
DB client has to be given all the DB servers, yet we didn't force this,
so setting a higher replication factor than the number …
=> Ensure enough DDB hosts to meet replication factor

rts/rts.c
It's not very pretty rewriting argv since the ps output will lie about
the command line, thus we do a bit of extra copying to avoid mangling
argv!
=> Avoid rewriting argv

.github/workflows/test.yml
Although technically we can update the apt repo after we've built the
.deb files, we really do want to wait for the test jobs as to ensure we
pass all tests before we update the repo with new releases etc.
Fixes #467.
=> Let CI jobs depend on all previous jobs

rts/rts.c, test/Makefile
Silly misplaced +1 resulted in just getting the wrong value, like for
--rts-wthreads=7, we would read s=7 as the argument, when it should just
be 7.
Even sillier that I (manually) tested this but I believe I made some
final cleanups to the code after that testing, which is probably when I
misplaced the parentheses.
Fixed a test case for it too.
=> Fix --opt=arg style parsing of argument

backend/client_api.c, backend/client_api.h, rts/rts.c, utils/actonmon
This adds some statistics for the DB client library so we can get an
idea of how much time we are spending waiting on the DB.
All the functions / operations in the DB client library have been
instrumented to track the following:
- called;     // Number of calls of this op, incremented on start
- success;    // Number of successful calls of this op
- error;      // Number of failed calls of this op, includes all errors
- no_quorum;  // Number of failed calls with NO_QUORUM_ERR
- no_msg_cb;  // Number of failed calls with NO_SUCH_MSG_CALLBACK
- time_sum;   // nanoseconds spent waiting for op to complete
- time_100ns; // bucket for <100ns
- time_1us;   // bucket for <1us
- time_10us;  // bucket for <10us
- time_100us; // bucket for <100us
- time_1ms;   // bucket for <1ms
- time_10ms;  // …
=> Add DB client lib statistics

builtin/env.c
with $Connection$newact(fd). Fixes #484.
However, it should be noted that in the context of issue #485, the actor constructors of env.c still differ from the compiler generated signatures because the former take the liberty of avoiding the continuation-passing style where it's not strictly needed. See #485 for further elaboration.
=> Replaced the incorrect use of $NEW($Connection,fd)

Makefile, deps/netstring.c, deps/netstring.h, rts/rts.c, utils/actonmon
Thus far we have used the Luck protocol - that is reading a bit of data
on the socket and just hoping it is enough to either recognize a command
or in the other direction, to get all the data. Last commit on the
actonmon client I had to adjust the recv to get more data so we get it
all.
We still want a simple line protocol, so we are now doing netstrings!
It's just taking the content and prefixing it with the content length
and a colon followed by the content, then ending the whole thing with a
colon.
Our command "WTS" thus becomes "3:WTS," and our JSON response becomes...
well, something very long, but now prefixed with like 20132:{...},
I'm using a simple netstrings library for this. Beyond more robust
reading, we can now also collect multiple commands and execute them all.
We don't …
=> Use netstrings for RTS Monitor interface

compiler/Acton/Deactorizer.hs, compiler/Acton/Env.hs, compiler/Acton/Types.hs, stdlib/src/__builtin__.act
That is, actors with method signatures that lack a corresponding def.
Currently this is only allowed when compiling with the --stub flag.
Moreover, the compiler now checks that abstract actors aren't instantiated (from within Acton code).
=> Opened up for 'abstract' actors.

Makefile, backend/actondb.c, backend/failure_detector/vector_clock.c, rts/rts.c, utils/actonmon
This adds a monitor interface to the ActonDB, just like we support in
the RTS. It uses a unix domain socket to expose JSON encoded data via
netstrings as a line protocol.
There is only a single supported query command now called "membership"
and it returns the local node ID and the vector clock view. By comparing
this view between the nodes in a cluster we can see if they all agree on
whose a member.
Unlike the RTS, the implementation here does not use a separate
monitoring thread but is rather part of the one big main loop that we
have. This means we do not have to worry about locking data structures.
Similar to the RTS, we limit ourselves to a single client at a time. The
second client that tries to connect will simply have to wait for the
first one to finish.
actonmon supports fetching …
=> Add monitor interface to ActonDB

test/Makefile, test/test_db.py
This changes so that we use python unittest for the control flow of our DB app tests rather than some home grown hack. We also use the mon socket on the DB (introduced in #499 / #401) rather than regex parsing stdout - much better!
=> Improve DB app tests

test/Makefile, test/rts/ddb_test_server.act, test/test_db.py
This adds an app recovery test, where we want to check that an
application has correctly recovered its state from the database upon
restart. Unlike the existing app recovery test, this one is based on a
TCP server, which makes it much faster, more robust and avoids the
timing issues that we have with the current app recovery test.
The count app outputs a number every second. We cannot lower the sleep
in between numbers, partly because after X doesn't take integer seconds
as arguments but also because we depend on killing the application
precisely when it has counted to 3. We then expect it to continue
counting from there. If the app is too fast, we might get racy
conditions and end up killing the app too late.
Since we now interact over TCP, a query completes in "no time at all"
and the …
=> Add TCP based app recovery test

builtin/env.h, utils/gen_env.py
Same as I did for env.c, just for env.c.
=> Skip generating header for some funcs

rts/rts.c
We initiate a graceful shutdown when receiving SIGINT OR SIGTERM. If we
receive a second signal while we are gracefully shutting down, we will
shutdown immediately.
Fixes #507.
=> Handle SIGINT & SIGTERM

builtin/env.c, builtin/env.h, stdlib/src/__builtin__.act, test/Makefile, test/env/listen_err.act, test/rts/ddb_test_server.act
env.listen(port, cb) has previously taken a single callback cb that is
invoked both when there are incoming connections to the listening socket
as well as for errors, in which case the callback was called with a None
argument. This is confusing, bad, bla bla. Better to have a separate
callback, which we are now introducing, so the new signature is:
env.listen(port, cb_on_connect, cb_on_error)
An error when trying to establish the listening socket will now be
reported by calling the callback function provided via cb_on_error.
There's a new test case to cover precisely this test case.
Fixes #471.
=> Separate env.listen error callback

compiler/ActonCompiler.hs, compiler/package.yaml.in
If we are not compiling a source file that is located in an Acton
project, we create a temporary directory where we place all the
intermediate output files. For debugging purposes it can be rather
useful to inspect and even modify these files, which is made rather
tricky when it's always a temporary directory.
To allow for simple debugging actonc now takes a --tempdir option
that allows us to specify the directory to use for the intermediate
output. It also implies that actonc will not remove the temporary
directory. Additionally, the commands that actonc run to compile the C
files and place O-files into libraries are written to a build.sh script,
so that it can easily be run again manually once the files have been
modified.
Fixes #444.
=> Allow specifying actonc temp dir

builtin/env.c, builtin/env.h, compiler/Acton/Builtin.hs, compiler/Acton/Prim.hs, rts/rts.c, rts/rts.h
The __resume__ method is run immediately after an actor has been
deserialized from the database upon resumption of the system and allows
us to add extra hooks when necessary. For example, for socket related
actors, we want to invoke the error callback so that the user
application code can recreate the socket.
=> Add actor resume method

rts/rts.c
Naming the main thread masks out the process name in some top / ps
output and similar. It is more useful to show the process / binary name
rather than the thread name (which would always be 'main').
Fixes #526.
=> Do not name main thread

Makefile, builtin/env.c, builtin/env.h, rts/rts.c, stdlib/src/__builtin__.act, test/test_db.py
When a ListenSocket actor is resumed from the database, its error
handler is now called so that the Acton application is notified that the
ListenSocket is no longer working.
We unconditionally call the error handler because there is no way that
the ListenSocket survives a resume. We serialize it many times to the
database in normal operations but we only deserialize and resume it when
we start up fresh (or in the future when we migrate an actor). Either
way, the listen socket has a local fd in the kernel and that will not
survive either circumstance so it assuming it broken and reporting via
the on_error callback is the only sane recourse. The Acton application
should have an error handler that sets up the listening socket anew.
We really should not need to create the cb_err attribute, …
=> Call error handler on resume of ListenSocket

builtin/env.c, builtin/env.h, stdlib/src/__builtin__.act
Seems cleaner to call it just on_connect rather than cb_on_error. It
takes the type action so we know it's a callback, no need to duplicate
that information by calling it cb_... I think.
=> Rename to on_connect & drop cb_ prefix

examples/server.act, stdlib/src/__builtin__.act, test/rts/ddb_test_server.act
Previously env.listen only took a single callback which was used to
signal both new client connections as well as errors in establishing the
listening socket. The argument would either be a Connection or None to
indicate an error. Now that we have separated errors into its own
callback we can always pass a Connection to the on_connect callback
handler. This makes it easier and cleaner to write application code.
Fixes #536.
=> Always pass Connection to on_connect callback

builtin/env.c, stdlib/src/__builtin__.act, test/rts/ddb_test_server.act
We install a receive handler on a Connection actor by calling the
on_receive() method and when a message is received by the Connection it
will execute this callback. The only argument passed used to be the
message content itself, which could make it somewhat difficult to
understand on which Connection the message was received. We now pass
both the connection and the message so that the handler function can
more easily understand which client Connection is being dealt with.
Fixes #520.
=> Pass connection argument to on_receive

builtin/env.c, test/Makefile, test/rts/ddb_test_client.act, test/test_db.py
We're getting an error when we try to add the same fd to epoll twice but with different filters. By clearing out the old stuff first, we can then register our interest in EPOLLIN.
Fixes #542.
=> Fix epoll stuff for TCP client connection

builtin/env.c, builtin/env.h, stdlib/src/__builtin__.act, test/test_db.py
Just like for ListenSocket we call the registered error handler when we
resume from the database.
Fixes #534.
=> Implement Connection resume support

CHANGELOG.md, builtin/env.c, stdlib/src/__builtin__.act, test/env/listen_err.act, test/rts/ddb_test_server.act
The Connection or ListenSocket instance that generates an error which
calls the registered error handler is now passed as an argument to the
error handler, so it knows which instance is reporting an error.
This makes it much easier to write an application dealing with these
errors.
Fixes #547.
=> Pass Connection / ListenSocket to error handler

.github/workflows/test.yml, test/test_db.py
MacOS should now be configured to write a core file if we encounter a
segfault and we should detect it and upload it, together with two of the
test binaries, as artifacts so we can inspect them separately!
=> Save and upload core files on Mac in CI

builtin/env.c, builtin/env.h, test/rts/ddb_test_server.act, test/test_db.py
Add a simple test case for light stressing of our TCP server stack. It now connects 2000 times (though sequentially) to a test server. This doesn't work unless we clean up fds since the default open file descriptor limit is 1024.
We now clean up fds when a client disconnects!
Our MAX_FD is now 1024, to align with the default fd limit of 1024. This does need to be improved further though, since a user can increase the fd limit beyond 1024 and we will still crash.
=> Cleanup fds

backend/client_api.c
Rather than exit(0), so now we can differentiate it from a normal
program run, much better!
Related to #579.
=> DB client now does exit(1) on error

backend/client_api.c
This was a sort of catch-all during development and it's time to remove
it. We should try to deal with errors in a more fine granular way.
Fixes #579.
=> Do not exit on error in DB client api

Makefile, backend/actondb.c, backend/comm.c, backend/db.c, backend/failure_detector/db_queries.c, backend/log.c, backend/log.h, backend/queue.c, backend/skiplist.c, rts/rts.c
Rather than printf() log message, we now use the same log.c library that
is used in RTS, though with a slightly different set of modifications.
Log output is now sent to stderr rather than to stdout as previously.
Not all printf() statements have been replaced but most have. I've
mapped most log lines to log_debug() but have lowered the level of some
messages to log_info(). Rather than scrub all this in one go, I figured
we could over time adjust the levels as we see fit.
We support writing the log to a file with `--log-file=foobar.log`. If
file logging is enabled, no log output is written to stderr.
It might seem weird to have two log libraries and in particular with
different set of modifications but that was quite deliberate, since the
use in the DB and RTS are quite different. For …
=> Use log.c lib in ActonDB

Makefile, compiler/ActonCompiler.hs, stdlib/src/_time.act, stdlib/src/_time.c, stdlib/src/_time.h, stdlib/src/time.act, stdlib/src/time.h
With this change the stdlib is now able to build native Acton modules. Previously, all modules have been implemented in C and thus we've only used actonc stub compilation to get .ty files. Now we support both with correct dependencies in between (assume all C modules need to be built first).
The time module, written in C, has been renamed to _time and a new time module in Acton has been added. It wraps all the existing functions in _time, so the interface of the time module is backwards compatible. We can now add in other functions to the time module, written in Acton.
actonc now correctly keeps dev and release profile compiled output apart by including _dev or _rel file ending for the libActonProject archive. Further, the up-to-date-check of output files has been fixed to not inspect .c …
=> Revamp stdlib build process, improving actonc and restructure time module

Makefile, compiler/ActonCompiler.hs
We now automatically infer stub mode compilation if there is a .c file
with the same filename (ignoring the extension) as the act file. For
example, if we are compiling _time.act and _time.c exists, we will
assume stub mode compilation.
Chased import files are stub checked separately so that the main target
can be normally compiled while one of its dependencies can be stub
compiled.
--stub has been removed in a number of places in the Makefile since we
can now detect it. Notably __builtin__.act is the only file that still
has it, since we compile the C files differently and there is no
__builtin__.c
Fixes #596
=> Infer stub mode compilation on presence of .c file

Makefile, compiler/ActonCompiler.hs, stdlib/Makefile
For a stub compiled .act files we will now run make for the
corresponding .c and .h targets, if there is a Makefile at the root of
the project directory and if the files exist. For example, actonc will
compile accordingly:
- src/foo.act  -> out/types/foo.ty
- src/foo.c    -> out/lib/foo_dev.o
- src/foo.h    -> out/types/foo.h (just copied)
Given the presence of foo.c and foo.h, src/foo.act will be stub compiled
into out/types/foo.ty and src/foo.h will be copied as-is to
out/types/foo.h. If a Makefile exists at the root of the project
directory, src/foo.c will be compiled by running `make
out/lib/foo_dev.o` (or _rel.o). Thus, we offer a hook point for custom
compilation rules, since many C modules will need to be linked or
include various flags.
Our stdlib, being organized as an Acton …
=> Add custom stub compilation via Makefile

Makefile, compiler/Acton/Env.hs, compiler/ActonCompiler.hs
Since we're already hard coding stuff for __builtin__.act it doesn't
hurt hard-coding some more, in this case stub mode compilation.
We no longer need to specify --stub anywhere in our Makefile, which
means that we could potentially remove the --stub argument completely
but as I'm uncertain on whether there might be other weird edge cases
where it could be useful, I'm leaving it in for now.
This is also in preparation for the actonc build command where we won't
be able to specify --stub specifically for __builtin__.act since we are
just running build for the entire stdlib project.
Part of #594.
=> Hardcode stub compilation for __builtin__.act

compiler/ActonCompiler.hs
The argument parsing of actonc has now been changed to support the
concept of commands.
We used to take a single mandatory argument, which was expected to be a
file path. If the file ended with .act, we would compile it whereas if
it was a .ty file we would dump its content. E.g. valid use cases:
actonc foo.act
actonc foo.ty
We now take a single mandatory argument, which is expected to be a
command. As a shortcut, we do still support being passed a .act file and
will then compile it, which means we are also somewhat backwards
compatible. For example:
actonc foo.act
Dumping the content of a file is however not supported by just sending
in a file path as the only argument. There is a new command, aptly named
"dump" which in turn accepts an option --file for the filename of the
.ty file to …
=> Change actonc argument

Makefile
I've noticed occasionaly failing due to two concurrent compiles stepping
on each other. It is fascinating how often it works just fine.
Dunno why I didn't do this properly before... but now it's guaranteed
not to build the stdlib in parallel.
=> Ensure serial build of stdlib

Makefile, compiler/ActonCompiler.hs, stdlib/Makefile
We agreed on the structure in a project but somehow ended up not
implementing it completely. I guess it comes from all modules being
manually compiled from C, so what actonc did wasn't as relevant.
Anyway, now actonc does the right thing!
For example, here's the layout of stdlib:
```
stdlib/out
├── dev
│   ├── bin
│   └── lib
│       ├── acton$rts.o
│       ├── libActonProject.a
│       ├── math.o
│       ├── numpy.o
│       ├── random.o
│       ├── _time.o
│       └── time.o
├── rel
│   ├── bin
│   └── lib
│       ├── acton$rts.o
│       ├── libActonProject.a
│       ├── math.o
│       ├── numpy.o
│       ├── random.o
│       ├── _time.o
│       └── time.o
└── types
├── acton
│   ├── rts.h
│   └── rts.ty
├── __builtin__.ty
├── math.h
├── math.ty
├── numpy.h
├── numpy.ty
├── random.h
├── …
```
=> Implement new project naming in actonc

compiler/ActonCompiler.hs
This gives nice concise output per default, for example:
Compiling foo.act for release
Compiling math.act for release in stub mode
Compiling numpy.act for release in stub mode
Compiling random.act for release in stub mode
Compiling _time.act for release in stub mode
Compiling time.act for release
Compiling acton/rts.act for release in stub mode
=> Change actonc default output

compiler/ActonCompiler.hs
Previously we wouldn't print out "in stub mode" when compiling in
developer profile. We do now, for example for stdlib:
Compiling foo.act for release
Compiling math.act for release in stub mode
Compiling numpy.act for release in stub mode
Compiling random.act for release in stub mode
Compiling _time.act for release in stub mode
Compiling time.act for release
Compiling acton/rts.act for release in stub mode
Compiling foo.act for development
Compiling math.act for development in stub mode
Compiling numpy.act for development in stub mode
Compiling random.act for development in stub mode
Compiling _time.act for development in stub mode
Compiling time.act for development
Compiling acton/rts.act for development in stub mode
=> Fix build output to include stub mode

compiler/Acton/Env.hs, compiler/ActonCompiler.hs
The environment (env) record has a stub field which controls
We used to initialize this value in initEnv and keep that value
throughout the current actonc invokation, affecting all compiled files,
which meant it was only the initial file that would really affect
whether stub compilation was used or not. Now we instead change the stub
mode in the local environment used for the compilation in runRestPasses,
effectively setting stub mode per file. It means it's now irrelevant for
initEnv, so the arg is removed from there.
Also improved output a bit.
Fixes #621.
=> Correctly implement stub mode

debian/control
I think this was just a brainfart on my part. I was thinking that we
need the -dev libraries when we are building Acton itself but for later
use of actonc itself we would be fine with like libprotobuf-c1, but
we're not! libprotobuf-c1 is a shared library and since actonc is a
compiler and we want the executables that actonc produces to have as few
run time dependencies, we do not use shared libs but rather prefer to
link it at compile time. Thus, we need the -dev version of the packages,
that include the non-shared libs, at run time of actonc.
Also added in uuid-dev since it seems to have been missing.
I've verified things work correctly by running it in a Debian container.
=> Correct Debian dependencies

compiler/ActonCompiler.hs, compiler/package.yaml.in, test/Makefile, test/actonc/project/auto_root/src/b.act, test/actonc/project/qualified_root/src/b.act, test/actonc/project/qualified_root/src/test.act, test/actonc/root/test.act
--root takes the name of the actor that shold be used as the root actor.
It used to be unqualified, like "main" and actonc would look in the
source file specified. Now that we support building multiple files in a
acton project, an unqualified name is ambiguous. Thus, by switching to
qualified name we get around this!
We still do attempt to build a qualified name if an unqualified name is
given and do this by the "old rules" so it behaves the same way as it
used to for single file compilation, for example:
actonc examples/count.act --root main
Here 'main' will be qualified to 'count.main' and is thus equivalent to
giving the full name directly:
actonc examples/count.act --root count.main
Using unqualified names for a project build is not deterministic and
should be avoided.
There are some …
=> --root now takes a qualified name

CHANGELOG.md, compiler/ActonCompiler.hs
Rather than take a option, actonc dump now takes a positional argument.
Before:
actonc dump --file foo.ty
Now:
actonc dump foo.ty
=> Let dump command take positional argument

.github/workflows/test.yml
fail-fast means if one job in a matrix fails, the other jobs in the
matrix will be canceled. Since we are seeing some intermittent build
failures on MacOS, we don't want this. It is better to let the tests
complete on all versions.
=> Do not fail-fast matrix builds

compiler/ActonCompiler.hs
--cgen or --hgen is just supposed to print the generated content to
stdout so that the output could be piped to a file. As we continued to
compile the module after printing the output, we would also output
errors or other output not related. We now exit immediately after
printing the output!
=> Exit after printing [ch]gen output

Makefile
All the Makefile targets related to the backend now have proper
prerequisite declarations so make should behave better. We should now
never need to use clean-backend or similar but any change should be
identified and rebuilt accordingly.
=> Properly declare prerequisites for backend targets

builtin/env.c, builtin/env.h, builtin/ty/src/__builtin__.act, examples/client.act, examples/server.act, test/rts/ddb_test_client.act, test/rts/ddb_test_server.act
This is for you to review; there is one problem that should be checked before we merge:
The file examples/client.act does not compile:
acton> actonc examples/client.act --root client
Compiling client.act for release
actonc: No match in record selector rtail
acton> 
I believe that this has very little to do with this change (but it compiled before), but this is for Johan to judge.
The only changes are that in Connection, method .write takes a bytes parameter instead of a str. The same for the first callback parameter in  on_receive.
Applications like server/client in examples and ddb_test_server_client/server  in test/rts need to do some calls to encode(() and decode().
I  believe that the test suite passes, but there is a lot of output which I don't understand completely...
=> changed TCP content to be bytes instead of strings

compiler/package.yaml.in
This brings down the test time from a staggering 0.7s to 0.2s on my
machine ;)   but it's a good thing to make them run in parallel since it
might make a much bigger difference down the line.
=> Run Tasty tests in parallel

compiler/test.hs, compiler/test/.gitignore, compiler/test/actonc/project/.gitignore, compiler/test/actonc/regressions/import_actor/src/foo.act, compiler/test/actonc/regressions/import_actor/src/import.act
Importing a module and then instantiating an actor from that module does
not work. This adds a test case to prove it and marks it as currently
failing.
=> Add (failing) test for creating imported actor

compiler/test.hs, compiler/test/actonc/regressions/abstract_actor_from_type_signature/README.org, compiler/test/actonc/regressions/abstract_actor_from_type_signature/src/abstract_actor_from_type_signature.act
Whenever an actor has a type signature defined it appears actonc thinks
it should be abstract and so fails on trying to instantiate the actor.
This seems wrong.
=> Add regression for abstract actors

compiler/test.hs
Not always easy to tell from which app the error message comes since we
run the tests concurrently. Now we include the app name (the thing) in
the message so should be simple.
=> Improve error message in test to include thing

compiler/Acton/CPS.hs, compiler/Acton/CodeGen.hs, compiler/Acton/Deactorizer.hs, compiler/Acton/LambdaLifter.hs, compiler/Acton/Names.hs, compiler/Acton/Normalizer.hs, compiler/Acton/Syntax.hs, compiler/Acton/Types.hs, compiler/ActonCompiler.hs, test/regression_auto/not_implemented.act, test/regression_auto/not_implemented.ext.c
Such functions can have any type, but since no type inference is done for NotImplemented bodies, annotations are typically required
to obtained the desired function type.
A NotImplemented function will pass through the compiler and obtain the appropriate transformations, although its generated C code
will just consist of a function header.
For an Acton source file NAME.act, actual C implementations of any NotImplemented functions are instead supposed to reside in a
sibling source file NAME.ext.c, which is automatically included in the generated code whenever NotImplemented functions are detected.
Let us ponder whether we want to control this behavior with some compiler flag or whether it should be automatic (as of now).
=> Added support for functions with NotImplemented bodies.

.gitignore, test/core_lang_auto/imported-class__bf/README.org, test/core_lang_auto/imported-class__bf/src/foo.act, test/core_lang_auto/imported-class__bf/src/ic.act
It is not possible to instantiate a class from an imported module.
Currently fails with:
kll@Boxy:~/acton/test/core_lang/imported-class__bf$ ../../../dist/bin/actonc build
Compiling foo.act for release
Compiling ic.act for release
actonc: Acton/CodeGen.hs:187:1-70: Non-exhaustive patterns in function conName
kll@Boxy:~/acton/test/core_lang/imported-class__bf$
=> Add test for failing imported class

.github/workflows/test.yml
Now that we run the test suite on multiple Linux distros we produce an
artifact for each which confused the release jobs. Pick a single one,
the one built on debian:11, for the release artifact. The rest are still
available but not as release assets.
Fixes #707
=> Select single linux tar ball for release

.github/workflows/test.yml, Makefile, builtin/env.c, builtin/env.h, compiler/ActonCompiler.hs, debian/control, rts/io.c, rts/io.h, rts/rts.c, rts/rts.h, stdlib/Makefile, stdlib/c_src/numpy/ndarray.c
This adds a new IO thread based on libuv. It doesn't really do anything besides existing but lays the foundation for using libuv in the RTS, env and modules. While we have yet to properly use it, I think this is correct, like linking is done as it should etc.
libuv header files are in dist/include. Previously we've had header files that are required at actonc run time in dist/builtin and dist/rts but I think it would be good to collect them in a single place so rather than create a uv specific directory, I added dist/include and endgame might be to move rts.h and builtin/*.h in there!?
libuv_.a is placed in dist/lib. We do not compile it differently for rel/dev profile (as of yet). It is linked in at actonc run time. I think this is the only way, for example; we could try to link io.o …
=> Add new libuv based IO thread to RTS

.github/workflows/test.yml, Makefile, builtin/env.c, builtin/env.h, debian/control, rts/io.c, rts/io.h
Add new test job running on debian:11. Pull down .deb file produced in
earlier job, install and run actonc on a simple program to ensure
dependencies are correctly specified.
We have dependencies at compile time of actonc itself and then a
different set of dependencies at run time of actonc (when a user is
compiling a program).  We want to minimize the number of dependencies we
have at run time. In order to ensure we get this right, we have to
install on a fresh machine that does not have the actonc compile time
dependencies installed. Further, for the dependencies we do have, we
try to include them in the Acton system distribution itself.
=> Ensure dependencies are included & specified

.github/workflows/test.yml
This tests that the acton system we've produced on our main build
platform (debian:11) is able to run on other distributions.
=> Test running actonc on Ubuntu

Makefile, compiler/Acton/CodeGen.hs, compiler/ActonCompiler.hs, compiler/test.hs, stdlib/Makefile, test/compiler/rebuild/README.org, test/compiler/rebuild/src/rebuild.act
There's a problem with the new root actor discovery mechanism. When a
project is rebuilt, actonc crashes with:
kll@ThinkYoga:~/acton/test/compiler/rebuild$ ../../../dist/bin/actonc build
Compiling rebuild.act for release
Building executable /home/kll/acton/test/compiler/rebuild/out/rel/bin/rebuild
actonc: Maybe.fromJust: Nothing
CallStack (from HasCallStack):
error, called at libraries/base/Data/Maybe.hs:148:21 in base:Data.Maybe
fromJust, called at ActonCompiler.hs:570:43 in main:Main
Which I'm guessing has to do with that we do not read in all modules
from .ty files unless we need to. When building from scratch, all
modules are read in, since we are compiling them all, but when some are
already built, we skip them unless they are dependencies of other
modules.
Test case for #728
=> Add failing test case for rebuilding a project

stdlib/src/net.act, stdlib/src/net.ext.c, test/stdlib_auto/test_net.act
This adds a new module called 'net'. The intention is to collect all of
the network related things currently existing in the env actor and place
them in the net module instead and perhaps to expand it further.
The only functions currently added are for doing DNS lookups of A and
AAAA records. The interface is not really what we want in the end but
quite similar to what we currently have.
The module is built using the new external C function style, which means
that functions in the .act file whose body consists of a NotImplemented
statement are not generated by the compiler but rather expected to be
manually or EXTernally implemented in the file net.ext.c, if such a file
exists.
libuv is used for these new functions also marking our first use of libuv.
lookup_a and lookup_aaaa (the public …
=> Add net module with basic DNS lookup functions

rts/io.c, rts/io.h, rts/rts.c, stdlib/src/net.act, stdlib/src/net.ext.c, test/stdlib_auto/test_net.act
I think this is a better fit. Also brings the added benefit of being able to call impure functions (which wasn't the case before due to wrong type signatures).
The test program is now correct (thanks to being able to use impure callbacks) and runs much faster. It used to take 1 second due to a after 1 but now runs in millieseconds.
We now await the ioloop to start up before proceeding with starting worker threads. This has eliminated a race which lead to deadlocks.
Fixes #750.
Fixes #749.
=> Restructure DNS lookup functions as DNS actor

rts/io.c, stdlib/src/process.act, stdlib/src/process.ext.c, test/stdlib_auto/test_process.act
The process module can be used to run child or sub-processes. A process
is modeled as an actor.
A new auth type called ProcessAuth has been introduced, which grants the
ability to start new processes.
It is not yet possible to write to stdin of a running process.
Fixes #156.
=> Add process module

test/stdlib_auto/test_process.act
Seeing lots of seemingly spurious timeouts on MacOS runners, so
temporarily disabling test...
=> Disable process module test

.github/workflows/test.yml
As of (end of) July 2022 (like now), it is no longer supported and thus
fails. Dropping it from the list of releases we are testing on...
=> Drop CI tests on Ubuntu 21.10

stdlib/src/net.act, test/stdlib_auto/test_net.act
We didn't initially take a WorldAuth argument since we didn't have an
instance but that's been fixed for quite some time now, thus NetAuth now
requires a WorldAuth token for initialization!
=> Fix NetAuth auth

.github/workflows/test.yml
Just like with the run-linux job, we spin up a new macos machine with no
dependencies installed and then compile a program using actonc. It
should work since we should have no run time dependencies!
=> Test run actonc on macos

.github/workflows/test.yml
GitHub Actions has deprecated support for macos 10.15 and it is going
away, so we'll stop testing on it!
https://github.com/actions/virtual-environments/issues/5583
Fixes #779
=> Stop testing on macos 10.15

compiler/Acton/CodeGen.hs, stdlib/src/net.ext.c, stdlib/src/process.ext.c, stdlib/src/time.ext.c, test/regression_auto/not_implemented.ext.c
This makes it possible to run code at module initialization time when
using the new .ext.c style!
Fixes #777
=> Add __ext_init__

stdlib/src/net.ext.c
I somehow got the impression that libuv functions returned -1 on errors
but that was apparently wrong. Got me a -24 here (too many open files).
With this improved error reporting, that is now clear! :)
Note to devs, never use uv_strerror! Only use uv_strerror_r!
=> Improve net.DNS error handling

stdlib/src/process.act, stdlib/src/process.ext.c
I didn't have my brain turned on when I did this. Figured that since
acton integers are signed I couldn't store a pointer since it couldn't
represent above 2^63... but that's obviously wrong. Brainfart. We can
safely store 64 bits, signed or unsigned is just in the eye of the
beholder.
=> Store process pointer as Acton int, not string

stdlib/src/process.act, stdlib/src/process.ext.c, test/stdlib_auto/test_process.act, test/stdlib_auto/test_process_env.act, test/stdlib_auto/test_process_pid.act, test/stdlib_auto/test_process_wdir.act, test/stdlib_auto/test_process_write.act
Rather than raising an exception when we encounter an error in spawning
the process, we call the on_error callback. It receives one argument
which is the error message.
Part of #795.
=> Add on_error callback for errors

rts/rts.c, rts/rts.h, stdlib/src/file.ext.c, stdlib/src/net.ext.c, stdlib/src/process.ext.c
This makes it easier to call, since we can do it from any function and
not just an actor. All functions are called by an actor anyway, it's
just that we dig it out of the pthread store rather than having to
thread through the argument (which is only possible in C anyway, making
it impossible to call such a function directly in Acton).
=> Remove arg from pin_actor_affinity

compiler/ActonCompiler.hs
Been hit by this a couple of times now and the consequences are dire.
The RTS will behave very weirdly when it doesn't get a R_CONT or
similar, so better detect at compile time.
=> Always treat return type warnings as errors

builtin/str.c, builtin/str.h, examples/client.act, rts/rts.c, stdlib/src/net.act, stdlib/src/net.ext.c, test/rts/ddb_test_client.act, test/stdlib_auto/test_net_tcp.act
The net.TCPIPConnection actor is a TPC client which connects to remote
systems. It takes an IP address as argument. The idea is to wrap this up
in a net.TCPConnection which does name resolution including happy
eyeballs.
It handles resume for distributed DB systems, which is also verified by
a test. A few tests have been updated to use this rather than the old
TCP client connection actor.
=> Add TCP client actor net.TCPIPConnection

.github/workflows/test.yml
There could be multiple artifacts when there have been failures during
the job that produced it. The artifacts are uploaded immediately after
the build completes so it can upload and then fail in the subsequent
testing, the job is rerun and thus we get multiple artifacts.
This makes the pre-release-tip handle that scenario by picking the
latest available artifact.
Fixes #825.
=> Ensure we grab latest artifact

stdlib/src/json.act, stdlib/src/json.ext.c, test/stdlib_auto/test_json.act
This adds a JSON module with encoding and decoding abilities. There's a
json.Json actor that does the actual work. I was originally going for
just having a free decode and encode function in the module but that
doesn't work (compiler bug) so had to make it look like an actor, which
does bring the benefit of allowing async work. There are free
encode/decode functions, so that you can encode or decode JSON with a
single line of code. They just wrap up the Json actor so every
invocation also means creating an instance of the Json actor. It should
really be the other way around, but we'll have to sort out the compiler
bug first.
Fixes #184.
=> Add JSON module

stdlib/src/process.ext.c
We have to stop reading after the provided lenght. That it has somewhat worked before is just a coincidence.
Fixes #836
=> Fix process module reading stdout

compiler/ActonCompiler.hs, compiler/package.yaml.in
actonc now outputs some information about what it is doing per default, like our default verbosity has increased. A new --quiet flag is introduced to make it quiet again. New default looks like this for stdlib:
```
Building project in /home/kll/terastream/acton/stdlib
Compiling time.act for release
Finished compilation in   0.045 s
Compiling test.act for release
Finished compilation in   0.047 s
Compiling random.act for release in stub mode
Finished compilation in   0.048 s
Compiling process.act for release
Finished compilation in   0.116 s
Compiling net.act for release
Finished compilation in   0.176 s
Compiling math.act for release in stub mode
Finished compilation in   0.088 s
Compiling numpy.act for release in stub mode
Finished compilation in   0.753 s
Compiling json.act for release …
```
=> Revamp actonc output & include timing

compiler/ActonCompiler.hs
Also correct timingtart -> timeStart. This was the result of a regexp replace where the --timing argument was previously called --times, so s/times/timing/ modified timeStart into timingtart, heh.
=> Don't print when --quiet

compiler/Acton/Deactorizer.hs, compiler/Acton/Prim.hs, compiler/Acton/Types.hs, rts/rts.c, rts/rts.h, test/regression_auto/11-int-float__bf.act
The after statement has thus far taken an integer argument for the number of seconds after which to run a method. It is now changed to a float so we can do sub-second delays.
Fixes #9.
=> after now takes float seconds as argument

CHANGELOG.md, test/test_db.py
We have a lot of intermittent failures in the DB tests, most of which stem from segfaults. Manually rerunning failed CI jobs is boring and time consuming. Also, retrying means rerunning the entire job which takes 5 minutes while retrying a single DB test is on the order of seconds, so this is much better.
In general we've stayed clear from retrying tests as to avoid hiding intermittent failures but it's clear here that we'd be more productive if we just solve the test-retry issue in a pragmatic way. We still have tickets and won't forget to get rid of the errors in the DB stuff.
Fixes #853.
=> Retry DB tests up to 5 times

test/Makefile, test/test_db.py
While we did retry the test function we have basic state in our environment that is automatically set up in the setUp function and later torn down in tearDown(). The retry wrapper wouldn't rerun those methods.
Instead, the test is refactored slightly and we explicitly call dbc_restart() from the test function to ensure the DB cluster is up and running in a fresh state.
Fixes #853
=> Make DB test retry actually work

.github/workflows/test.yml, Makefile
Forgot to actually include runacton into our distribution. That's fixed now and in order to properly test that, we now use it in both the run-linux and run-macos tests!
On mac we need to modify the PATH since we don't actually install acton on the system but just extract it in a directory in our home dir. It would be preferable if we actually did a brew install or somesuch so that acton would be installed in the system...
Fixes #861.
=> Include and use runacton in tests

.github/workflows/test.yml
We had a mix of macos & darwin. It's now more uniform.
'darwin' comes from the architecture, i.e. uname reports itself as darwin so that is what our package names are called but still, it's easier to understand what it is if we refer to it as macos in most places I think...
Fixes #864.
=> Uniformly use 'macos' in CI test job names

.github/workflows/test.yml
dpkg -i doesn't install dependencies so we have to accept a failure and run apt-get -f install to resolve and install those dependencies for us.
apt install does it all in one operation and is available since around the time of Ubuntu 16.04, i.e. available "everywhere".
Fixes #865.
=> Use apt install rather than dpkg -i

Makefile
We now compare the git version tag, if set, to the current version from our authoritative source in common.mk to ensure that they are equal!
Fixes #281
=> Ensure consistent git version tag

.github/workflows/release.yml
Releasing thus far has consisted of:
- updating the VERSION variable common.mk
- updating CHANGELOG.md
- pushing a tag
It's slightly annoying because the first two means changing files, opening PR and merging and then git pulling main, add a tag and push the tag. It's a lot back and forth.
We now automate the last bit of pushing a tag by having a new CI job doing it for us.
New process is thus:
- updating the VERSION variable common.mk
- updating CHANGELOG.md
- open PR with name starting with release-
- when PR is merged, tag based on VERSION in common.mk will automatically be pushed to main branch
=> Add auto-release CI job

.github/workflows/release.yml, CHANGELOG.md
The push used the defaults credentials provided when checking out the repository, which equates to github.token. For some reason, perhaps to avoid cyclic errors, the CI runner is not supposed to trigger itself and so using github.token for auth will not trigger any workflows. By switching to our own SSH deploy key for checking and pushing the repo we can trigger workflows!
Fixes #877
=> Use deploy key for pushing tag

Makefile
Sometimes, like when this repo is downloaded as a tar ball, we are not in a git repo and so we get an error from running git. We suppress that since it's pointless and doesn't have a negative effect.
=> Suppress git error

compiler/ActonCompiler.hs
Homebrew on x86 places headers in /usr/local/include whereas on M1 it is placed in /opt/homebrew/include. gcc / clang includes /usr/local/include per default but for M1 we must explicitly add the include path.
We now also explicitly list the standard include paths so we can work with compilers, like zig, that do not seem to have any default include paths?
=> Add homebrew on include path

CHANGELOG.md, compiler/ActonCompiler.hs
The checkUptoDate function has only considered imported modules that are in the local project. If we import a module from the standard library, it has errored out as it cannot find the .ty file.
We now look both in the local project and stdlib to find the .ty file.
Fixes #890.
=> Also find .ty files in stdlib

builtin/tuple.h, compiler/Acton/CodeGen.hs
The bug is caused by a dark corner in C macro expansion.  The macro $NEWTUPLE in tuple.h uses the tuple pasting operator ## in order to avoid a spurious "," in the call of __init__ for an empty tuple. This is a gcc extension which does not work for nested macro calls.
Fixed by introducing a special macro $NEWTUPLE0 for empty tuples and removing the ## operator in $NEWTUPLE.
Probably one should think through other macros in common.h which also use ## and would fail on nested calls.
=> fixes issue 869

test/test_db.py
On my AMD 5950X machine I'm rather consistently seeing this test fail. We stop the first invocation and by altering the timing of when we stop it, starting the program a second time might lead to a crash. 0.1 seconds fairly consistently leads to crashes on my machine. By bumping our 0.1 second sleep to 0.2 avoids the crash. Lowering it to 0.01 also avoids the crash. Thus, there is some time window during which we are doing something important, that if interrupted will lead to crashes the next time we try to resume the program from DB.
It's likely my machine is faster than CI, so in order to have a better chance of steering clear of the "bad time window" we're now sleeping for 0.5 seconds.
We should naturally get to the bottom of this but meanwhile it's pretty annoying not being able to …
=> Avoid crash during TCP client resume test

backend/actondb.c
I think it's a short-coming in the gossip protocol so we only gossip one of the ports, the normal port that clients connect to, so to find the gossip port we just take that port + 1. Thus, users are not really free to set the gossip port however they want. Maybe it shouldn't even be configurable given this constraint... however, changing the default port is at least a simple way of leading users to the right thing.
=> Change actondb default gossip port

CHANGELOG.md, Makefile, backend/actondb.c
The gossip protocol only includes the RPC port and does not explicitly
say what port is used for gossip, so other parts of our system assumes
it is the RPC port +1. Thus, we change the actondb default to also be
based on RPC port +1.
The long term solution is to make the gossip port configurable and to
propagate that information in the gossip protocol. Meanwhile, since we
do not support any other port than +1, we make it impossible to
configure but leave most of the argument parsing code in so that it's
easy to change one day.
=> Compute gossip port as offset from RPC port

CHANGELOG.md, rts/rts.c
libuv takes a uint64 for the timeout. When we computed a negative offset and fed it in, it gets treated like a very large number, something like 18446744073709550271, or roughly 584 million years.
Now fixed by treating negative timeouts as 0 so we immediately wake up to handle the event.
Part of #907.
=> Fix handling of missed timed events

CHANGELOG.md, rts/rts.c
When the worker threads are created they are first in a no-exist / poof state and once they're initialized in the main_loop function they should be marked as Idle. They were not, which lead to problems as the wake_wt function specifically looks for worker threads in the idle state to wake up. Since it was in poof state, it would not be woken up. Now fixed!
Fixes #907.
=> Properly initialize WT state

stdlib/src/net.act, stdlib/src/net.ext.c
After we resume a TCP actor, its fd is invalid. While we do already call the registered error callback to notify the user application and let them deal with it (reconnecting), there are probably cases where a method is already scheduled to run and it will attempt to use the invalid fd. By setting it to an invalid fd, -1, we should see errors reported (provided that all our calls to uv_write and similar are correctly error handled) instead of segfaults.
Part of #908.
=> Invalidate fds on resume

CHANGELOG.md, backend/actondb.c, backend/client_api.c, backend/comm.c
The DB client interaction functions have unconditionally tried to communicate with all remote servers in our list. If a server is dead, it's socket is invalid and trying to communicate with it doesn't make any sense. We now only communicate with servers that we think are live.
This has been a long running issue and a rather annoying one where we've seen lots of garbage written to the screen when RTS fails to connect to a DB server. It happened because the sockfd gets rewritten to 0, which is stdin, and then the message meant for a DB server is written to our terminal. It's a binary protocol so it looks like a bunch of garble garble.
Now also using -1 for sockfd so we get an error if we try to write to it and tightened up so we only set NODE_LIVE after connection is successful.
Same …
=> Only communicate with live nodes

stdlib/src/net.ext.c
After resuming an IO actor, specifically a TCP actor in this case, the fd we had is invalid. We recently changed so that the __resume__ method would set fd = -1 but apparently that's not enough to avoid libuv from segfaulting. I figured it would just not run uv_write, perhaps returning with an error, when fed an invalid fd but nope, it segfaults. So now we return early from these functions if we got an invalid fd.
Fixes #908.
=> Avoid invalid uv_write after resume

backend/client_api.c
We might actually end up with invalid fds, like -1, since we don't mutex protect everything.. and that should be fine, so changing the assert accordingly.
Initially, 0 was used as an error signal. That was wrong since 0 is actually a valid fd and when we meant to signal "invalid fd" we just ended up writing data to stdin which in turned led to garbage output on terminals... anyhow, we changed the "invalid fd" to use -1, so this assert is really just to check that we haven't forgotten anywhere.
Part of #923.
=> Only check for fd == 0

CHANGELOG.md, rts/rts.c
There were a bunch of log lines in RTS that still had the ending new line. Simply forgot to remove these when moving from printf to our log lib.
Fixes #926.
=> Remove newlines from RTS log lines

backend/actondb.c, backend/client_api.c, backend/comm.c, backend/failure_detector/db_queries.c, test/rts_db/test_db_app.act, test/rts_db/test_tcp_client.act, test/rts_db/test_tcp_server.act
This removes ending new lines from a bunch of the DB log messages.
Some log messages have been changed for improved wording. For parsing various messages the errors have been broken into NULL / type check (to help me debug an issue).
Also fix test script output.
=> Remove new lines from DB log messages

test/rts_db/test_tcp_server.act
We can't really rely on newlines == a message chunk, although it has pretty much been equal on my local machine. Anyway, this should make it more robust and also print more debug info in case we miss our mark.
=> Robustify tcp server test

backend/client_api.c, backend/client_api.h, backend/test/test_client.c
Functions that did non-range search of DB rows in the client API did not return a status. This PR fixes that.
=> Return status from exact row search functions as well

Makefile
macos appears to kill actonc if we recompile it and copy it in place but if we copy it to a temp file and move that in place, it is fine?
Fixes #969
=> Do cp & mv dance to avoid macos weirdness

test/rts_db/ddb_test_server.act, test/rts_db/test_tcp_server.act
I've added some more debug printouts, in particular we now display the error from the TCPIPListener, which should normally be "resume" when the system resumes but could perhaps be something else.
Timeouts have been increased, although I'm not sure if this has a real effect or not.
In my testing, these changes to the test scripts drops the error rate for this test on Ubuntu 20.04 from 13% to ~1.5% which is in line with other platforms.
=> Improve test_tcp_server test

compiler/Acton/CommandLineParser.hs, compiler/ActonCompiler.hs, compiler/test.hs
=> Cmdlineparser

Makefile, compiler/ActonCompiler.hs, test/rts_db/test_db_app.act
We depend on multiple external libraries and in order to produce a known and consistent result, we include those libraries in the Acton distribution.
When actonc compiles, since we produce C code, we need to link that with the libraries of our external dependencies which means the acton compiler needs to have an exhaustive list of all libraries. This includes libraries required by builtins and by stdlib. It is not desirable to have to maintain such a list in multiple places (both Makefile where we copy files and in compiler for correct linking).
We now combine all .a libraries into one big .a archive which we can then link with and so it's up to cc/ld to figure things out. Thus we've remove the definition of all these libraries from actonc!
Fixes #849.
=> Combine all external libs in one .a archive

.github/workflows/test.yml, Makefile, compiler/ActonCompiler.hs, debian/control, homebrew/Formula/acton.rb, stdlib/Makefile
Our strategy thus far has been to rely on the package manager of system on which we are being built. On Linux (Debian) we've used apt to install packages and then copy the .a archives from those packages into the Acton distribution, which means we get a library built with some set of options which we are unable to influence. On Mac we do the similar thing but using Homebrew.
Not all libraries are available in apt or brew, so there is a point where we have to start compile things from source. We now do and beyond being able to bring in libraries that are not available in apt/brew, we also gain better control over what compilation flags are used, so for example, we include libxml2 but without z, lzma or python support, making it a much smaller library with no other dependencies.
Our build …
=> Build all library deps from source

Makefile, compiler/Acton/CommandLineParser.hs, compiler/ActonCompiler.hs, compiler/test.hs
--always-build skips the up-to-date check in actonc and always builds, which is necessary for correct tests since we otherwise risk relying on outdated results. The up-to-date check only inspects source and output files on disk. For example, if a .ty file is newer than its source .act file. If actonc itself has changed and updated the format of the .ty file, we won't catch this. --always-build is thus the only safe option for testing.
Fixes #967.
=> Add & use actonc --always-build

Makefile, compiler/ActonCompiler.hs
This adds in the bsdnt library which we plan to use for bigint support. I'm opening a separate PR in order to land these changes immediately thereby reducing the risk of git conflicts in the build system files since there's a bunch of work relating to that which is currently ongoing (most notably using zig).
Part of #146
=> Add bsdnt for bigint support

Makefile
We have a make clean target to clean out stuff if dependency updates have gone wrong or similar. This certainly has happened in places like the builtins or stdlib but I don't think I've ever seen it happen to the compiler... it always recompiles correctly! And since it's rather slow rebuilding the compiler, I think what most people what when they do "make clean && make" is to just rebuild the other stuff and thus I'm removing the compiler from the default clean action. If you really want to clean away the compiler, do make clean clean-compiler
=> Do not clean compiler

.github/workflows/test.yml, Makefile
Now the -target argument is applied universally. While we previously applied it to dependencies and ran it from actonc, thus covering stdlib, we didn't use it for CFLAGS throughout the Makefile, so actondb for example was not compiled with -target, thus it would get dynamically linked towards the glibc on the machine instead of the fixed version we have set. That prevented actondb from being run on older machines.
Also, using -target changes the include paths and this revelead that we didn't have a working inclusion of protobuf headers. protobuf is a dependency where we still rely on a system provided library rather than compiling it ourselves. This is somewhat risky since we want to guarantee compatibility with some given glibc version but it's tricky compiling protobuf-c and since …
=> Use -target for all & include protobuf headers

stdlib/Makefile, stdlib/src/acton/rts.ext.c, stdlib/src/random.ext.c, stdlib/src/random.h
Rather than have the whole module implement in C with a .c file, we now
use the newer ext.c style to implement certain functions (which in this
case happens to be 100% of the module contents but that's besides the
point).
ext.c do not require manual Makefile targets, so those have been removed.
Also removed unused _time make targets.
Fixes #758.
=> Use new ext style for random & acton.rts modules

Makefile
I had problems with this before but after adding --disable-protoc (we don't need the compiler), it all works just fine. Yay! Now all external libraries are built from source!
Fixes #1030.
=> Build libprotobuf-c from source

test/perf-benchgames/pidigits/1.act
Follow directory structure in programmings-language benchmark repo under bench/algorithm so we can easily copy programs between the two.
=> Move pidigits benchgame

Makefile, compiler/Acton/CommandLineParser.hs, compiler/ActonCompiler.hs
This enables the automatic detection of stub mode compilation. Previously it was the default to always do stub mode detection, but this is problematic if there happens to be .c files with the same name as our .act file in the same directory but it's entirely unrelated, i.e. not an Acton C module implementation.
This is the case with the Programming Languages Benchmark where all test files are in the same directory and named by a sequence number, like 1.act is the first Acton solution to a particular problem and 1.c is the C solution to the same problem.
It is saner and safer to not do automatic stub compilation per default. For some places, like our stdlib, we now have to provide --auto-stub, which feels just fine!
Fixes #1047.
=> Add --auto-stub to actonc

compiler/Acton/CodeGen.hs
=> Fixed bad codegen of classename arg to isinstance().

test/perf-benchgames/spectral-norm/1.act
Ported from an older Python version, which was easier to understand.
Part of #180
=> Add bench game: spectral-norm

.github/workflows/test.yml, Makefile, homebrew/Formula/acton.rb
This avoids a dependency on an external libargp on MacOS, so we now get to control how it is compiled.
For Linux, this should have preference over the system provided argp.
Fixes #1037.
=> Include argp in libActonDeps

builtin/hash.c
Bit shifts outside of var width are UB on signed ints according to C spec. Using unsigned is correct!
Fixes #989.
=> Avoid UB bit shift; fix by signed -> unsigned

Makefile
We already place libuuid in libActonDeps and thus already link with it through that.
Fixes #1067.
=> Drop unnecessary -luuid

Makefile
We needed these to pull in stuff via Homebrew but as we now ship all of our own libs in libActonDeps we don't need it anymore.
Fixes #1064.
=> Drop old lib / include paths

Makefile
We include the libs in here in our big libActonDeps.a anyway...
=> Drop -Ldeps/instdir/lib from LDFLAGS

debian/control, docs/development_workflow.md
These external library dependencies are part of libActonDeps now, so no need to install. Nor do we need gcc at run time of actonc since we bundle zig.
Fixes #1079.
=> Remove deps for Linux in CI & in debs

backend/client_api.c, backend/failure_detector/vector_clock.c, backend/failure_detector/vector_clock.h
Make sure that clients (RTSs) do not hop between different DB server partitions if these exist, even if they learn about disjoint gossip views.
This handles a problem that can happen if incomplete partitions happen. For instance, the distributed DB servers might be partitioned from each other, but the clients (RTSs) might still be able to talk to servers in both partitions. Consequently, clients might receive a stream of diverging gossip views from each of the partitions. If this happens, this PR enforces that the clients stick to one of the partitions only to prevent data inconsistency.
This is implemented by comparing the vector clocks of the currently installed view, and the new view to be installed, and skipping view installs at the client as long as these vector clocks are …
=> Make RTS clients sticky to partitions

backend/client_api.c
On Linux, select modifies the timeout value to reflect the amount of time not slept. Since we want to continue sleeping for 3 seconds on every iteration we need to reset the value on every loop iteration.
Fixes #1085.
=> Reset comm thread timeout

backend/client_api.c
If we get an error we take another spin in the loop rather than try to continue processing.
I've seen the comm thread hanging on a read on the wakeup_pipe, which shouldn't be possible. I wonder if it might be that we have continued processing after getting EINTR and that is just invalid. Think this fixes it.
=> Correct error handling in comm thread

.github/workflows/test.yml, Makefile
We dropped Ubuntu 20.04 when it was clear that libxml2 required a newer version of automake than available on Ubuntu 20.04 and it was just too much to handle at the time. As it turns out, that requirement is probably not a very hard requirement at all, likely the artifact of running autoupdate on a relatively new machine and voila, the required version is bumped to something quite new.
It seems to work just fine compiling and running after we rewrite the required version to what is available on Ubuntu 20.04.
=> Test on Ubuntu 20.04

Makefile, backend/client_api.c, compiler/ActonCompiler.hs, rts/rts.c
This adds garbage collection to the Acton run time system through the
use of libgc. We use link time redirection of malloc and friends in
order to catch all occurrences. Thread creation is hooked by including
gc.h in RTS and the DB client (which are the two places where we create
threads).
An earlier attempt was made to change our source code from using malloc
& friend to GC_MALLOC & friends but as it is exceedingly difficult to
find all mallocs, it regularly produced programs that segfaulted. libuv
and yyjson allows using a custom malloc but other libraries, like
utf8proc, doesn't appear to have functionality for specifying which
malloc to use and so it becomes rather difficult. Thus, this approach
was abandoned in preference of link time redirection of `malloc`.
Thread creation is …
=> Add garbage collection using libgc

compiler/test.hs, test/stdlib/test_time.act
Fixed so that test.hs and test_time.act agree on time unit.
=> fixed test_time bug

README.md
The note on lack of GC is outdated since we now have a GC!
While the web page install instructions are nice, I have regretted removing the install instructions from the readme since I just think it's nice that the instructions, in their very briefest form, are available right in the repo. Makes it easier to grasp how simple the install process is.
=> Add install instructions & remove GC comment

docs/acton-by-example/src/primitives/lists.md
Expand documentation of lists, now including how to reverse a list in place and taking a copy of it.
Related to #1132
=> AbE: expand list doc

test/builtins_auto/list.act
Test various methods of lists. A bunch of things are commented out as it doesn't work in Acton, although perhaps it should given that we more or less copy Python lists? If we decide this is not to be implemented, then let's just remove it.
Related to #1132
=> Add tests of list

.github/workflows/test.yml, Makefile
We add the option to statically compile actonc by setting STATIC_ACTONC=true for the build. We set this variable for our build-debs jobs so the produced .deb file should now run on older platforms too!
Fixes #1146
=> Statically compile actonc

Makefile
We already set this argument in CFLAGS for all platforms higher up.
=> Remove redundant CFLAGS path on linux

Makefile, stdlib/src/acton/rts.act, stdlib/src/acton/rts.ext.c, test/stdlib_auto/test_acton_rts_sleep.act
Calling usleep isn't signal safe and since our GC is using signals
rather extensively to pause threads, we ended up with a fairly broken
rts.sleep. By switching to nanosleep we not only tolerate signals but
can also resume sleeping to the correct amount as nanosleep will return
the remaining time that it didn't sleep.
Also added in a acton.rts.gc() function that will explicitly invoke the
GC since this was fairly useful to trigger bugs during testing. There's
an "Interruptor" actor in the test of acton.rts.sleep which was helpful
during development but as it seems we have some unknown deadlock!? I am
not leaving it enabled, though just commented out so we can investigate
further.
Fixes #1171
=> Handle signal interrupts in rts.sleep

rts/rts.c
We start indexing by 1 rather consistently, partly to allow for 0 being used by the main thread in some places (like uv_loops). WTS mon assumed indexing started at 0 :/ I think this is what we had before, so just forgotten to update when changing at some point.
Fixes #1063.
=> Fix WT indexing in mon WTS

examples/server.act, stdlib/src/net.act, stdlib/src/net.ext.c, test/rts_db/ddb_test_server.act, test/stdlib_auto/test_net_tcp.act
The on_receive and on_error handler for individual client connections (TCPListenConnection) are now registered after instantiation of each TCPListenConnection actor by calling cb_install(). This is most appropriately done in the on_accept callback. Unlike the old pattern, where we provided these callbacks up front to the TCPIPListener actor, having them registered per client connection naturally opens up to having different handlers per client.
There are two ways of handling connections;
- one actor that handles many TCP clients
- means we need to keep track of individual TCP client actors so we respond to the right one etc
- one actor per TCP client
- each actor implementing business logic only speaks to a single TCP client, so the actor code can be quite simple
- scale out by serving a …
=> Revamp & fix bugs in TCPListener

compiler/Acton/Parser.hs
This changes a very confusing error message reported by Kristian in issue 732 to a slightly less bad one...
=> slightly improved some parser error messages

Makefile, rts/io.h, rts/rts.c, stdlib/src/time.act, stdlib/src/time.ext.c, test/regression_auto/125-async-actor-method-call.act, test/stdlib/test_time.act, test/stdlib_auto/test_acton_rts_sleep.act, test/stdlib_auto/test_time.act
=> Add DateTime, Timer, Duration & Instant

Makefile
Also move zig extraction to separate directory to avoid:
- extracting zig again after make clean
- avoid recompiling all deps, since they depend on $(ZIG) they would be rebuilt after make clean since we would re-extract dist/zig, not so anymore since we now use zig directly from deps/zig/zig
This does however double the disk usage for zig and since it's ~350MB we are up to ~700 just for carrying two copies of zig. Disk is sort of cheap though, so probably not an issue.
=> Add clean-all target & improve zig extraction

.github/workflows/trigger-web-update.yml
When there are changes to the acton-by-example book, which is published on our web page, we automatically trigger a rebuild of the web page so the new content becomes visible.
=> Trigger rebuild of web page

.github/workflows/test.yml
Now using the newer style as recommended in
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Fixes #1073
=> Fix use of deprecated set-output

.github/workflows/test.yml, .github/workflows/trigger-web-update.yml
Just like we do for the tar balls, the .deb package is now also available at a stable URL.
=> Use deterministic name for deb package

Makefile, builtin/int.c, builtin/str.c, rts/io.c
Using GC_MALLOC_ATOMIC instead of GC_MALLOC (the normal malloc is redirected to GC_MALLOC in our repo) means we mark an allocation as atomic. Atomic allocations means the GC will not scan it internally for any pointers, which in turn speeds up the GC mark phase!
Fixes #1221.
=> Use atomic mallocs

Makefile, deps/zig-extras/lib/libc/include/any-macos-any/sys/timex.h
Rather than relying on timex.h existing at some particular path, we now bundle timex.h ourselves and copy it in at build time. It seems that on Macos 13, or perhaps due to some other circumstances, timex.h might be in a different location. It's just easier to bundle it ourselves than try to find it across a number of different paths.
The final solution would be to have it included in upstream zig instead. We have initiated this work.
Fixes #1224
=> Bundle timex.h and copy in on build

builtin/slice.h, builtin/tests/dict_test2.c
typedef for B_slice is already in __builtin__.h like it is for all other types, so just defining the struct here.
Remove superfluous space
=> Align B_slice def

compiler/Acton/CommandLineParser.hs
This adds bash completion of .act files as input to actonc. Sooo frustrating not being able to tab complete my way to files, but it works now, yay :)
Fixes #1244
=> Bash complete .act files

compiler/ActonCompiler.hs
-Og is the recommended flag for debugging, which is what we want for dev mode. We did -O3 before but not consistently, so now we do -O3 for all compile during release build.
=> Do -O3 for release builds & -Og for dev

.github/workflows/deps-builds.yml, Makefile, compiler/ActonCompiler.hs
Just like we did for libActonDeps, libactongc now includes the platform name in the archive name, like libactongc-x86_64-linux.a, so we can easily differentiate multiple versions of it, which in turn makes it simpler to do caching and perhaps eventually cross-compilation.
=> Include platform in libactongc lib name

.github/workflows/deps-builds.yml
To avoid littering the actonlang/acton repo with deps-* releases, we move them to a separate repository!
=> Publish release on actonlang/libactondeps

.github/workflows/deps-builds.yml, Makefile, compiler/ActonCompiler.hs, stdlib/Makefile
This revamps building deps so we now produce a single tar.bz2 ball containing relevant libraries and headers. Makes it easier to handle rather than multiple independent files.
There is now some support, though relatively untested, for also downloading an existing tar ball, extracting it and using those files. It is possible to override by setting ALWAYS_BUILD=true, which means we will not download and force local build. This should also be idempotent, so we do not attempt to download the deps archive multiple times, thus even without internet connectivity, we won't attempt to run curl (which would fail).
=> Revamp deps build & use deps dl as cache

.gitignore, Makefile, builder/build.zig, compiler/Acton/CommandLineParser.hs, compiler/ActonCompiler.hs, compiler/project-build.zig
This switches to using zig build for building Acton projects. There are a number of advantages and unlocked potential advantages:
- zig has a very advanced caching system
- invoking zig cc as a C compiler, like before, does not use this caching system
- invoking zig build, like with this change, we make use of the cache!
- zig has awesome cross-compilation support and we can better utilize it when we call zigs high-level build command rather than the lower level cc compatibility commands
- by directly adding in RTS, builtins etc, we can even skip building libActon libary archives in rel / dev flavors and let it be built per project with the exact compilation flags we want, or for cross-compilation! This could open up for more compilation options that affects builtins, RTS etc.
- build.zig …
=> Build projects using `zig build`

.github/workflows/test.yml
We might not be running in CI for the main actonlang/acton repo, so we must set the git repo url to clone!
Fixes #1291
=> Set git repo url for homebrew formula testing

compiler/ActonCompiler.hs
Since we are having problems with the zig build, change default to our classic approach of directly calling (zig) cc.
=> Default to classic cc compile

docs/acton-by-example/src/actors.md
The comment in the first actors example mentions that a dummy return was needed to avoid a segfault with "await async". This doesn't seem to be true anymore.
=> rm segfault workaround in example

.github/workflows/test.yml, Makefile, compiler/ActonCompiler.hs
One pin down the rabbit hole! Switched from using the `zig build` frontend, which under the hood just builds the builder program based on our build.zig. It's really build_runner.zig, which in turn imports build.zig. We now do that step manually and are then able to inject our own compilation arguments, like which arch to compile for and should thus get a portable executable that is built for the base CPU feature set without all the bells and whistles of the native CPU of the build machine!
Default to use the zig build!
Fixes #1305.
=> Build a portable builder!

Makefile
Seen a lot of spurious build faults where we seemingly lack gc.h. It happens on MacOS machines mostly and always lacking gc.h
Fixes #1297
=> Fix race in Makefile around header installation

Makefile
Per default zig compiles a super optimized binary using all the CPU features avilable on the build machine. This isn't very portable. On x86_64 we tell zig to compile for the base CPU spec by doing -mcpu=x86_64 which disables all extra features. I figured it was the same for all architectures but apparently not on aarch64, so now we will only specify -mcpu=$(ARCH) on x86_64.
Portable binaries are mostly important when we do releases. We don't have any aarch64 builds, thus this is only used for locally built Acton systems and will thus probably work just fine. Will be interesting to see if an M2 will produce a binary compatible with an M1 though!
Fixes #1310
=> Only force base CPU feature set on x86_64

.github/workflows/test.yml
The macos 13 machines seem faster, so switching over!
=> Run brew-macos on macos13

.github/workflows/test.yml
The brew-macos job is failing more times than not. I don't have the time or energy to fix it now, so option to remove as all failures are becoming a nuisance.
I originally added the brew-macos job as we had failures once we pushed a new release to the homebrew-acton repo. With rather few releases and far between, the brew build problems only dawned on us once we made a release. Having the Formula committed locally and testing it continuously was an attempt in increasing the likelihood of finding problems earlier so we could fix them. It did work well and did catch a bunch of problems but something is different now, presumable in brew itself, so that our local test no longer works. It was quite hacked up and not a "supported mode of operation" in / by brew.
In the longer term I think we …
=> Remove failing brew-macos job

Makefile
git clone is slower and takes more space since we clone full history. We don't need flexibility of git, so using curl to grab a snapshot is simpler.
=> Fetch deps using curl rather than git clone

.github/workflows/test.yml
There appears to be build problems with Ubuntu 20.04. We can't download the latest stack for Haskell. Removing the job for now.
=> Remove testing on Ubuntu 20.04

Makefile, builder/build.zig, compiler/ActonCompiler.hs
In order to simplify compilation and decouple the compiler from the list of C libraries, we bunched them all up in one large archive called libActonDeps.a. Recently it was moved to include the platform name, like libActonDeps-x86_64-linux.a.
With the move towards using zig build and how the entire build process, both what's called from actonc as well as how we put together the Acton distribution itself, the need for having libActonDeps is smaller. We accept the list of libraries in multiple places. Since our dist building step now naturally installs the .o files in dist/depsout, we make use of them directly, so also building libActonDeps is just unnecessary. It has now been removed.
The classic C compilation (not using zig) has also been fixed to use the correct paths.
dist/builtin is …
=> Ditch libActonDeps, minimize dist

docs/acton-by-example/src/modules.md
sleep() as a concept, i.e. actively waiting, is not something that exists in Acton. This particular module is a hack to allow RTS debugging. We shouldn't promote or even talk about it since it might lead users into thinking it should be used.
=> Avoid using acton.rts.sleep() in example

base/builtin/int.c
This PR makes a change to __pow__ for type int to avoid an error introduced by C compiler optimization.
=> small change to __pow__ for int to avoid C compiler optimization error

.github/workflows/test.yml, Makefile
xz is faster and better than bzip2. Here we tell it to use lowest level of compression (-0) and thus the fastest mode. --threads=0 enables using multiple threads to compress data.
Despite being the faster level and thus worst compression, it beats bzip2 standard settings. The current release tar ball turns in bz2 & xz:
- bz2: 66061362
- xz:  65009672
On an AMD 5950X (16 cores / 32 threads) with an NVMe drive, it takes ~16 seconds to produce the bz2 while producing the xz takes just over 1 second. It might just be the increased parallelism or a combination with xz being faster overall.
There are plenty of CI runs where it takes just as long to build Acton, like coming in just over 2 minutes (with a zig build cache), as it does to produce the release tar ball (just under 2 minutes). …
=> Use xz instead of bzip2 compression

.github/workflows/test.yml, Makefile, base/src/time.ext.c, compiler/Acton/CommandLineParser.hs, compiler/ActonCompiler.hs, compiler/test.hs, docs/acton-by-example/src/compilation.md, test/compiler/hello/.gitignore, test/compiler/hello/src/hello.act
Musl libc doesn't expose ntp_adjtime, only adjtimex. However, adjtimex is apparently just an older name for ntp_adjtime() and ntp_adjtime() is the pereferred one and available on many systems. Somewhat unclear on why musl picks the older name, but regardless, by picking adjtimex() for Linux systemes, we are compatible with both GNU libc and musl, while for others, like Macos we keep the call to ntp_adjtime().
Switch libgc to a newer version of its build.zit that will set options correctly for musl, which comes down to setting NO_GETCONTEXT.
=> musl compatibility

.github/workflows/test.yml
We had some issues with concurrent builds specifically on MacOS that we could never really pinpoint. They appeared out of thin air one day, perhaps they've also gone away by themselves...?
Fixes #1147
=> Enable concurrent builds in CI for MacOS

backend/build.zig, base/build.zig, base/rts/rts.c, base/rts/rts.h, base/src/__builtin__.act, base/src/__builtin__.ext.c, base/src/acton/rts.act, base/src/acton/rts.ext.c, base/src/net.act, base/src/net.ext.c, builder/build.zig, test/stdlib_auto/acton_rts_io.act, test/stdlib_auto/test_net_tcp.act
This makes it possible to explicitly shut down a TCP client connection, which should clean up everything in the libuv loop.
If actors are garbage collected, there is likely remaining socket cruft left in the libuv loop which we do not currently have any means of cleaning up. At least this gives us the ability to explicitly shut things down cleanly from within the application.
=> Add .close() for TCP client actor

compiler/ActonCompiler.hs
Shouldn't compare with .h and .c file since we copied them in, so there's no point in comparing the same files.
=> Fix checkUptoDate for stub mode

base/builtin/env.c, base/src/__builtin__.act, base/src/acton/rts.act, base/src/file.act, base/src/net.act, base/src/process.act, examples/client.act, examples/files.act, examples/server.act, test/perf/ring.act, test/rts_db/ddb_test_client.act, test/rts_db/ddb_test_server.act, test/rts_db/test_db_app.act, test/rts_db/test_tcp_client.act, test/rts_db/test_tcp_server.act, test/stdlib_auto/test_file.act, test/stdlib_auto/test_net_dns.act, test/stdlib_auto/test_net_tcp.act, test/stdlib_auto/test_process.act, test/stdlib_auto/test_process_env.act, test/stdlib_auto/test_process_pid.act, test/stdlib_auto/test_process_wdir.act, test/stdlib_auto/test_process_write.act
All actors that take a capability ref argument, now has the argument renamed from 'auth' to 'cap' to better align with the capability intuition.
WorldCap is now available as env.worldcap, which should be used rather than env.auth. env.auth will be removed in a future version.
Fixes #1178
=> Rename auth arg to cap & env.auth -> env.worldcap

CHANGELOG.md, compiler/ActonCompiler.hs
Remove files from the out/ directory that do not have a corresponding source file in the src/ directory. This can happen if we have compiled a project and then rename a source file. The old generate .c and .h files would remain and the low level builder would find them and attempt to compile them. This way we clean out such files without having to resort to something akin of 'make clean'.
Fixes #1411.
=> Remove outdated out files

compiler/Acton/Env.hs, compiler/Acton/Types.hs
when validating hierarchical module names. Now using a proper check against the import list instead.
=> Stopped relying on the module cache 

CHANGELOG.md, base/builtin/exceptions.c
An exceptions error message is now optional and we only attempt to print it if it is set. The exception error class name is now printed as well.
Fixes #1422 
Fixes #1423
=> Print exception class name + allow no err message

base/builtin/env.c, base/builtin/env.h, base/rts/rts.c, base/src/__builtin__.act, base/src/acton/rts.act, base/src/acton/rts.ext.c, test/regression_auto/125-async-actor-method-call.act, test/stdlib_auto/test_acton_rts_sleep.act
This splits up so that functions related to the Acton RTS system internals now take a special SysCap capability. This is not part of the WorldCap chain of capabilities and so it must be more explicitly passed around.
Fixes #1388
=> Add SysCap

CHANGELOG.md, Makefile, backend/build.zig, base/build.zig, builder/build.zig, deps/libuuid/build.zig
More changes to the build.zig syntax which we've now updated. All dependencies are updated as necessary, thus the bumped REFs.
Fixes #1421
=> Upgrade to zig v0.11.0

CHANGELOG.md, base/src/net.act, base/src/net.ext.c, compiler/ActonCompiler.hs, docs/acton-by-example/src/security/capabilities.md, examples/client.act, test/Makefile, test/rts_db/ddb_test_client.act, test/rts_db/test_tcp_client.act, test/rts_db/test_tcp_server.act, test/stdlib_auto/test_net.act, test/stdlib_auto/test_net_tcp.act
This adds a new TCP client connection actor which replaces the older TCPIPConnection actor. It improves on the old implementation through the addition of DNS resolution and Happy Eyeballs (RFC6555).
While not super complex it is non-trivial compared to the old connection actor and so there are probably bugs lurking. More test cases are needed.
Right now we do a rather aggressive Happy Eyeballs where we instantly connect both to IPv4 and IPv6. This effectively doubles the resources consumed, fds on our end and more on the server side. While the RFC allows for this, the recommendation is to have a slight delay for the IPv4 side, like I think Chrome does 300ms or so. We can look into that.
Added net.is_ipv4() and net.is_ipv6() as well.
=> Add net.TCPConnection & remove TCPIPConnection

compiler/Acton/Names.hs, compiler/Acton/Types.hs
to allow forward references from functions to classes and actors.
=> Modified the splitting of declaration groups

base/src/net.act
The connect timeout implementation was just incomplete and broken. What a brainfart from my end. It was late and I rushed it in last minute, completely botching things. Now fixed!
Also nicer state management.
=> Fix TCPConnection connect timeout

base/src/acton/rts.ext.c, base/src/file.ext.c, base/src/net.act, base/src/net.ext.c, base/src/process.ext.c, compiler/Acton/Deactorizer.hs
Private actor methods are hidden and wouldn't get nice C wrapper functions generated. This is now changed so that we can easily call actor methods from outside of CPS context.
Through this change in actonc, we can use this and directly call the relevant methods in TCPConnection. This let's us get rid of some ugly hacky variables.
Fixes #1432.
=> Generate wrappers for hidden funcs

base/src/net.ext.c, base/src/process.ext.c
This is the best we can currently do. It's effectively silencing a warning, which is rather dangerous since the right hand value is typically something generated from a .act file, so it will change if there are changes and we won't get any C compiler warnings.
Part of #805.
=> Cast actions

compiler/Acton/Deactorizer.hs
They were always missing, commit 223a8dd1 just exposed the error. Fixes #1447.
=> Added missing deactorizer typeargs.

compiler/test.hs
The cross-compilation tests can take a really long time, in particular when run in GitHub Actions on the MacOS runners, which are likely quite strained. 5 minutes should be enough!
=> Bump test timeout to 5 minutes for cross-compile

base/rts/rts.c, base/rts/rts.h, base/src/acton/rts.act, base/src/acton/rts.ext.c
This returns the RTS stats from within Acton! A first step to replacing the RTS mon functionality written in C in the RTS with similar functionality that we can instaed build in Acton! It's monitoring Acton from within Acton!
Part of #1430.
=> Add acton.rts.rts_stats()

base/builtin/i64.h, test/builtins_auto/int.act
val is not a pointer. I suspect this was erroneously copied from our int implementation where val is a pointer to a bsdnt struct. Now fixed!
Fixes #1459
=> Fix i64 eq/ne/etc comparisons

CHANGELOG.md, base/builtin/list.c, test/builtins_auto/list.act
It's that damn memcpy again! I have now also skimmed the other uses of memcpy in this module and I think they are OK but added asserts to check at least the source argument.
Fixes #1461
=> Fix list add for empty list input

Makefile, base/src/net.act, base/src/net.ext.c, builder/build.zig, test/stdlib/test_net_tls.act
This adds a TLS client connection actor. It's interface is rather similar to the TCPConnection actor.
Under the hood, we are using tlsuv and mbedtls for the TLS functionality and integration with libuv. It is quite integrated so for example, at this point it has name resolution integrated. That's a part I'd like to lift out so we can do it in Acton (and one day avoid relying on getaddrinfo entirely) but it's there for now out of simplicity. There's more important issues to fix on this TLSConnection first, like disabling certification verification (useful for testing).
Longer term I'd also like to see the ability to bundle CA certs in the application itself so that we don't rely on anything external, think of a WASM app or on a freestanding target.
There's a simple test application that …
=> Add net.TLSConnection()

Makefile, base/src/net.act, base/src/net.ext.c, test/stdlib/test_net_tls.act
This is obviously not a good security practice but for the sake of testing or similar it is very useful to be able to disable the verification of TLS certificates.
Most of the changes went into the tlsuv library where I had to add new options for this. I'm not all too pleased with that solution but it works.
I have verified that this works by connecting to google.com but through an IP address so we get a mismatch between the address and certificate name. It normally fails but once we disable verification the connection is established.
Fixes #1471
=> Allow disabling TLS certificate verification

base/src/logging.act, base/src/logging.ext.c, test/stdlib_auto/test_logging.act
This adds our first attempt at a logging module for logging in an actor centric world. I'm no logging expert, not like I've spent half my life thinking of this and most of the experience I have is with imperative language, perhaps Python above all. Python has lots of magic going on with an implicit logger hierarchy behind the scenes that automatically figure out modules etc. We don't have mutable state and I just don't think it's a good fit. One of the benefit of Pythons implicit hierarchy is the control per submodule or module tree. I tried to recreate the same using Handlers in this module. It's not implied though but the developer has to explicitly define a hierarchy of Handlers if that's what we want. It's a bit of an experiement, let's see how we can use this.
We avoid loops between …
=> Add basic logging module

base/rts/rts.c
Rather than hiding them away in the RTS debug output, we print them to stderr per default.
Also added a very simple version of name unmangling to get at least the most basic of examples working with better readability.
With this PR this code:
```python
actor main(env):
raise ValueError("foo")
env.exit(0)
```
Looks like:
```
Unhandled exception in actor: -12[foo.main]:
ValueError: foo
```
The indentation of the exception itself is intentional. I was thinking we would make it easier to parse these tracebacks, which are log multi-line log messages, by indenting the subsequent lines.
Fixes #1475
=> Print unhandled exceptions

base/builtin/builtin_functions.c, base/builtin/builtin_functions.h
=> Fixed naming and method table for the primitive EqOpt witness class.

base/src/http.act, test/stdlib_auto/test_http.act
This improves the HTTP library. First is a refactoring of the parsing functions for parsing HTTP requests and HTTP responses. They now have a common base in parse_message() which parses a HTTP message. Requests and responses look the same except for the start line, so parse_message() does the parsing and hands over the start_line so that parse_request() and parse_response can parse just the start line.
There's now a test module which tests the parsing of requests and thus of the main parse_message() function.
Now with the new parsing organization and tests in place, I've added support for chunked transfer-encoding.
All the get, post, etc methods on the HTTP client now take a headers argument so it is possible to send in headers.
Fixes #1505
=> Add chunked transfer-encoding & headers

CHANGELOG.md, docs/acton-by-example/src/primitives/tuples.md, docs/run-example.py, test/core_lang_auto/return-tuple-with-bool.act
Move run-example.py so it can be reused for multiple books, not just AbE.
Fix tuple example to directly check bool type as a bool. We fixed this bug but I couldn't get the example to work, which turned out to be because I was using the system installed actonc rather than the one locally built in the repo, and so I ended up with an older one that didn't have the fix.
I changed the path to actonc in run-example so we get the locally built one which is probably what we want!?
Now also have a test on this type of bool check on a field in a returned tuple.
Fixes #1500. Really fixed by #1504, but this adds tests etc too :)
=> AbE: fix bool field in tuple

base/rts/rts.c, base/src/__builtin__.act, base/src/__builtin__.ext.c
The base exception now has a __str__() method that formats the exception. This is very useful for more advanced exception types where we want to be able to include more dynamic data but not carry the cost of doing up front string formatting. Now we can always provide extra data but only string formt it when necessary for printing. More complex exception types need to implement their own __str__().
_name() returns the name of the exception type.
Now we can standardize on calling this __str__() function when printing exceptions too!
=> Add __str__() method to Exceptions

base/src/net.ext.c
We are waiting for an error both on IPv4 and IPv6 but since we incorrectly reported IPv6 errors as IPv4, we never got both and thus never propagated errors to the calling code via the on_error callback.
This only deals properly with dual stack connections. For IPv4-only or IPv6-only cases we need more code paths...
=> Fix error handling in TCPConnection

base/builtin/float.c
We opt to diverge from Python and join the bunch of languages that follow the IEEE float convention of returning infinity for divide by zero instead of throwing an exception.
Fixes #1521.
=> Remove exception for float /0

base/src/testing.act
proc() allows creating actors and as such allow for non-determinism. mut() should be deterministic and that's what we like to call unit tests!
=> Unit tests should be: mut() -> None

base/src/json.act, base/src/json.ext.c, test/stdlib_auto/test_json.act
The JSON encode and decode functions were implemented as methods on an Actor due to an actonc bug where NotImplemented simply wasn't recognized for free functions. This design was never the intended one but a side effect of this actonc limitation. The json.encode() function instantiated the Json actor and called Json.encode() so the functionality of calling the encode function was possible just that it involved creating an actor and so required quite a bit of extra overhead than necessary.
Another consequence was that the encode() function got the effect proc, since it creates an actor, and of course any calling could would be CPS split. The unit testing functionality offered by the testing module requires mut() effect so we can't use it to test JSON encoding or test any function that in …
=> Change JSON encode/decode to free functions

.github/workflows/test.yml, Makefile, compiler/package.yaml.in, compiler/stack.yaml, compiler/stack.yaml.lock, debian/control, homebrew/Formula/acton.rb
It's been awhile since we upgraded and it would be nice to move to a fresher version of ghc, so here we go.
Now doing CI .deb builds using Debian 12 / bookworm. Since our newer Stack LTS requires a newer version of Stack, we have to upgrade stack on Debian 11 and Ubuntu 20.04 and 22.04. It's a little nasty but I think it's ok to say that people who want to develop Acton itself needs to use a relatively recent platform.
The LTS & GHC upgrade gives a good speed increase. Compiling a certain relatively large project now runs ~25% faster or so.
I managed to put together so we can now do static compilation on Linux even when building on other distributions than Debian 11.
Fixes #1512.
=> Upgrade to Stack LTS 21.13 & GHC 9.4, build on Debian 12 and always do static compilation for Linux

compiler/stack.yaml
Not that I've seen any direct issues on this branch, there were build issues on Ubuntu with LTS 20.26 that might be due to inconsistency compilation flags. It's probably best to keep consistent compilation options for all dependencies.
=> Do -fPIC for all deps

Makefile
This reverts commit 1f7fcf3db5bf17ce988803edd29cfff585c12927.
The per thread malloc seems to cause hangs, so we need to disable it for now and bring it back in in an order fashion.
I've been running the rts_db/test_tcp_client application repeatedly and it keeps hanging in about 25% of cases with per thread malloc whereas it always works without it.
=> Revert "Use per-thread malloc"

test/rts_db/ddb_test_client.act, test/rts_db/test_tcp_client.act
I suspect a bug related to DNS lookups that hits us on MacOS. We already have stdlib_auto/test_net_dns.act that does DNS lookups and that seems to work just fine, but continuously running test/rts_db/test_tcp_client results in a lot of SIGILL and SIGSEGV on MacOS. We are doing DNS lookups both in the program under test, ddb_test_client, but also in the test_tcp_client app test orchestrator itself, which seem to account for most of the failures and since it's the app test runner, its crashing have weird effects and cannot be easily handled. I don't know why but it somehow seems to be hanging, so running it in a bash for loop, I still need to ctrl+c it and in CI we hit the timeout in GitHub Actions (6 hours) rather than it just failing.
I've looked quickly at the backtrace and it seems we …
=> Avoid DNS lookup in testing

base/src/net.act
One of the main features of the new TCPConnection is that it does rather nice dual stack support. However error handling even presumed dual stack and did not work correctly for single stack use, such as when an IP address is given as input. That's now fixed.
The full state machine needs to be modeled and reviewed. This is still a bit haphazardly put together and I'm sure there are more bugs lurking.
We've been seeing quite a lot of problems in CI with test timeouts. Not sure why there would be timeouts or any errors in CI, but if they're actually connection refused but without the error propagating, this could explain it. The rate is suspiciously high though. Let's see.
=> Fix net.TCPConnection single stack error handling

compiler/Acton/LambdaLifter.hs
=> Removed premature conversion of input given to the closure converter.

Makefile
This reverts commit 4e9dfc7e52220b20bef79f147bf8c65a51692eba.
Third time around ;)
It doesn't seem like it's the per-thread malloc that's causing problems, it only revealed problems elsewhere, in this case around DNS. After avoiding DNS lookups, the problems disappears and since per thread malloc is a good thing - better perf - we now re-enable it!
=> Revert "Revert "Use per-thread malloc""

.github/workflows/test.yml
To keep a consistent style, add in -tip where we would normally have the version number. For example:
https://github.com/actonlang/acton/releases/download/v0.17.0/acton-linux-x86_64-0.17.0.tar.xz
https://github.com/actonlang/acton/releases/download/tip/acton-linux-x86_64-tip.tar.xz
Whereas we used to have
https://github.com/actonlang/acton/releases/download/tip/acton-linux-x86_64.tar.xz
=> Use -tip as version number

base/src/net.act
If we get a DNS resolution error, we now check if we are still in the resolving state. If not, like if we have already connected or are in some other state where this is not relevant any longer, we don't do anything. If we are still in the resolving state, we retry the DNS lookup after 0.1 seconds.
Previously we would just retry immediately, which would lead to loads of busy work. For example, if there is no AAAA record at all, we would just continue retrying the AAAA lookup for all future, so even when the IPv4 connection has established and TCP is working properly, the TCP actor would just retry the AAAA lookup. This could consume 50% - 75% of a CPU core!
=> Improve DNS error handling

Makefile, backend/build.zig, builder/dependencies.zig, deps/libnetstring/build.zig, deps/libuuid/build.zig, deps/libyyjson/build.zig
Updating to use zig v0.12, which is the current development version. There are further improvements to the build system. Since there are now finally documentation available on the Zig Build system, that's probably an indicator it is stabilizing. It did require a few small changes from v0.11.
=> Use zig v0.12.something

test/builtins_auto/int.act
Now the test will exit immediately rather than hang indefinitely (but eventually timeout by test framework) with an unhandled exception.
=> Refactor int test

base/rts/rts.c
Previously unhandled exceptions would bubble up and be printed both in the actor where the exception was raised as well as in another actor that called the method raising the exception. Given this program:
actor Foo():
def foo():
print("FOO")
raise ValueError("FOO")
actor main(env):
f = Foo()
a = f.foo()
We would see:
FOO
Unhandled exception in actor: foo.Foo[-14]]:
ValueError: FOO
Unhandled exception in actor: foo.main[-12]]:
ValueError: FOO
Since the Foo.foo() method is actually "returning" the exception back to the main actor (the return value is assigned in the main actor), it should not be considered "unhandled" in the Foo actor where it is raised.
We now check if there are other actors waiting for us, in which case we consider the exception handled since we propagate it back. Thus, …
=> Only print truly unhandled exceptions

base/src/__builtin__.act, base/src/__builtin__.ext.c
Johan Nordlander hates type() - it should not be used for metaprogramming... but I find it damn helpful as a debug tool. I print types and work with that :) Maybe a "print_type" could fix this, which directly prints to stdout instead of returning a str, that way it's impossible to use for metaprogramming but anyhow, let's go for this. We'll try to remove it in the future when we have other better means of debugging types, like a language server or similar.
=> Add type()

base/builtin/str.c
As far as I can tell these should do the same thing while memcmp is more portable.
=> Prefer portable memcmp over bcmp

compiler/Acton/Env.hs, compiler/Acton/Solver.hs, compiler/Acton/Subst.hs, compiler/Acton/Syntax.hs, compiler/Acton/TypeM.hs, compiler/Acton/Types.hs, compiler/Utils.hs, test/typeerrors/ex1.golden, test/typeerrors/ex11.golden, test/typeerrors/ex12.golden, test/typeerrors/ex14.golden, test/typeerrors/ex15.golden, test/typeerrors/ex17.golden, test/typeerrors/ex18.golden, test/typeerrors/ex19.golden, test/typeerrors/ex2.golden, test/typeerrors/ex20.golden, test/typeerrors/ex21.act, test/typeerrors/ex21.golden, test/typeerrors/ex22.act, test/typeerrors/ex22.golden, test/typeerrors/ex23.act, test/typeerrors/ex23.golden, test/typeerrors/ex4.golden, test/typeerrors/ex5.golden, test/typeerrors/ex8.golden, test/typeerrors/ex9.golden
Small further improvements to type error messages, in particular some changes to avoid assigning blame. Example, test/typeerrors/ex1.act:
```
def f(x,y):
return x+y
a = f(3)
```
Error message is now
```
ERROR: Error when compiling ex1 module: Type error
|
4 |a = f(3)
|    ^^^^
|
1 |def f(x,y):
|    ^
Type incompatibility between definition of and call of f (too few arguments in call)
f is inferred to have a type of the form [A(Plus)] => _(A, A) -> A
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
```
This avoids the previous blaming of the call for being wrong, just noting that the call and the function definirion are incompatible.
Note: I made one restructurintg change, by moving class Simp and its instances from Types.hs to Env.hs (so I could use it in …
=> Improve typeerrormsgs 4

.github/workflows/test.yml, CHANGELOG.md
Seems Homebrew has dropped support for MacOS 11 and with it pre-built binary versions of stuff, so in order to avoid building everything from source, we drop MacOS 11 from CI.
=> Stop testing on MacOS 11

.github/workflows/test.yml
Rather than overwrite the acton package in the repo with a new one, we now keep all versions. Since this is a new feature in reprepro, we've also moved to using a fresher container etc.
Now also using the Acton package name in the git commit message.
=> Store multiple versions in apt repo

base/builtin/range.c, base/src/__builtin__.act
The real default is still applied in C code, but at least the type signature now indicates that the step argument has a default value.
=> Set range default step=1

.github/workflows/test.yml
Telemetrify is the largest project implemented using Acton, by quite a fair margin. We want to be aware if / when we introduce backwards incompatible changes in Acton that breaks Telemetrify.
I'm not actually sure what the workflow should be when we do introduce backwards incompatible changes. Perhaps we should have a "acton-next" branch on the telemetrify git repo that should normally be rebased & up to speed with its main branch but that also allows us to modify things to align with changes in Acton itself!?
=> Test external project Telemetrify

compiler/stack.yaml
Homebrew is based on GHC 9.4.8 currently so this should help align there and get a working version!
=> Upgrade to Stack 21.25 / GHC 9.4.8

CHANGELOG.md, base/builtin/builtin_functions.c, base/src/__builtin__.act, base/src/testing.act
Also remove printn() since it is superceded by print(foo, end="").
Fixes #112.
=> Add sep, end, stderr & flush args to print()

base/builtin/dict.c, base/src/__builtin__.act
Now that exceptions are always string formatted by __str__ we can actually include the key in the KeyError exception. It's only included as an object attribute so it doesn't cost much. The actual string formatting is only performed if the exception is actually printed.
Fixes #1564.
=> Include actual key in KeyError.__str__()

.github/workflows/test.yml
aptip is the APT repo for tip releases. There's a new GH Action job to push the .deb file built during tip releases to that repo.
Part of #1569
=> Push .deb to aptip repo

.github/workflows/test.yml
GitHub caps it at 1GB. Weird, because surely it must be easier & cheaper to produce than regular git access. Anyway, ditching LFS since we want to stay in the free...
Part of #1569
=> Remove git LFS

Makefile, backend/build.zig, base/build.zig, builder/build.zig, deps/libnetstring/build.zig, deps/libuuid/build.zig, deps/libyyjson/build.zig
There's been some major updates to the build system in zig and this brings us up to date.
What's pretty cool is that we've done a proper job of reimplementing the CMake build of BDWGC using build.zig (earlier it was just a quick hack supporting a minimal subset of features) and it's now upstreamed, so the git ref we're now using is from the upstream repo and not our own fork, although we continue to mirror the repo for the time being.
Our installation size will grow now since we're also enabling C++ and Windows, which we've previously stripped out from our zig install. This is mostly a preparatory move.
Fixes #1646
=> Use zig 0.12.-dev.2236

compiler/ActonCompiler.hs
Haskell detects if stdout is a terminal, in which case it does line buffering, or something else in which case it is block buffered. This means when we call it from the `acton` frontend we end up with block buffered output which locks really bad. We want direct output which gives that interactive feeling!
=> actonc: line buffered stdout

base/builtin/dict.c, base/src/__builtin__.act, test/builtins_auto/dict.act
This does the change described in #1659. It also fixes a bug in setdefault.
I also tried to add copy and clear as methods to  dict, but code generation  for calls in client code fails. The type signatures in __builtin__.c have a Hashable witness as 2nd parameter (and so did my implementation), but code generated for calls got only one argument (the dict). Leaving it for now.
=> fixes #1659

compiler/Acton/CommandLineParser.hs, compiler/ActonCompiler.hs
This pull request adds two things:
- actonc  can take one file argument with suffix .ty; if the file exists, its contents is prettyprinted on stdout.
- one more Boolean CompileOption --ty is added; this causes copying of the .ty file from the temporary  project dir to the source file directory before the temporary dir is erased.
=> More support for ty files

compiler/Utils.hs
This pull request removes all SrcLoc info in .ty files. When these are read all SrcLoc entries become NoLoc.
After pulling, do 'make clean'. 
All existing .ty files become invalid and the corresponding source files must be recompiled. The symptom is an error report from Data.Binary.Get.runGet.
Fixes #1592
=> removed SrcLoc info from .ty files

base/rts/rts.c
uint isn't a defined type on some platforms, 'unsigned int' would be correct but in many of these places we might as well just use a normal signed int.
=> Use int rather than uint

base/build.zig, base/rts/rts.c, base/rts/rts.h, builder/build.zig, compiler/Acton/CommandLineParser.hs, compiler/ActonCompiler.hs, test/Makefile
It's now possible to build Acton programs without the DB backend support. In fact, it is the new default, since the DB backend is still a rather esoteric feature and not very mature, so anyone that wants it can easily add in the --db flag.
=> Make DB backend optional

base/builtin/env.c, base/rts/q.c, base/rts/rts.c, base/rts/rts.h
This adds so the main thread runs the worker, i.e. it picks up and executes actor continuations. We've previously used readyQ 0 as the shared queue, but since the main thread is the closest thing we have to a thread 0, it now owns readyQ 0. The shared readyQ is instead at the top-most position.
For now, only the Env actor runs on the main worker thread. This is necessary since things like installing signal handlers, which we want to do in the Env actor, must be performed in the main thread. There are probably other good uses of placing particular actors on this thread.
=> Let main thread perform special actor work

Makefile, base/builtin/int.c, base/rts/common.c, base/rts/common.h, base/rts/rts.c, base/src/re.ext.c, test/builtins_auto/modinit_large_int.act
We have thus far relied on link time redirection of malloc and friends. It's a little cleaner and more flexible to explicitly call GC_malloc or whichever malloc we want. That way we can still use the classic malloc if we want to and mix and match between different allocators.
acton_replace_allocator will now also change the allocator in all relevant C libraries we make use of in stdlib and similar. libuv and tlsuv are not affected, they always use GC_malloc, set from acton_init_alloc() since nothing in module initialization that is constant should come from these libraries and we want all libuv stuff to be GC_malloced, so that all things in the IO loops can be properly traced from the root set.
We're still doing link time redirection but this patch should put the necessary changes in …
=> Support custom malloc

compiler/Acton/Types.hs
Somewhat funny, the test_testing module gets type inferred to the wron types, which is sort of expected in a way I guess, because since it is test discovery, there are no explicit calls from test_runner to these functions yet... if there were, then we would infer the right types. Not sure what the best solution but at the very least it should be possible to explicitly type out the full type signature for test functions... but that was broken, it would find report_result function which took either a bool or None as first argument, but the correct type is a maybe bool. It now accepts this. Not sure if we should still continue matching on just bool and None as well, but I guess it doesn't hurt since some test functions that have inferred type signatures might get those types!?
=> Fix test discovery to catch proper type signature

base/src/__builtin__.act
This reverts commit 0089ed927ff3dffb96469a844e96cdc59a2d69cc.
Making the exception message optional has unexpected consequences for Telemetrify so I'm reverting this now. It's not a very important change. We'll try to bring it in at a later point in time.
=> Revert "Make exception msg optional"

test/stdlib/test_time.act
Bump up the accepted diff. It has started failing quite a lot in CI lately, with the diff being like 7 seconds. I think it's because of how we run the program from test.hs. We first get the time then build and run the test program. Presumably the build takes a little time and that leads to the larger diff. Maybe our builds are slightly slower now (after linking libc++??) or the CI runners are slightly slower.
If there's an actual problem with the time function it's likely to be off by much more.
=> Accept larger time diff in test_time

compiler/test.hs
Should really find a better way for expressing these tests. The cross-compilation tests all run in the same Acton project, for which actonc takes a lock, so only one test job at a time will run. That should be reflected here. Even if we have multiple repos, it woul might not be faster because zig / clang would ue all CPU cores per compilation so doing multiple compilations in parallel might not improve anything.
=> Bump up test timeout

cli/src/acton.act
success is None when we get an exception, so got to deserialize that properly.
=> Fix acton test

CHANGELOG.md, builder/build.zig
While the database backend is the only thing that have relied on libprotobuf-c so far, we have the need for it in other places so let's always add it in!
=> Unconditionally link in libprotobuf-c

compiler/Acton/Subst.hs, compiler/Acton/Types.hs, workspace/Semantics.txt
=> Fixo required since self is now parsed as a kwd param.

base/src/testing.act, cli/src/acton.act
`acton test list` will list all the test names in a project and it can take --json. It's possible to use --name to filter which tests to run, e.g. `acton test --name foo --name bar`.
The reported test count in the result summary was wrong, it counted modules when it should have counted tests. We now wait showing output until we've received the initial list of tests from each module.
=> Testing: list tests, name filter & fixes

base/src/testing.act, base/src/time.act, cli/src/acton.act, test/stdlib_tests/src/test_testing.act
Tests are now run multiple times for a minimum of
1ms (MIN_TEST_DURATION). Many small unit tests will run a bunch of times and we can thus get an average for performance numbers and we can detect flakiness. The whole display routine has been rewritten to be able to show such results. It also shows tests in progress in a more consistent manner.
Errors / failures were flipped. Now fixed.
Async actor test and env tests are now run properly. Previously we would actually start all such async tests at once, so they would run in parallel. The idea is that we should grab one test, let it run and once complete we move on to the next. This has now been corrected so it works as intended.
There's a bunch of to_json / from_json serialization functions but it doesn't work very well for some reason so …
=> Revamp testing

compiler/ActonCompiler.hs
I suppose aarch64-linux might be using some other CPU. We (or Zig?) should really have some better CPU detection going on I think but this should do it for now.
=> Default to apple_a15 for aarch64-macos

CHANGELOG.md, builder/build.zig
Haha, how silly, I had a hard-coded path from the early hack attempts and since I did all my testing with a repo where the dependency is called "dumbo" it all worked. Now using a true dynamic path!
=> builder: correct path to dep

base/src/testing.act, cli/src/acton.act
If a module encounters some crash when it runs the tests in that module, we now detect this by getting the program term_signal and still properly update the test result. For example from a test program that deliberately fails with an assertion:
Tests - module abort:
crash:                 ERROR (1 errors out of 1 runs in 1.000ms)
Module test error: .test_abort: t_testroot/src/abort.ext.c:8: B_NoneType abortQ_abort(): Assertion `0 == 1' failed.
1 out of 1 tests errored (1.940s)
=> Handle test crashes

base/src/process.act, cli/src/acton.act, test/rts_db/test_db_app.act, test/rts_db/test_tcp_client.act, test/rts_db/test_tcp_server.act, test/stdlib_auto/test_process.act, test/stdlib_auto/test_process_env.act, test/stdlib_auto/test_process_pid.act, test/stdlib_auto/test_process_wdir.act, test/stdlib_auto/test_process_write.act
Move workdir & env to end of list and make them optional. Nicer interface!
Add an optional timeout argument so we can say we want to terminate a program after some timeout period.
Added a new RunProcess which buffers stdout & stderr while waiting for the program to exit after which a callback is called. This is a much simpler interface for the scenario when we want to await a process to finish and then read the output.
=> Reorder process args & add RunProcess

CHANGELOG.md, Makefile
Copying the files would update mtime which in turn would trigger later build steps to run. Now with cp -a we avoid that and the whole build runs much faster when there are no changes!
=> Preserve mtimes to achieve make idempotency

Makefile
We always need to copy over these files. This was previously not a problem because __builtin__.ty that we have a dependency on would always be out-of-date and thus rebuilt because we previously copied it without preserving timestamps. One we fixed that, it revealed this problem!
=> Fix make check for base, now PHONY

CHANGELOG.md, base/src/file.ext.c
Since WriteFile.write() writes the whole content of the file (not append) we should truncate the file when opening it so we don't get the tail of the old file if our new content is shorter.
=> file.WriteFile: Truncate file

.github/workflows/test.yml, CHANGELOG.md, Makefile, cli/src/acton.act
This adds a test on MacOS v14. The GitHub runners for this job is apparently all Apple M1 so it also means we not get to test on arm64!
=> Test on MacOS 14 on Apple M1

CHANGELOG.md, Makefile, base/builtin/common.c, base/builtin/dict.c, base/rts/common.c, base/rts/common.h, base/rts/netstring.c, base/rts/rts.c, base/rts/rts.h, base/src/file.ext.c, base/src/net.ext.c, base/src/process.ext.c, base/src/re.ext.c, base/src/snappy.ext.c, base/src/time.ext.c, base/src/xml.ext.c, base/stdlib/numpy/ndarray.c, base/stdlib/numpy/ndselect.c, builder/build.zig
Since the introduction of the GC, we have been making use of link time redirection of malloc and friends in order to catch all invocations of these calls. It works but is less flexible as we are forced to use the GC-heap for everything. We would like to be able to mix GC-managed memory with manual memory management and thus we want to avoid doing link time redirection of malloc.
For a period of time, we've used a sort of hack where we dig out the real malloc through dlsym shenanigans, but that only works when malloc is in a libc that is dynamically linked. It won't work when statically linking libc. We do this so we can run with manual malloc during module init and avoid placing module constants on the GC-heap.
To disable link time redirection, we must make sure that all mallocs that we …
=> Stop redirecting malloc & friends

Makefile, test/stdlib_auto/test_process_many.act
libuv blocks most signals when it forks in the uv_spawn() call. I guess because signal handling can get messy around a fork.
The GC uses SIGPWR & SIGXCPU to pause & resume threads. We must not ignore those signals since it leads to a deadlock. When one thread initiates GC stop-the-world it will wait for all other threads to comply and if they ignore signals, they will never comply.
Also add a test program that runs lots of subprocesses so we get to exercise this code. I can reproduce the bug on like the 4th process down and we run 1000 so I'm quite confident in this fix working well.
=> Fix GC deadlock & uv_spawn

.github/workflows/test.yml
GDB is installed on Linux to enable printing backtraces on segfaults, sigill etc. We also enable core dumps with ulimit -c unlimited and enable the whole test directory on failures so we can analyze core dumps separately.
=> Install gdb, enable & upload core dumps

base/rts/rts.c, base/rts/rts.h
We just want to initialize jump0 once per worker thread which we now achieve by placing jump0 in our worker context wctx. Previous to this, we would rerun the $PUSH every time we entered wt_work_cb, and thus actually push a new exception jump point to the stack - effectively a memory "leak" with run-away memory consumption as a consequence.
=> Place jump0 in wctx

compiler/test.hs
The idea was to get better test coverage of like stress testing but I don't think it meets this since we still just have very short lived programs. What we really want is for a program to run for a longer period of time. The extra time it takes to run through the tests is slightly annoying, so I'm tuning it down to 2. Still keeping the basic support for running repeat tests so we can easily ramp it up again.
=> Reduce test run repeats

base/rts/rts.h, base/src/random.ext.c
Rather than seed our PRNG with time() which is second-granularity, we now feed in nanoseconds.
Running the test suite over and over would result in flakiness as we'd get the same random values and that in turn affects some of the file tests where it creates temp files (which would be the same due to random being the same). This fixes that.
=> Increase randomness

backend/build.zig, backend/client_api.c, base/build.zig, base/rts/io.c, base/rts/log.c, base/rts/log.h, base/rts/q.c, base/rts/q.h, base/rts/rts.c, base/rts/rts.h, base/src/logging.ext.c, builder/build.zig, compiler/Acton/CommandLineParser.hs, compiler/ActonCompiler.hs
This adds a mode for running the RTS without threads. It can be useful on platforms that do not have POSIX threads available, such as WASM.
Since one of the goals is to remove the need for pthreads, this must be chosen at compile time rather than run time. Use the --no-threads flag:
actonc --no-threads foo.act
=> Support no-threads RTS mode

base/src/testing.act, cli/src/acton.act
While we have only run 1 concurrent test within a module when in perf mode, multiple modules have been executed at the same time, so we've gotten useless results. This fixes that by serializing the test modules to run one by one.
We still run in full concurrency when not in perf mode.
=> Limit test perf concurrency to 1

base/builtin/str.c, test/builtins_auto/strings_and_bytes.act
The str.strip() method was not handling empty strings correctly. We would get back a \0 character instead of an empty string. Now fixed by returning input string if length is 0. I don't think it's an issue that you get back the actual string if you call strip on an empty string rather than a new string with the same value as you'd otherwise get.
=> Fix str.strip() to handle empty strings

Makefile, compiler/ActonCompiler.hs
Thus we can detect whether a program should be recompiled when the acton distribution itself has been modified.
=> Include acton(c) binary in uptodate check

base/src/testing.act
We now still print all the individual tests in a module so if there are tests that have completed, we still print those and then print the non-completed ones as module errors / crash.
=> Improve test module crash error printout

cli/src/acton.act
This makes it possible to run acton test --module foo to only run the tests in the module named foo.
=> Add --module to filter module to test

base/src/re.act, base/src/re.ext.c, base/src/uri.act, test/stdlib_tests/src/test_re.act
It is possible to define a matching group in a regexp that does not match while the overall regexp does match, in which case the individual group should be None. As such, the type has been updated to be a list[?str] instead of list[str] for both group and named groups.
The code has been updated to avoid segfault since the string offsets are unset (-1) when a group has no match.
New test case to test this.
=> Fix re groups for no match

base/builtin/str.c, test/builtins_auto/str_slice.act
The problem is really that slice is 0 long and allocating an array that is 0 long and then doing operations on it becomes UB so we SIGILL in testing since we now run tests in --dev mode (which comes with all sorts of UBsan).
=> Fix str slice outside of range

Makefile
Official zig build download page has removed the particular zig build we used. We cannot directly go to zig v0.12 which is the closest release to what we need, since some stuff we use was deprecated.
Meanwhile, we fix this by uploading the missing .tar.xz file to our own little mirror of the zig builds and use that for our build.
=> Temp fix (CI) build via zigballs

CHANGELOG.md, base/builtin/set.c, test/builtins_auto/set_test.act
It previously returned NULL, which is just invalid in so many ways. The type signature says it should return something and thus throw an exception if something goes wrong. Now it does!
Fixes #1789
=> Make set.pop() throw ValueError for empty set

.github/workflows/test.yml
In order to get decent speed on CI builds we are using caching. Github limits the cache size to 10GB in total and with all the jobs we have we reach above that. MacOS 14 was the last one we added which tipped us over 10GB so Github evicts one of the caches but since we're really using all of them we just end up with lots of churn. I tried to use a common cache among similar distros, like multiple versions of Debian, to increase reuse but somewhat unsurprisingly, it doesn't work out great.
Ever since we started vendoring in libraries and building it ourselves, the problems with supporting multiple versions of distributions and OS has been at a minimum. There have been very few issues, so arguably running all these tests for every PR is overkill. Thus, we're now reducing the PR builds to …
=> Reduce PR CI jobs & do nightly

Makefile, base/src/buildy.act, builder/build.zig, builder/build.zig.zon, cli/src/acton.act, compiler/ActonCompiler.hs, compiler/test.hs, test/compiler/test_deps/build.act.json
It is now possible to define a Zig package dependency in build.act.json, our own variant of Zig's build.zig.zon. We use this information to generate a build.zig.zon as well as inject in some places in build.zig, in order for things to work correctly. And it does work! Very cool!
Fixes #1848 
Fixes #1844
=> Support including Zig package dependencies

base/src/argparse.act, test/stdlib_auto/test_argparse.act
Rather than just print the top level help, --help will now print the help section for the most specific command found. For example: acton pkg --help now shows the help for the pkg command section.
Fixes #1747
=> argparse: --help shows help for most specific cmd

Makefile, backend/build.zig, base/build.zig, base/build.zig.zon, builder/build.zig, builder/build.zig.zon, builder/dependencies.zig, compiler/test.hs, deps/libnetstring/build.zig, deps/libuuid/build.zig, deps/libyyjson/build.zig
=> Ship libs as src and build on demand

Makefile, cli/src/acton.act, compiler/ActonCompiler.hs
Now split the cache into the zig global cache and the zig local cache. Zig had these separate from the beginning but as Zig didn't differentiate between them earlier, before the package manager, I didn't know what they were good for and so we ended up just using a single directory. Now that there is a package manager, we separate the global cache, which is used for downloaded packages, and the local cache which is used for built stuff.
The automatic clearing of the cache is kept but only applies for the local cache. The global cache is never automatically cleared, instead a warning is emitted once it crosses 10GB in size and for every additional 1GB in growth.
Fixes #1858
=> Revamp zig build caching

Makefile, base/src/buildy.act, cli/src/acton.act, compiler/ActonCompiler.hs
We want them out of view.. I don't think we ever need to clear them. This isn't a build cache like that, so it's fine for it to be persistent. It would be ideal to move actonc output like .c / .h / .ty files out-of-tree, but it's negligible compared to other things.
Also added cache size messages for global / local to be a little bit more precise.
Fixes #1864.
=> Move downloaded deps to .build/deps

base/rts/rts.c
This is triggered right now by a problem with Zig build concurrency. Zig gets the number of parallel worker threads to run by inspecting its affinity. This is a great approach since it works in containers / cgroups, unlike when just inspecting /proc/cpuinfo or similar. However, zig is run as a subprocess to actonc which in turn is run as a subprocess to acton, which is an Acton program. The Acton RTS sets the thread affinity in order to pin each worker thread to a CPU core. This affinity is apparently inherited from the acton RTS worker threads to actonc and finally to zig, so it thinks it can only run on a single CPU and thus.. it's rather slow.
I have been pondering the thread affinity topic in general for quite some time. I don't have any hard evidence, but I think that pinning to …
=> Don't set worker thread CPU affinity

base/build.zig, cli/src/acton.act
I know I tested these commands once or twice so not sure how I could have messed them up like this (attaching under pkg and not zig-pkg and thus conflicting with the pkg add/remove). Anyhow, that's fixed and added --artifact arg.
Also exposed rts/log.h since I noticed I want to reach it from an external package module.
=> Fix acton zig-pkg

Makefile, base/__root.zig, base/acton.zig, base/build.zig, base/rts/gc.zig, base/src/base64.act, base/src/base64.ext.c, test/stdlib_tests/src/test_base64.act
This adds a new stdlib module called base64. It does exactly what you think it does. What's slightly cooler is the way it is implemented. Base now includes a __root.zig file, which is the root module of base. It defines two functions:
export fn base64Q_encode(data: *acton.str) callconv(.C) *acton.str {
export fn base64Q_decode(data: *acton.str) callconv(.C) *acton.str {
These are written in Zig but using the C ABI, 'export' saying they should be exported, having the C calling convention and taking input and output of the Zig type called `acton.str`. I have created this new acton module in Zig which is meant to contain acton related things. In this case some types, although so far I have only gotten to implement the B_str type. Unlike C, Zig has modules so we don't have to treat everything …
=> Add Zig support in base for new base64 module

cli/src/acton.act
If a dependency is available both remotely as well as locally via a path, the local path should take precedence. A common scenario would be that the dependency normally is available as a download from the Internet but the user decides to fork the dependency and make changes to it. After cloning the repo, we can use the dependency just by updating the build.act.json and set the path to the local clone.
Fixes #1907
=> Let local dep path take precedence over URL

docs/acton-by-example/src/SUMMARY.md, docs/acton-by-example/src/ext/integrating_c_library.md, docs/acton-by-example/src/working_with_zig.md
This includes a page on how to integrate a C library into Acton code. We use the zlib C library to implement an Acton zlib modue for compression decompression. We go through memory allocation and other things one needs to keep in mind when working with C code around Acton.
=> Guide: integrating a C library

.github/workflows/test.yml
The iterations was meant at some point to catch errors but even with the error in mind (we had a problem at the time) we never saw this testing any errors, it's just too small and simple of a test. It's point and thus I'm removing it. I think it should also speed up the test execution by a bit since when we use the script style runacton execution, each invocation actually gets its own file, which means it's compiled anew and thus takes "some time". It feels in CI like this is 0.5~1s per iteration, so we're looking at 20-60 seconds of time for a whole test!?
=> Speed up CI run-linux by doing 1 iteration (not 50)

.gitignore, Makefile, compiler/ActonCompiler.hs
Acton.Builder in the compiler was an embedding of the builder so that we could generate it, but this haswon been moved to the acton cli, so we can remove it from actonc entirely!
=> Remove embedded Builder

compiler/ActonCompiler.hs
.root.c file are generated when a module has a root actor. If a .act module had a root actor previously which is now removed, the .root.c file should be removed too. Since determining which files previously had a root actor that no longer has one is sort of tedious, we just remove all .root.c files first and recreate them later if necessary.
Fixes #1930
=> Remove orphaned .root.c files

compiler/Acton/Syntax.hs, compiler/Acton/TypeEnv.hs, test/typeerrors/ex24.golden
Fixes #1811 
(opening on behalf of @sydow who's experiencing trouble logging in to GitHub)
=> Improved location determination for constraints

base/src/testing.act, test/stdlib_tests/src/test_logging.act, test/stdlib_tests/src/test_testing_asserts.act
Now assertEqual & assertNotEqual actually work properly for None values. Previously they only compared correctly for non-None values.
Also added a test of these testing functions.
=> Fix assert(Not)Equal & add tests

.github/workflows/test-app.yml, .github/workflows/test.yml
Add a GitHub CI reusable workflow to test Acton projects by just providing a git repo URL. The first project we test is the acton-yang repo, the YANG module & compiler.
=> Test acton-yang project

base/src/buildy.act
I think this is the first bug that I have checked in that is probably written by Copilot. I usually spot such things immediately since I let it write just a few lines at a time but the pattern here was probably somehow close enough so that it "looked right". Blargh. Anyhow, now fixed!
=> Fix so dependency "path" works

test/builtins_auto/actor_mutarg.act
The compiler currently complains about this, stating that mut leaks the actor seal, but I don't think that is right. I don't see how it is leaking...
kll@Kristians-MacBook-Air builtins_auto % acton actor_mutarg.act Building file actor_mutarg.act
Compiling actor_mutarg.act for release
ERROR: Error when compiling actor_mutarg module: Type error
|
2 |actor Foo(cb: mut() -> None):
|              ^^^
Leaking actor seal: mut
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
kll@Kristians-MacBook-Air builtins_auto %
=> Add test for actor with mut arg

compiler/Acton/CodeGen.hs, compiler/Acton/Kinds.hs, compiler/Acton/Types.hs, compiler/test.hs, test/compiler/mixed-dots/README.org, test/compiler/mixed-dots/src/foo.act, test/compiler/mixed-dots/src/main.act
so that Types will properly detect method invocation via class name even for imported classes.
=> Moved qualified name detection from Types to Kinds

compiler/Acton/Env.hs, compiler/ActonCompiler.hs
We had some tricky cases where we got compilation errors due to imports not working properly. It has to do with hierarchical modules, so like when there is a foo.act and a foo/bar.act. If we import foo.bar first into our compilation environment, the foo module will just be an empty module, but it will exist and so if we later on import foo, the compiler thinks it is already imported, won't read the .ty file and then proceed to (likely at least) give some error about whatever we tried to access in the foo module does not exist.
We now check explicitly if the module is empty. If it is, we try to import it by reading .ty file. We cannot differentiate between an actually empty module and a module that is just a placeholder, i.e. have only been created to form the structure to a submodule, and …
=> Fix hierarchical module import

cli/src/acton.act
If we run the compiler like `acton src/foo.act` in a project, we want to still build the project like a project, which includes things like first building dependencies. Previously, any invocation of acton on a single file would invoke single file compilation regardless of the location of the file. We now check if we are in a project and run the project build but with the file specified, so only the specified file is compiled.
Fixes #1949
=> Use BuildProject to compile files in project

compiler/Acton/Parser.hs, compiler/Acton/Types.hs
Changes the error in the issue to be a syntax error and adds location to related escaping type var error (see comment in the issue).
=> fixes #1963

test/stdlib_tests/src/test_net_tcp.act
We might get port collisions, so adding some retry to avoid flaky tests.
=> Retry TCP tests

.github/workflows/test.yml
Apple has EoL MacOS 12, we are getting warnings from Homebrew and Github has started the deprecation of version 12 on their Action runners.
=> Remove macos-12 from testing

base/src/buildy.act, cli/src/acton.act
The fetch of dependencies during acton build and that of acton fetch are now powered by the same code. DRY! Looking good, and more importantly it checks the fetched hash and actually compares it to the configured one.
Fixes #1966.
=> Check for hash mismatch when fetching deps

cli/src/acton.act
If we already have the deps, identified by their hash, on disk, we don't need to fetch them again!
Fixes #1952
=> Idempotently fetch deps

.github/workflows/test.yml
The GitHub runner cache relies on zstd, so in order to provide a consistent environment, where both the pre and post cache steps run consistently, we move the installation of build stuff before the cache step.
=> Install zstd before cache

builder/build.zig, cli/src/acton.act, compiler/Acton/CommandLineParser.hs, compiler/Acton/Env.hs, compiler/ActonCompiler.hs
The initial implementation of dependencies relied on discovering dependencies through their location in the special directory deps/ in the project root. Since we have subsequently added support for reading the dependencies from our build.act.json configuration file, we can now get rid of the first crude method of dependency discovery and rely entirely on configured deps.
Fixes #1999
=> Remove old deps discovery

.github/workflows/test.yml
Seems our hacks for getting the GitHub Action artifact steps no longer work. Guess Ubuntu 18.04 is dead for real, so removing and moving on...
=> top testing on Ubuntu 18.04

base/src/buildy.act, cli/src/acton.act
This way we keep track of the version of a dependency since the hash is the ultimate identity of a version. Previously, if we updated a dependency so its hash would be updated, we couldn't detect that since the local dependency copied into .build/deps was just identified by name.
Fixes #1997
=> Use hashes in deps dir name

cli/src/acton.act
The build.act.json of a project specifies the URL and hash of dependencies. Sometimes it is useful, in particular when doing development of a project simultaneously as improving one of its dependencies, that we want to use a local copy of a dependency. Changing build.act.json and add a path is one way, but it's a little bit awkward and I have ended up mistakenly committing the local "path": attribute more than once.. so here is an alternative, we can now specify depeednncy path overrides to acton using the --dep argument, e.g.
acton build --dep foo=../foo --dep bar=/some/path/to/bar
Which means that the dependency named foow ill used the local path ../foo instead of whatever is specified in build.act.json. The path can be absolute or relative. The dep paths are passed down, so if one of …
=> Make it possible to override dep path

.github/workflows/test.yml
We have a lot of Acton (Zig) build cache related issues now so we need to clear the cache to get builds to work. It's quite annoying since the Haskell Stack install is so slow. Separating caches lets us only clear the problematic acton cache.
=> Separate caches in CI

compiler/Acton/Types.hs
We construct the lists by prepending using :, which is more efficient O(1) in Haskell than appending O(n), but it ends up reversing the list of the tests and I think it's nice if we present the lists to the user in the same order in which they are defined in the source file. It is still grouped by test type, but at least there is some more semblence between list of tests and source file now.
Fixes #2019
=> Reverse order of tests

base/rts/rts.c
Launching LLDB on MacOS often just hangs. While it has worked at some point, my overall experience is that it does more harm than good. I usually disable it since dealing with hung lldb processes is such a pain.
=> Disable automatic trace print on !linux

Makefile
It's nice to be able to iterate on the compiler without getting the whole world rebuilt. I believe this dep was added when we embedded stuff early on in the compiler and thus needed the dep.
=> Do not let actonc depend on builder

base/src/process.ext.c
If the process has already exited, we can't send a signal to it!
=> Guard signal()

base/builtin/common.h, base/builtin/complex.c, base/src/__builtin__.act, docs/acton-by-example/src/SUMMARY.md, docs/acton-by-example/src/primitives/complex.md, test/builtins_auto/test_complex.act
This staticmethod constructor allows us to create a complex instance
from two Reals.
Add a test suite for complex.
Fix division to raise exception on zero-divison
The acton.guide has been updated with a page on complex numbers.
Add new RAISE macro to simplify raising exceptions from C code.
=> Add complex.from_real_imag()

base/builtin/hash.c
Bit shifting overflow is UB for signed integers. We now use unsigned (which are well defined for bit shift overflow) to avoid UB. Since we compile rather strictly (Zig's default to clang), any UB results in SIGILL.
=> Fix hash function, no signed overflow UB

base/src/testing.act, cli/src/acton.act
Run tests in individual processes
- crashes now only affect the single test, not others
- we can now capture stdout / stderr from tests
- these are printed if the test fails
- simplified logic in many places
Fixes #2048 
Fixes #1987
=> Revamp test running

base/src/net.ext.c, test/stdlib_auto/test_net_tcp.act
Also realign some test code on newer behavior of on_listen callback!
Fixes #2072.
=> Always call on_close in TCPConnection.close()

README.md, docs/acton-by-example/src/install.md, docs/acton-by-example/src/install_tip.md
Update the acton-by-example documentation with the latest guidelines for APT package repository signing keys.  Change the distro to stable from bullseye.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/actonlang/acton/pull/2080?shareId=df46971a-c4a2-4867-a79f-e32406fc7d9b).
=> Update acton-by-example documentation with latest APT key guidelines

compiler/actonc/package.yaml.in, compiler/lib/package.yaml.in
We haven't used them in quite some time.
=> Remove Alex & Happy build-tools

Makefile
I missed updating the file deps when I moved around things in the compiler, separating the lib etc. We now dive into the lib and find relevant .hs files.
Also after adding the lsp-server, the actonc target started building both binaries. It now only builds actonc. We can add in lsp-server later, perhaps to its own target, but it's unnecessary to compile both concurrently now when we really only want to recompile actonc. Given the new structure with a library, any change to the library means both actonc and lsp-server gets rebuilt, so we're doubling the work required by compiling both. Now reducing it back to just actonc.
=> Fix actonc make target deps

Makefile
** doesn't seem to be supported by Makefile at all. Other systems treat it a recursive wildcards, but I can't find support for that in Makefile, so probably my mistake to use that to begin with. Now using known-length path with wildcards to find all relevant source files for lib / actonc.
=> Avoid ** in Makefile wildcard

Makefile
The building of the CLI is special. It's an Acton project which we normally compile with the acton cli, but that's obviously cyclic here, so we need to compile with actonc. It is normally acton that does some initialization of build.zig.zon, but since we're invoking actonc directly here we can't do the same. actonc normaly receives a build.zig.zon written to disk by acton, which it then rewrites a bit. Unless build.zig.zon doesn't exist, in which actonc will also place the file there. There is no acton to write it for us, so by removing the file first, we get actonc to write it for us.
=> Ensure fresh build.zig.zon for cli build

cli/src/acton.act
We transform any relative input paths to absolute ones before we pass them when building deps. Each dep build then transform them back to relative ones, since that is what we want for Zig build, but this way, everything works!
Fixes #2094
=> Normalize --dep paths

compiler/actonc/Main.hs
Complete list of alternative output so we suppress the kind of messages we normally print.
=> Correct alternative output for --types etc

cli/src/acton.act
The build of sub-acton only takes a few arguments, the rest of arguments are either for ourself or is meant to go towards the main project build.
Fixes #2085.
=> Filter args to dep builds

base/build.zig, builder/build.zig, test/builtins_auto/int.act
Our signed integer types are now allowed to overflow. We use the straight C types and in the C specification, signed integer overflow is undefined behavior. Most C compilers are quite lax and don't enforce it in any way per default. We use Zig to compile and per default it enables all sorts of UBsan, and so we have inherited that behavior.
However, in Acton we think the sane behavior is for integer operations to be well defined and not change with compilation flags, plus we want decent performance and so overflow is the most sane behavior. That is now the case!
Some simple test cases are added to verify overflow works. u16 / i16 does not work, likely since the underpinning type is actually not 16 bits.
Fixes #2079
=> Let iN overflow

base/src/buildy.act, docs/acton-by-example/src/SUMMARY.md, docs/acton-by-example/src/pkg/local_dependencies.md, docs/acton-by-example/src/pkg/override_dependency.md
We used to allow path and url, in which case the path would override the url and this was useful to override with like a local fork of a dependency when doing development across multiple projects simultaneously. However, it's bad changing checked in files like build.act.json and so we added acton build --dep to override deps. It also has the benefit of being propagated to the build of dependencies, so if we have a main project that depends on foo and bar. In turn, foo depends on bar, so if we now override the path to bar, the same override is passed to the build of foo as to the main project.
Given that we have --dep, the old way of manually overriding the path in the configuration file is deprecated. We now block and require that only path OR url is set. Otherwise the user gets an error. …
=> Allow dep path OR url in build config

compiler/actonc/Main.hs, compiler/lib/src/Acton/CommandLineParser.hs
This restructure the top level main function in actonc a bit.
- we now accept a single file argument, not a list like before
- makes code simpler and I don't think we will use option to send in multiple files
- new --sub argument which instructs actonc it is running as a sub-compiler, from which we can infer certain behavior. We don't really use this much yet, but I think it will expand
- we do not take locks on single file compilation in --sub mode, so that we can run multiple concurrent actonc as a subprocesses to a parent acton compiler
- locking is more consistently handled
- improved detection if we are in a project or not and act accordingly
- cleaner main function
Related to #620 through non-locking under --sub
=> Restructure actonc main, file build & locking

cli/src/acton.act
Errors are already printed from streaming stderr so no need to print them again...
=> Don't print errors twice

base/src/buildy.act, cli/src/acton.act, compiler/actonc/Main.hs
This means multiple projects that use the same dependency will share it. We get working cache as well since it's the same path. Yay.
=> Use a global deps dir in ~/.cache

cli/src/acton.act
Recursively removing the cache dir can actually take some time so we risk concurrent access from our cleaning code and zig, which is bad. I also suspect zig might hang because of this.
=> Await cache cleaning

base/src/testing.act, test/test_testing/src/errs.act
Since we typically run many iterations of tests, we end up with a long log of messages. Most of them are likely the same. We now dedup this list, for example:
```console
stdout_capture:          FLAKY FAIL:  272 runs in 50.090ms
testing.NotEqualError: Expected equal values but they are non-equal. A: 1 B: 2
STDOUT:
== 140 test runs with this output:
Random number: 2
== 132 test runs with this output:
Random number: 1
```
=> Dedup stdout / stderr test output

.github/workflows/test-app.yml, .github/workflows/test.yml
v3 no longer works. We used v3 for a long time because v4 requires Node 20 which in turn requires a newer glibc which made it basically impossible to run on Ubuntu 18.04 and similar old distributions. But 18.04 broke anyway, so we removed it so now we are fine moving to v4. It should appraently be quite a bit faster...
=> Use upload/download-artifact@v4

base/builtin/str.c, base/src/xml.ext.c
If the string contains wide (Unicode) characters then nbytes > nchars, but nbytes must never be less than nchars.
=> Assert nbytes >= nchars for B_str allocator

cli/src/acton.act, cli/src/acton_cli/deps.act
acton build now reads dependencies recursively for deps, so if our current project depends on A and A depends on B, we will now dig out the B dependency and add it internally for resolving modules etc.
Fixes #2003
=> Support transitive dependencies

cli/src/acton.act
When adding transitive dependencies with a recursive search, do not override the main project dependencies. These can either be listed explicitly in the main project build.act.json or passed on the command line with "--dep foo=../path/to/foo".
=> Fix transitive deps

base/src/testing.act
The builtin exceptions have changed such that they now print the actual values as part of the exception message. Since we already print the values in the specific message we have for golden tests, we suppress the other printing of vals.
=> Avoid double printing values

compiler/lib/src/Acton/Types.hs
Push them further down into the methods instead
=> Don't store witnesses in class attributes

cli/src/acton.act
After we recurse into the main project dependencies (dependencies, ...) to build the tree of transitive dependencies we update main project dependencies in build_config, while preserving local overrides. But then we must also use build_config (and not all_deps!) for building the main project.
=> Fix main project local dep override

cli/src/acton.act
It is quite normal to have like ~diamond shaped dependencies in project, so the top project depends on A & B, and A also depends on B, so when we start sub-compilers to build dependencies, they will race to build B. One will make it first and the other will have to wait. It is unnecessary to print that build lock warning, it only confuses users (who think something has hung and aborts the whole build). Detecting this via TTY might not be ideal but it works for now.
=> Silence build lock for dependency builds

cli/src/acton.act
The TLS lib doesn't interoperate well with our GC. While tlsuv does allow custom mallocs, there is an asymmetry for where malloc / free is done for DNS addrinfo structs. We control the malloc side and point to GC_malloc while on the free side, a normal free() is used. That leads to crashes, so if the GC runs at the wrong time, we'll crash.
Since pkg upgrade is a very small and simple operation, memory usage is negligible and thus we can live without GC. It's ugly, but at least pkg upgrade works.
Clearly the solution is to fix the DNS resolution. We already have this working for TCPConnection, so should port that to TLSConnection.
=> Disable GC for acton pkg upgrade

cli/src/acton.act
Improve parsing of --dep arg & print nicer message on error. Use the parsed result instead of redoing the whole parsing when we pass on deps to sub-compilers.
=> Robustif dep arg parsing

compiler/actonc/Main.hs, compiler/actonc/test/typeerrors/ex1.golden, compiler/actonc/test/typeerrors/ex10.golden, compiler/actonc/test/typeerrors/ex11.golden, compiler/actonc/test/typeerrors/ex13.golden, compiler/actonc/test/typeerrors/ex14.golden, compiler/actonc/test/typeerrors/ex15.golden, compiler/actonc/test/typeerrors/ex16.golden, compiler/actonc/test/typeerrors/ex17.golden, compiler/actonc/test/typeerrors/ex18.golden, compiler/actonc/test/typeerrors/ex19.golden, compiler/actonc/test/typeerrors/ex2.golden, compiler/actonc/test/typeerrors/ex20.golden, compiler/actonc/test/typeerrors/ex21.golden, compiler/actonc/test/typeerrors/ex22.golden, compiler/actonc/test/typeerrors/ex23.golden, compiler/actonc/test/typeerrors/ex24.golden, compiler/actonc/test/typeerrors/ex4.golden, compiler/actonc/test/typeerrors/ex5.golden, compiler/actonc/test/typeerrors/ex6.golden, compiler/actonc/test/typeerrors/ex7.golden, compiler/actonc/test/typeerrors/ex8.golden, compiler/actonc/test/typeerrors/ex9.golden, compiler/actonc/test/typeerrors/funargs1.golden, compiler/actonc/test/typeerrors/funargs2.golden, compiler/actonc/test/typeerrors/funargs4.golden, compiler/actonc/test/typeerrors/funargs5.golden, compiler/actonc/test/typeerrors/funargs6.golden
Use the real filesystem path to the module where a type error was raised.  This means replacing "." with path separator and appending the ".act" suffix. So foo.bar@123 becomes foo/bar.act@123
This makes it possible for VS Code to create a clickable link to the file. Well, almost, because VS Code does not recognize "@" as a file - location separator. Not sure if the diagnostic package can be tweaked to use ":" instead of "@"?
=> Make type error location "clickable"

base/rts/rts.c, base/rts/rts.h
On Mac OS the default is 524288, which is too low for the recursion depth required by the acton-yang generators. On Linux it is 1 MB, where the current generators work, but it may just come back to haunt us when the model depth increases 👯 We now set the secondary threads stack size to at least 8 MB, or more if the primary thread stack size is larger.
=> Ensure thread stack size is at least 8 MB

base/__root.zig, base/src/base64.act, test/stdlib_tests/src/test_base64.act
We must use decoder.calcSizeForSlice() instead of calcSizeUpperBound() to get an exact number of bytes we will decode, without padding. If we allocate the maximum size including padding, we may decode less bytes and then our decoded buffer may end up containing garbage.
We also align with other languages (including Python) on the input and output types for encode and decode - the functions now work with Acton bytes instead of str.
=> Fix base64.decode buffer allocation, UTF-8 handling, change input/output to bytes

.gitignore, base/__root.zig, base/acton.zig, test/stdlib_tests/src/test_base64.act
=> Raise ValueError from base64.decode() if input is not base64 encoded

cli/src/acton.act, compiler/actonc/Main.hs
When cross-compiling on amd64 host for arm64, Zig picks the *baseline* default CPU. But that is not sufficient to compile Mbed-TLS, it needs AES. For other cross-compilation targets we already provide a default CPU model with the required instructions. We now use *[cortex_a72](https://en.wikipedia.org/wiki/ARM_Cortex-A72)* CPU for cross-compiling for `aarch64-linux-*`. This is the first AWS Graviton from 2018. Not sure if we should target something more modern? I guess it does make a difference in the Zig compiler output?
I also found that using *generic+crytpo* works for all cross-compile targets, but again, what does that mean in terms of other optimizations?
=> Fix aarch64 linux cross compile

base/src/testing.act
I'm not sure when this happens but I have gotten an exception thrown for a IndexError and this is the only place I can find. After this fix I can no longer reproduce (though reproduction case was probably <1% in the first place, so a little hard to tell). I suppose we don't have enough test output yet, but I don't really get why because we should print \n, so I think there should always be a second part that is at least the empty string... but I guess not. Doesn't hurt to be defensive.
Fixes #2188
=> Handle error during output deduplication

base/src/testing.act, compiler/lib/src/Acton/Types.hs, test/stdlib_tests/src/test_testing.act
This is meant to replace the existing AsyncActorTest. The main idea is to inject a test-arg object, of type AsyncT, instead of multiple loose arguments. We can encourage users to explicitly type the arg type and thus the test discovery becomes more robust. The AsyncT object has methods for signaling the result:
- .success(output: ?str=None) for a successful test, possibly with golden output
- .failure(exception: Exception) for a failing test
- .error(exception: Exception) for an erring test
Once we're happy with this, we will rewrite the other test types to follow the same style and remove the current ones.
Part of #2122
=> Add AsyncTest

base/src/testing.act, compiler/lib/src/Acton/Types.hs, test/stdlib_tests/src/test_testing.act
The new style of test discovery is based on a single, explicitly typed, argument to the test function. Relying on type inferrence for test discovery is brittle. If we knew something was a test, we could presume it would take a argument aligned with a test function and do type checking based on that, but test discovery is done after type inferrence & checking, so we don't know. Often the test function type signature can be inferred to something else and thus discovery doesn't work.
The new style using explicit types, like
def _test_foo(t: testing.EnvT):
...
Means test discovery becomes deterministic. We also make it more easy to extend the test environment since we can add new attributes to the EnvT object without affecting test discovery.
pure def _test_foo():
proc def _test_foo():
proc …
=> Test discovery 2.0

compiler/actonc/test/syntaxerrors/err1.act, compiler/actonc/test/syntaxerrors/err1.golden, compiler/actonc/test/syntaxerrors/err2.act, compiler/actonc/test/syntaxerrors/err2.golden, compiler/actonc/test/syntaxerrors/err3.act, compiler/actonc/test/syntaxerrors/err3.golden, compiler/actonc/test/syntaxerrors/err4.act, compiler/actonc/test/syntaxerrors/err4.golden, compiler/actonc/test/syntaxerrors/err5.act, compiler/actonc/test/syntaxerrors/err5.golden, compiler/actonc/test/syntaxerrors/err6.act, compiler/actonc/test/syntaxerrors/err6.golden, compiler/actonc/test/syntaxerrors/err7.act, compiler/actonc/test/syntaxerrors/err7.golden, compiler/actonc/test/syntaxerrors/err8.act, compiler/actonc/test/syntaxerrors/err8.golden, compiler/actonc/test/syntaxerrors/err9.act, compiler/actonc/test/syntaxerrors/err9.golden, compiler/lib/src/Acton/Parser.hs
There's lots of tools that strive to not write newlines at the end of a file. I have seen editors do this and lately I noticed AI agents produce files without a newline. The Acton parser throws an error at this, which seems excessive.. so now change that. The fix here is to just add a newline if one isn't present. That's a little hacky but simpler than changing parsing rules. I can't really see any drawbacks to this.
=> Don't require newline at end of file

.github/workflows/test.yml, Makefile, compiler/lib/package.yaml.in, compiler/lib/src/Acton/Parser.hs, compiler/lib/test/ParserSpec.hs, compiler/lib/test/parser_golden/fstring_empty_expression.golden, compiler/lib/test/parser_golden/fstring_invalid_format.golden, compiler/lib/test/parser_golden/fstring_missing_expression.golden, compiler/lib/test/parser_golden/fstring_unbalanced_format.golden, compiler/lib/test/parser_golden/fstring_unclosed_brace.golden, test/stdlib_tests/src/test_fstring.act
This adds support for f-strings. Under the hood it just rewrites it to use % operator style. We largely treat everything as a string, which greatly simplifies things since we are doing all this as a rewrite in the Parser where we do not yet have type information.
Fixes #2050
=> Support f-strings

base/src/testing.act
If test output doesn't match expected golden, show a diff instead of entire output vs expected!
=> Use diff for golden testing

.github/workflows/release.yml, .github/workflows/test.yml
1. Change name to pattern in artifact download for Debian packages
2. Process each .changes file individually in reprepro loop
3. Update deprecated set-output syntax to use GITHUB_OUTPUT
4. Improve version extraction and use in update-homebrew job
=> Fix release workflow issues

test/stdlib_tests/src/test_numpy.act
- Add comprehensive test coverage for numpy module functions
cp -a base/__root.zig base/Acton.toml base/acton.zig base/build.zig base/build.zig.zon base/builtin base/rts base/src base/stdlib dist/base/
cd dist/base && ../bin/actonc build --dev --auto-stub && rm -rf .build
Building project in /Users/kll/dt/acton/dist/base
Compiling __builtin__.act for development
Already up to date, in    0.004 s
Compiling xml.act for development
Already up to date, in    0.000 s
Compiling uri.act for development
Already up to date, in    0.000 s
Compiling time.act for development
Already up to date, in    0.001 s
Compiling term.act for development
Already up to date, in    0.000 s
Compiling snappy.act for development
Already up to date, in    0.000 s
Compiling re.act for development
Already up to date, in …
=> Expand numpy test suite

base/src/testing.act, test/stdlib_tests/src/test_testing_asserts.act, test/stdlib_tests/test/golden/test_testing_asserts/assert_equal, test/stdlib_tests/test/golden/test_testing_asserts/assert_not_equal
If the `testing.assertEqual(a, b)` assertion fails, we now include the diff output in the exception message. That is in addition to the A, B values which are also printed in full.
I find that in this case the full output is also useful if one wants to copy & paste the output and update the expected value in the test.
=> Include diff in testing.assertEqual(a, b) exception

.github/workflows/test.yml
- Fixed GitHub Actions workflow to properly substitute VERSION variable in Homebrew PR creation
The `peter-evans/create-pull-request` action was using shell variable syntax `${VERSION}` in YAML fields that are evaluated by GitHub Actions, not by the shell. This caused the literal string `"${VERSION}"` to appear in:
- PR titles (e.g., `acton v${VERSION}`)
- Branch names 
- Commit messages
Changed to use GitHub Actions expression syntax `${{ env.VERSION }}` for proper variable substitution in the action parameters.
The fix will be validated when the next release is created - the Homebrew PR should show the actual version number instead of the literal `${VERSION}` string.
=> Fix VERSION substitution in Homebrew PR creation

compiler/actonc/Main.hs, compiler/lib/src/Acton/Boxing.hs, compiler/lib/src/Acton/CPS.hs, compiler/lib/src/Acton/CodeGen.hs, compiler/lib/src/Acton/Converter.hs, compiler/lib/src/Acton/Deactorizer.hs, compiler/lib/src/Acton/Env.hs, compiler/lib/src/Acton/Kinds.hs, compiler/lib/src/Acton/LambdaLifter.hs, compiler/lib/src/Acton/Normalizer.hs, compiler/lib/src/Acton/Prim.hs, compiler/lib/src/Acton/QuickType.hs, compiler/lib/src/Acton/Syntax.hs, compiler/lib/src/Acton/TypeEnv.hs, compiler/lib/src/Acton/Types.hs
This makes docstring an attribute on NameInfo so that we can more easily work with it throughout the compiler and more (LSP!!).
=> Add docstring to NameInfo

compiler/lib/src/Acton/Env.hs, compiler/lib/src/Acton/Types.hs
when scanning __init__ for attributes
=> Fix unintended dependency on a complete scope

base/src/argparse.act, test/stdlib_auto/test_argparse.act
Add support for short option aliases (e.g., -v for --verbose) with validation and grouping capabilities.
Features:
- Short options via optional 'short' parameter in add_bool/add_option
- Grouped boolean flags (-abc = -a -b -c)
- Inline values for options (-ofile.txt, -n42)
- Alphanumeric validation for short option characters
- Conflict detection for duplicate short options
- Updated help text to show both forms (-v, --verbose)
- Comprehensive test coverage for all short option features
Also convert string formatting to f-strings for improved readability.
Fixes #2279
=> argparse: add short options support

compiler/actonc/Main.hs, compiler/lib/src/Acton/CommandLineParser.hs
Refactor command-line parsing to support global options (--tty, --debug, --quiet, --timing) that work across all subcommands. This eliminates duplicate field definitions between CompileOptions and BuildOptions, providing a cleaner architecture where global options are defined once in GlobalOptions and shared across all commands.
Key changes:
- Add GlobalOptions type with gtty, gdebug, gquiet, gtiming fields
- Remove duplicate fields from CompileOptions and BuildOptions
- Update all commands (build, doc, version) to use global options
- Thread GlobalOptions through the compilation pipeline
- Maintain backward compatibility with existing command-line interface
=> Add global command-line options to actonc

base/src/__builtin__.act, base/src/argparse.act, base/src/http.act, base/src/logging.act, base/src/testing.act, base/src/time.act, base/src/uri.act
Replace more % formatting and string concatenation with f-string syntax
Slice expressions don't work in f-strings, so those are still kept.
=> More f-strings for stdlib

base/src/process.act, test/stdlib_tests/src/test_process_env.act
We don't need to do PATH injection in `RunProcess` actor, it uses `Process` internally.
=> Remove unneeded code in process.act

compiler/actonc/Main.hs, compiler/actonc/package.yaml.in, compiler/actonc/test/syntaxerrors/err1.golden, compiler/actonc/test/syntaxerrors/err2.golden, compiler/actonc/test/syntaxerrors/err3.golden, compiler/actonc/test/syntaxerrors/err4.golden, compiler/actonc/test/syntaxerrors/err5.golden, compiler/actonc/test/syntaxerrors/err6.golden, compiler/actonc/test/syntaxerrors/err7.golden, compiler/actonc/test/syntaxerrors/err8.golden, compiler/actonc/test/syntaxerrors/err9.golden, compiler/actonc/test/typeerrors/funargs3.golden, compiler/lib/package.yaml.in, compiler/lib/src/Acton/Diagnostics.hs, compiler/lib/src/Acton/Parser.hs
This integrates the diagnose library with megaparsec to provide beautiful error messages.
The integration only affects actual megaparsec parse errors. Context errors and indentation errors continue to use their existing error handlers.
=> Use diagnose lib for printing parser errors

compiler/lib/src/Acton/Env.hs
Reverts actonlang/acton#2328 because it no longer builds acton-yang.
=> Revert "Treat skolemized tyvars as constants when computings LUBs/GLBs"

compiler/lib/src/Acton/Parser.hs, test/core_lang_auto/after_expressions.act
`after X:` used to be constrained to just local functions but we now allow any expression so that we can call methods on objects or remote actor methods etc.
Fixes #1458
=> Allow anything after after

base/builtin/str.c, test/builtins_auto/test_str.act
If the haystack str we are looking for the needle in is shorter than the needle, we would calculate an incorrect starting position, potentially pointing to uninitialized memory. Now explicitly check length to make sure we stay within bounds of haystack str.
Added some test cases but since we often allocate memory deterministically, I can't reproduce the issue I saw with this test. However, the out-of-bounds problem that I saw when running `acton test` no longer occurs in hundreds of test runs - it used to pop up in like half the runs previously.
Fixes #2350
=> Fix .endswith() for short / long str

compiler/actonc/package.yaml.in, compiler/lib/package.yaml.in
I don't quite understand how or why but it seemed we got a lot of complete rebuilds of the Acton library which underpins actonc. stack / ghc would say something build dependencies being changed and then "unregister" the whole acton library and then rebuild it from scratch. That's fairly annoying given that it takes quite a long time.  Doing `make` and `make test` interleaved would pretty much result in rebuilds every time, presumably because the list of dependencies was different for the test suite vs the actual library?
By simplifying dependencies for actonc / acton lib it seems we avoid this situation and every `make` or `make test` invocation now only builds the changed stuff. Much better!
This was extra annoying using AI code tools since they'd tend to shift between `stack test acton` …
=> Avoid rebuilds for actonc

cli/src/acton.act, compiler/actonc/Main.hs, compiler/lib/src/Acton/CommandLineParser.hs
Renamed debug mode to verbose mode. I think this much better aligns with what it does and avoids confusion with debug builds. Also adding a --verbose-zig option since I found that getting verbose zig output is normally not what we want. It's two very separate use cases to do --verbose for verbose output from actonc and --verbose-zig for getting debug output about the low level Zig based build process.
Fixes #2097
=> Revamp actonc debug / verbose mode

base/src/__builtin__.act, base/src/__builtin__.ext.c, test/builtins_auto/test_repr_str_type_none.act
Just like we made str(?value) we now allow repr() and type() to take an optional type, which makes it more convenient to use repr() & type()
There are functions like optional_repr among Acton application to work around this - those are no longer needed!
=> Let repr & type accept an optional value

base/src/logging.act, test/stdlib_tests/src/test_logging.act
We can pass a data dict to logging functions, like:
log.init("msg", data={"name": name})
The data argument is now a `dict[key, ?value]`, it used to require that every item passed in was a non-optional value. We now allow optional values, which is just much more convenient as the user can feed in whatever they have, not having to think about unwrapping the optional value. This work is really the spiritual continuation to when we changed to str(?value).
Fixes #2381
=> Allow logging of optional values

.github/workflows/webex-notifications.yml
Bah, so we were subject to shell escaping in handling the commit messages, like `style` backticks would invoke shell execution. Avoid that by using environment variables.
Also make the title a little less visually intrusive by only having the PR part be an actual link - should reduce clutteriness.
=> Simplify Webex notif & handle escapes

CHANGELOG.md, compiler/actonc/Main.hs
These fields in Paths are not used ever since we switched over to using Zig and its out-of-tree style building in a cache dir, so object files and archives (that used to go in the lib dir) end up in the cache dir instead.
Fixes #2383
=> Remove sysLib & projLib

base/builtin/str.c, test/builtins_auto/test_bytearray.act, test/builtins_auto/test_bytes.act, test/builtins_auto/test_str.act
bytes.startswith() wouldn't recognize equality when the needle is the same length as the total haystack, i.e. `b"foo".startswith(b"foo")` would return `False`. It's now fixed!
Same issue for bytearray and the same fix. There are a handful of new tests for covering .startswith(). In addition the test_bytes.act and test_bytearray.act modules have been restructured and aligned on the test style we have in some other builtin test styles. Small simple functions for each test with a bool return value and not much else. Simple!
Fixes #2399
=> Fix bytes.startswith() when needle length equal to haystack length

base/src/http.act, test/stdlib_tests/src/test_http.act
The HTTP Server actor decodes parts of the HTTP request to str. If the
part is not a valid UTF-8 string, it is not a valid HTTP request, so we
stop processing.
=> Handle malformed HTTP request gracefully
